### ISSUE TITLE
Dostupnost u ANL

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#10]
dostupnost u článků z báze "Výběr článků v českých novinách..." lze generovat z pole 910a

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
Ano, ale doplníme ji pouze pro tu knihovnu, která záznam vytvořila (jedno pole 910) i když stejný dokument vlastní mnoho jiných knihoven. Nebude to pro uživatele matoucí?

**Comment by PavlinaDolezalova** [comment]
Po vzoru mezinárodních bibl. systémů AGRIS, INIS, FSTA jsme myslela, že knihovna v 910a by byla garantem plného textu za všech okolností. Pokud ale CPK bude schopno dostupnost nabízet iv dalších knihovnáchy (podle 773zxt ?), tak to samozřejmě bude ještě lepší (asi problém v číslech a ročnících?) Vlastnit titul jako takový ještě neznamená, že i ostatní knihovny budou mít příslušná čísla. Proberu s SDRUK pro bibliografii.

**Comment by lenkamaixnerova** [comment]
to může ale platit pouze u baze ANL, u ostatních článkových bibliografií to může být jinak

**Comment by Stoklasovab** [comment]
Probereme na jednání 12.11. Je už známo stanovisko SDRUK pro bibliografii?

**Comment by PavlinaDolezalova** [comment]
Dotazník mezi aktuálními členy SDRUK pro bibliografii proběhl, výsledek mám. Další podklady dávám dohromady.

**Comment by Stoklasovab** [comment]
Výsledek je slibný, těšte se na příspěvek Pavlíny i její další smělé plány :-)

**Comment by Stoklasovab** [comment]
Většina stávajících členů SDRUKu je ochotna garantovat dostupnost plného textu pro ANL. Info přes ANL - půl roku testování.

**Comment by PetraZabickova** [comment]
Chápu tedy správně, že máme u záznamů z ANL doplnit dostupnost dle pole 910?

**Comment by lenkamaixnerova** [comment]
Je to jedna z možností a asi zatím jediná možná. Nejlepší by bylo, kdyby u článku došlo k rozpoznání titulu a podle titulu by měl uživatel k dispozici seznam institucí, které daný titul vlastní. Zdraví Lenka



 Od:   Petra Žabičková <notifications@github.com> 
 Komu:   moravianlibrary/CPK <CPK@noreply.github.com> 
 Kopie:   lenkamaixnerova <maixnero@nlk.cz> 
 Odesláno:   3.12.2015 14:29 
 Předmět:   Re: [CPK] Dostupnost u ANL (#10) 


 
Chápu tedy správně, že máme u záznamů z ANL doplnit dostupnost dle pole 910?

**Comment by PavlinaDolezalova** [comment]
Mám přehled knihoven, které chtějí být garanty článku, seznam sigel pošlu. U těchto případů by bylo možné využít 910a v bázi ANL a pokud to bude zároveň zapojená knihovna, tak by tento údaj nebyl fiktivní jednotkou z 910a báze ANL, ale byl by nahrazen skutečnou jednotkou z katalogu knihovny (tedy pokud bude možné odfiltrovat přes údaje ročníku a rozsahu čísel konkrétní knihovní jednotky. Další dostupnost bude pravděpodobně nutné řešit např. SKC/seriály  nebo přes data zapojených knihoven, v obou případech shodou ve 245 a 015, 022, 020  a budeme doufat, že se opravdu k článku uživatel dostane.

**Comment by paulusova** [comment]
Tým realizující VPK by byl rád, kdyby při linkování článků na zdrojový dokument bylo prolinkování omezeno pouze na typ dokumentu periodika, ISSN a rok. Můžeme to realizovat, ale nenajdou se tak periodika, která jsou zapsaná jako kniha (popsaná čísla dohromady nebo z důvodu chyby záznamu), kterých není zanedbatelné množství. Souhlasíte s touto úpravou?

**Comment by PavlinaDolezalova** [comment]
Asi v této fázi nelze zatím řešit jinak. Souhlasím. Snad v budoucnu nalezneme takové řešení, které postihne i periodika bez ISSN a další dokumenty.

**Comment by lenkamaixnerova** [comment]
A jak to bude např. s kapitolami v knize? My do analytiky zařazujeme i tzv. kolektivní monografie.

**Comment by PavlinaDolezalova** [comment]
Posíláte do ANL z Bibliomediky i kolektivní monografie? Domnívala jsem se, budete do souborné článkové báze posílat pouze některé méně závažné lékařské periodické tituly. Předpokládám, že integraci Bibliomediky do CPK bude NLK řešit samostatně od ANL i v četně toho, zda-li zůstane pro koncové uživatele v CPK pouze bibliografickou databází, či zda bude zvolen nějaký způsob propojení na plné texty.

**Comment by xmorave2** [comment]
Kdybychom to uměli udělat hezky, tak bychom to dávno udělali.
