### ISSUE TITLE
Oblíbené / Tisknout vybrané

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#100]
Bude možné v budoucnu získat pro tisk nějaký kompaktnější seznam vybrané literatury než je tomu nyní a poslat e-mailem a exportovat vybrané bude i pro nepřihlášené?
![cpk_oblibene](https://cloud.githubusercontent.com/assets/15088603/14254179/ea3a0664-fa8e-11e5-96fc-56a8cc47c06e.jpg)

**Comment by paulusova** [comment]
Poslat e-mailem a Export pro nepřihlášené bude v příští verzi. O úpravě seznamu pro tisk jsme neuvažovali, chybí vám v něm něco?

**Comment by PavlinaDolezalova** [comment]
Nechybí, naopak přebývá. Myslím, že by stačil jen řádkový výpis (třeba ISBD či tak nějak, což nynější zobrazení nabízí) na šířku stránky (teď se řádky zalamují v tabulce). Nejsou třeba velké šedivé ikony ani označení druhu dokumentu - články a stačila by černobílá barva.
[Prohlédnout záznamy.pdf](https://github.com/moravianlibrary/CPK/files/221118/Prohlednout.zaznamy.pdf)

**Comment by PavlinaDolezalova** [comment]
viz také již uzavřené #12, #13 a #14 - tj. práce s oblíbenými položkami i pro nepřihlášené.
