### ISSUE TITLE
Přihlašování přes MojeID

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#101]
Je v plánu implementace přihlašování přes MojeID? Vím, že se to řešilo,a le netuším jestli se to dostalo do požadavků. Vzhledem k ambicím NIC.CZ  a projektu MojeID na našem území bych považoval podporu tohoto způsobu jako velmi vhodnou.

**Comment by paulusova** [comment]
Na betě momentálně není, protože jsme měnili přihlašovací okno, ale počítáme s tím a v příští verzi by mělo fungovat.
