### ISSUE TITLE
Nastavení/výchozí řazení

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#102]
Chybí mi nějaký krátký popis co která volba ve skutečnosti znamená. Co je nám jasné, běžnému uživateli být jasné nemusí. Například:

- nejrelevantnější: zobrazí výsledkay podle toho, jak odpovídají vámi zadanému zadání. Zohledňuje se jestli je hledaný výraz vyskytuje v názvu, vedlejším názvu nebo například v popisu.
- nejnovější: výsledky seřadí podle data vydání dokumentu od nejnovějších po nejstrarší
- nejpůjčovanější: výsledky seřadí s ohledem na počet výpůjček dokumentů v jednotlivých knihovnách
![Uploading Screenshot at kvě 05 10-23-16.png…]()

atp.

**Comment by PetraZabickova** [comment]
Rádi bychom znali názory ostatních, protože řazení dle nejpůjčovanějšího jsme měli v plánu zcela odstranit. Problematické je použití jakéhokoli řazení mimo relevanci při hledání obecnějších dotazů. 

Chápeme potřebu vysvětlivek a nápověd, ale v daném případě si nejsme jisti, že jsou potřeba a navíc na daném místě nevíme, jak ji umístit přehledně a nerušivě. Samozřejmě, že počítáme s vysvětlením chování hledání a zobrazení výsledků v nápovědě.

Budeme rádi taky za upozornění na nějaké webové vyhledávače a portály, které mají dobře udělanou kontextovou nápovědu. Nám se zatím nepodařílo nic, čím bychom se chtěli inspirovat, najít.

**Comment by lenkamaixnerova** [comment]
řazení podle nejpůčovanějšího bych taky nedávala, vysvětlivky k relevanci bych nedávala

**Comment by jankanka** [comment]
Volby, ktere jsou nyní k dispozici, podle mého názoru stačí a jejich názvy "mluví". Nápověda mě napadá jen velmi stručně po najetí myší na prvek toho drop-down menu (nejaky onHover?). Prisne vzato z hlediska pouzitelnosti - ta menu (pocet zaznamu a razeni) by opravdu (jako kazdy jiny prvek) mela mit nejaky label, ale tady hodne setrime mistem a doufame, ze je to samovysvetlujicic... S tim razenim dle pujcovanosti bych byl opatrny - pokud to nebude zalozeno na spravnych a velkych datech, radeji bych nedaval.

**Comment by Stoklasovab** [comment]
Stávající volby jsou ok, půjčovatelnost vyhodit.

**Comment by vodomilka** [comment]
Zrovna půjčovanost je ale parametr, který by zajímal uživatele, podle toho, co nám říkali v UX testování.
I když by při ostrém spuštění nebyla k dispozci, můžeme alespoň hledat shodu, jak sbírat společně data, která toto řazení umožní?

**Comment by zabak** [comment]
Data dostáváme v poli 996. Nicméně Radek Záhořík zmiňoval, že Dilia má oficiální statistiky půjčovanosti v knihovnách, což by byla druhá cesta.

**Comment by Stoklasovab** [comment]
Zatím vyhodit a postupně zkusit realizovat.
