### ISSUE TITLE
Detail záznamu/Komentáře: Notice: Undefined index: reviews

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#104]
Notice: Undefined index: reviews in /data/www/beta.knihovny.cz/VuFind-2.x/module/CPK/src/CPK/RecordDriver/SolrMarc.php on line 525

**Comment by paulusova** [comment]
Pořád se ti to tam zobrazuje? Na betě ani na frontu to nevidím.

**Comment by black23** [comment]
Teď se zdá, že to už je ok. Zavírám.
