### ISSUE TITLE
Ikona notifikací po přihlášení

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#105]
Ikona s vykricnikem, ktera prihlasenem oznamuje nejaky problem je dobra vec. Ukazoval jsem to nekolika beznym uzivatelum a nikdo nechape jeji vyznam, protoze ten vykricnik temer zastini zvonecek. Takze neni vlastne poznat, co ze to ma byt. Idealni by bylo zmenit to tak, ze u zvonku bude prilepena vyrazna (cervena, oranzova) plocha s cislem. Ten bude odrazet pocet hlaseni (problemu). Tento zpusob se vyuziva v ruznych sluzbach, napriklad v ebankovnictvi a lide to znaji. Dale by bylo skvele, kdyby se text notifikaci nevypsal az po kliknuti, ale jen po najeti mysi nad zvonek. Opet vetsina mych testeru nepocopila, ze maji klikat.

**Comment by PetraZabickova** [comment]
Děkujeme za návrhy.

Číslo s počtem notifikací jsme zvažovali a nakonec jsme od něj ustoupili, protože nám přišlo, že použití notifikace příliš komplikuje.

Nedokážeme totiž notifikaci označit jako přečtenou, tudíž číslo by po přečtení nezmizelo, ale zůstávalo. Má smysl počet i takovém případě?

**Comment by black23** [comment]
Potom cislo smysl nema. Tak co vypsat napriklad "Vzkaz z knihovy". Jestli to nebude dlouhe. Nebo neco podobneho.

**Comment by zabak** [comment]
Na druhou stranu: uživatel nemá ty notifikace jen přečíst, on má hlavně ty problémy vyřešit, tj. knihy vrátit, registraci prodloužit, pokuty zaplatit. Když to udělá, nemá tam žádné číslo a je spokojený. Co může být problém je ale to, že číslo bývá obvykle bílý text v červeném kolečku a to celé na jinak barevné ikoně. To tady neplatí.

**Comment by vojtisev** [comment]
A nemohla by ta ikona jenom zčervenat, popř. to rozpohybovat?

**Comment by black23** [comment]
@zabak Jiste, ma ho to vest k nejake akci. Problem, ale je, ze uzivatel casto netusi, co to tam nahore je. Takze to cele je jen marna snaha. Udelejme to tak, at tam tou mysi zajede. Jestli tam bude cislo nebo nejaky text je asi jedno.

**Comment by zabak** [comment]
Co kdyby se to občas (velmi málo často) nějak pohnulo? Třeba krátce po přihlášení uživatele. Aby si možná všimnul. Třeba by se to mohlo "objevit" až po vykreslení celé stránky.

**Comment by zabak** [comment]
@vojtisev nevšiml jsem si, že to není nový nápad :-)

**Comment by black23** [comment]
Co ostatní?

**Comment by vodomilka** [comment]
Je škoda, že nelze realizovat původní návrh @black23 s číslem u zvonečku. Jsem za řešení, které bude co nejvíc podobné řešením, které uživatelé již znají odjinud. Tady na githubu je u zvonečku jen modrý puntík, když jsou nepřečtené notifikace. Bylo by možné jen dát jinak barevný puntík při nedořešených problémech? Pokud by vše bylo OK nechat bez puntíku? Pohybující prvek mi tam nesedí, jinde to nepoužíváme, navíc nevím, jestli by to nekomplikovalo co nejlepší přístupnost pro uživatele se zrakovými problémy.

**Comment by PetraZabickova** [comment]
Jak uz jsem psala na začátku nedokážeme rozpoznat zda uživatel notifikaci již četl pokud se znovu přihlásí, protože si tyto informace na portále o čtenářích nedržíme.

Můžeme zobrazit číslo s počtem notifikací (pokud nějaké jsou) nezávisle na tom, zda již přečtené jsou nebo ne.

Souhlasíte?

**Comment by Stoklasovab** [comment]
Nějaký symbol + číslo, po vyřešení snad zmizí, to opakované zobrazení, pokud je nutná nějaká akce, až tak moc nevadí.

**Comment by zabak** [comment]
Souhlasím, notifikace v CPK nejsou jen zprávy, je to oznámení problémů a cílem je problémy vyřešit, ne si o nich počíst. Takže to že bude vidět číslo, dokud problémy nezmizí je správně. Otázka je, jestli to císlo má být červené, když je celý portál červený. Skoro bych řekl, že by to chtělo nějakou odlišnou barvu - třeba modrou.

**Comment by HankaHornychova** [comment]
Přimlouvám se za zobrazení čísla s počtem notifikací. Může být klidně v barvě portálu, uživatel ho určitě zaregistruje. Není nutné kazit (příjemný) design stránky nějakou jinou barvou.
Ze stejného důvodu bych se přimlouvala za statický prvek. Pohybující se prvek může zbytečně odvádět pozornost uživatele od obsahu portálu.

**Comment by Stoklasovab** [comment]
Jsou zde rozporuplné názory - symbol + číslo versus pouze číslo. Prosím o další názory a uzavřeme 22.8.

**Comment by vodomilka** [comment]
Symbol (zvoneček?) plus číslo, jenom číslo by mi přišlo méně jasné, zvlášť, pokud nepočítáme, že by se objevilo nějaké vysvětlení při najetí myší.

**Comment by jrmeixner** [comment]
Souhlasím se symbolem (zvoneček) plus číslo (počet notifikací) - obdoba řešení co má GitHub.

**Comment by Stoklasovab** [comment]
Vede symbol (zvoneček) + počet notifikací

**Comment by Stoklasovab** [comment]
Vykricnik a cislo.
