### ISSUE TITLE
Nepřehledné a neúsporné zobrazení aktuálních výpůjček

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#107]
Naše testovací skupinka prohlásila zobrazení výpisu výpůjček za nepřehledné. Je to dáno tím, že se nezobrazují obálky, ani nahrazující piktogram a levý část prostoru je tak zcela nevyužitá. Název je nevýrazný. Naopak červené podbarvení hlášky "Jednotka měla být vrácena." zabírá neúměrně velikvý prostor. Pokud má čtenář více výpůjček seznam se velmi dlouhý a fukce "prodloužit vybrané" ztrácí smysl, protože málokoho napadne, že dole jsou záznamy, které je možné označit.
Při najetí myší nad "Jednotka měla být vrácena." text změní barvu na červenou a stává se téměř neviditelným.
Pokud by bylo možné změnit formulaci u včas nevrácených jednotek z Půjčeno do: 9. 5. 2016 na mělo být vráceno 9. 5. 2016, prospělo by to pochopení uživatelem.
Obecně bych navrhoval zobrazovat údaje jako sloupce tabulky = jedna položka by pak zabrala va výšku měně místa. Mohlo by to vypadat například takto:
| obálka | název, autor | do kdy/mělo být vráceno | varování na překročení |

![screenshot at kve 19 09-24-58](https://cloud.githubusercontent.com/assets/5516936/15385723/abba94fc-1da3-11e6-9e59-73b6fbdbbba1.png)

Ostatní jsou se současným stavem spokojeni?

**Comment by PetraZabickova** [comment]
Obálky výpůjček samozřejmě zobrazujeme, včetně prolinku do úplného záznamu publikace. Pravděpodobně se jedná o chybu způsobenou tím, že vypůjčený konkrétní záznam není zaindexovaný. Alternativně může být chyba v konfiguraci Vaší knihovny. V tuto chvíli nemůžeme ověřit, protože žádný z testovacích uživatelů Vaší knihovny, které máme k dispozici nemá žádnou výpůjčku. Prosím o zaslání identifikátorů publikace, kde obálka chybí nebo vytvoření testovacích výpůjček některému s testovacích uživatelů Vaší knihovna.

Jinak děkujeme za návrh, tabulkové zobrazení zvážíme (vyzkoušíme).

**Comment by black23** [comment]
ID = tre.59566, na dalším testování se můžeme domluvit emailem.

**Comment by black23** [comment]
Aby to nezapadlo. Obálky vyřešíme a asi s tím nebude problém, ale co obecně zobrazení aktuálních výpůjček? Co ostatní, jaký máte názor viz mé konstatování a návrhy v prvním postu?

**Comment by vojtisev** [comment]
Také se mi nepodařilo nasimulovat výpůjčky s obálkami (testovací uživatel MZK 705). Já mám trochu rozporuplné pocity - myslím, že se to určitě dá ladit (a pokud to testují uživatelé a je to pro ně nepřehledná, pak je to dost jasný signál), např. checkboxy nejsou u každého řádku (?). Na druhou stranu mi to připadá funkční, hlavně na mobilu:

![moje_vypujcky_mob](https://cloud.githubusercontent.com/assets/11600358/16091382/a6e3fed2-3333-11e6-860d-515e839c12aa.png)

Trochu se obávám, že čím víc údajů tam dáme, tím se to znepřehlední pro malý displej (a pořád tak nějak počítám se strategií mobile first).

Hodně by pomohlo, kdyby byla možnost vidět to s obálkami, ale mě docela stačí CO (název) a KDY (půjčeno do) a link (obálka) - hodilo by se ovšem samozřejmě více testerů.

**Comment by black23** [comment]
chceckboxy jsou jen u položek, které lze prolongovat = ne všude.

**Comment by PetraZabickova** [comment]
Abych to vysvětlila. Jakmile není knihovna zcela zapojená nebo je ještě nějaký problém v konfiguracích, tak v seznamu výpůjček, rezervací, apod. zobrazuje pouze ty informace, které získáváme přes NCIP/API. Ve chvíli, kdy konfiguraci knihovny doladíme, tak spárujeme informaci o publikaci se samotnou publikací zaindexovanou v portálu, a zobrazíme podrobnější informace, obálku a prolink.

Ukázka z MKP není ještě propojená.  Pokud knihovny nebudou plně zapojeny, tak v portálu v ostré verzy nebudou. Tudíž takto nehezky informace o svých výpůjčkách nezískají.

Otázku toho, zda informace nezobrazit nějakým  úspornějším způsobem např. tabulkou jsme zvažovali a přikláníme se k ní také. Pokud bude o ni zájem i od ostatních tak ji přidáme, bude nám to jen nějakou dobu trvat.

**Comment by paulusova** [comment]
Plně zapojená knihovna vypadá takto:
![image](https://cloud.githubusercontent.com/assets/14090956/16114018/638f344e-33bf-11e6-842d-025caf1ff05e.png)

**Comment by vojtisev** [comment]
@black23 

> chceckboxy jsou jen u položek, které lze prolongovat = ne všude.

to mi taky mohlo dojít, pardon.

**Comment by vojtisev** [comment]
@paulusova díky. Mě to takto pořád připadá funkční pro spuštění.

**Comment by HankaHornychova** [comment]
S přehledem výpůjček ve čtenářském kontě jsem spokojená. Obsahuje nejdůležitější údaje i obálku.
![cpk_vypujcky](https://cloud.githubusercontent.com/assets/15137682/16839745/fe970d6e-49d0-11e6-9831-d5757f1bec0d.png)

Jen - pokud se nepodaří výpůjčku prodloužit, není možné zjistit důvod neprodloužení.
Ale to je kosmetická záležitost.

Pokud jde o návrhy @black23:
1. Změnit formulaci u včas nevrácených výpůjček z "Půjčeno do:" na "Mělo být vráceno:"
Nechala bych současný stav. Po překročení lhůty se objeví varování a je jasné, že mělo být vráceno.
2. Sloupcový formát zobrazení je samozřejmě úspornější, na desktopu bych se k němu přikláněla.
Ale - na mobilu je současná verze hezká a dobře čitelná. Stačí jen rolovat směrem dolů, je dobře vidět celý název i termín vrácení. Po změně na sloupce již bude nutné manipulovat se zobrazením (buď otočením telefonu na šířku, nebo posouváním na displeji). -- domnívám se.
V tom případě bych nechala současnou podobu zobrazení výpůjček.

Pro spuštění do provozu jsou funkce čtenářského konta naprosto vyhovující.

**Comment by Stoklasovab** [comment]
Nejsem pro delší formulaci. Tabulka by byla fajn, ale je otázka, jak se bude tvářit na mobilu. Můžeme mít vzorek do 22.8., kdy budeme věc uzavírat?

**Comment by lenkamaixnerova** [comment]
Nechala bych současný stav.

**Comment by Stoklasovab** [comment]
Zachovat stávající stav.
