### ISSUE TITLE
Aktuální výpůjčky - "Došlo k chybě: No suitable backend driver found"

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#108]
![screenshot-beta knihovny cz 2016-05-19 17-18-52](https://cloud.githubusercontent.com/assets/11600358/15399068/79d0c0cc-1de6-11e6-8f56-e41fdae58960.png)

Narazil jsem na to při prvním přihlášení přes mojeID.

**Comment by PetraZabickova** [comment]
Jedná se o chybu, kterou opravíme. Uživatel přihlášený přes sociální sítě nebo instituce, které jsou plně zapojené do portálu, dostane informaci o tom, že služba není dostupná a návod, jak si může připojit další identitu nebo zaregistrovat se do nějaké knihovny.
