### ISSUE TITLE
Rezervace a objednávky: "Došlo k chybě: Cannot call method: CPK\ILS\Driver\MultiBackend::getMyHolds"

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#109]
![screenshot-beta knihovny cz 2016-05-19 17-25-01](https://cloud.githubusercontent.com/assets/11600358/15399144/cdd5d522-1de6-11e6-91f2-6d0bae865654.png)

**Comment by PetraZabickova** [comment]
Stejná situace jako issue 108. Budeme řešit.
