### ISSUE TITLE
Pořadí institucí v "Nalezeno v těchto institucích"

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#11]
Jak je určováno pro nepřihlášené uživatele?

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
V tuto chvíli chaoticky, v příští verzi bety bude již určováno Vahou (kvalitou) záznamu.

**Comment by PetraZabickova** [comment]
Pořadí institucí bude řešeno třemi možnými způsoby:
- vahou, v případě anonymního uživatele
- pokud anonymní uživatel použije filter pro jednu a více knihovnu, tak se tyto knihovny se umístí do popředí
- u přihlášeného uživatele budou v popředí ty knihovny, ve kterých bude registrován
