### ISSUE TITLE
Profil - Dummy - Profil se nepodařilo načíst

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#110]
![screenshot-beta knihovny cz 2016-05-19 17-28-00](https://cloud.githubusercontent.com/assets/11600358/15399231/20d457da-1de7-11e6-965c-9bc2edf5ce3b.png)

Při prvním přihlášení přes mojeID.

**Comment by PetraZabickova** [comment]
Stejný problém jako u issue 108. Budeme řešit.
