### ISSUE TITLE
mojeID - logout page

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#111]
![mojeid_cpk_logout_page](https://cloud.githubusercontent.com/assets/11600358/15399500/2de4edd0-1de8-11e6-9182-5d50ef76e7e2.png)

Logout Page by měla být upravená na straně IdP - nevím, zda v tomto případě jde o CZ.NIC, nebo CPK. Odhlašoval jsem se po přihlášení přes mojeID.

**Comment by HankaHornychova** [comment]
Potvrzuji stejnou podobu odhlašovací stránky, kterou uvádí @vojtisev . Přihlášení bylo provedeno přes identitu mojeID. Po výše uvedené stránce následovala ještě další:
![mojeid_2](https://cloud.githubusercontent.com/assets/15137682/16916898/9228f9f8-4cff-11e6-8c9b-5ea98005d886.png)

**Comment by PetraZabickova** [comment]
Chybová odhlašovací stránka je ve správě CESNETu. Komunikujeme to s nimi. Nejsme schopni ovlivnit, kdy bude opraveno.

**Comment by xmorave2** [comment]
Zdá se to vyřešené, může to někdo další potvrdit?
