### ISSUE TITLE
Ad předvybraný set “hezkých" záznamů

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#112]
Výborný nápad, díky za to. Bude se to průběžně aktualizovat? Ve výsledcích vyhledávání nějak vypadává kódování (v detailu záznamu je to OK):

![screenshot-beta knihovny cz 2016-05-19 17-39-37](https://cloud.githubusercontent.com/assets/11600358/15399674/e5ffecda-1de8-11e6-9704-f01e9e7b318c.png)

**Comment by PetraZabickova** [comment]
Děkujeme. Chceme tuto sadu rozhodně rozšiřovat. Nabídneme i způsob jakým by knihovny mohli záznamy do této sady přidávat. 

Kódování se pokusíme ošetřit, jedná se o problém, kdy anotaci krátíme  na určitý počet znaků a v daném případě, se nám rozpůlil jeden utf znak.
