### ISSUE TITLE
Přihlášení z výsledků vyhledávání

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#113]
Pokud se přihlásím během vyhledávání, jsem přesměrován přímo do "Můj účet/Výpůjčky" - nemám ale možnost, jak se dostat zpátky na výsledky vyhledávání. Pokud se tedy přihlašuji během vyhledávání proto, abych si udělal rezervaci, budu muset začít vyhledávat znovu. Není to škoda?

**Comment by PetraZabickova** [comment]
Děkujeme za upozornění. Víme o tom a ještě to upravíme. Přesně tohle je důvod, proč jsme přidali funkci notifikací. Po přihlášení z výsledků dotazů nebudeme uživatele přesměrovávat do jeho Výpůjček, ale zachováme ho na tom místě, kde byl. Pokud by měl ve svém účtu nějaké problémy o kterých by měl vědět, tak se o nich dozví z notifikací.
