### ISSUE TITLE
Výpůjčka - CTA

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#114]
Pořád mám docela problém s tím, že v detailu záznamu nemáme žádné pořádné tlačítko, které by pomohlo uživatelům provést akci. Pokud chceme v CPK poskytovat službu(y), a ne jen bohatý katalog záznamů, měli bychom mít jasnou vizi, co je pro CPK konverze. Je to výpůjčka? Rezervace? Exportovaný záznam? Citace?

Pokud jde o výpůjčky - pokud najdu dokument, který chci, musím rolovat dolů a hledat utopené tlačítko "Chci vypůjčit".

Příklad:

![detail_zaznamu](https://cloud.githubusercontent.com/assets/11600358/15400450/dce6efec-1deb-11e6-9d83-b3bb904767ed.png)

**VS**

![detail_zaznamu_2](https://cloud.githubusercontent.com/assets/11600358/15400497/066de73a-1dec-11e6-82da-840706d1b402.png)

**Comment by black23** [comment]
Souhlasím s Vojtou. Zatím jsme něřešíme příliš na "tah na branku". Nikde proaktivně nenabízíme registrace v knihnách, ani jejich návštěvu a to není dobře. Knihovny chtějí slyšet, proč mají mít zájem zapojit se do CPK, dejme jim důvod = konverze.
Po najetí nad tlačítko "To chci" by se mohla zobrazit provozní doby knihovny, neregistrovanému také podmínky registrace a její cenu, případně vzdálenost od akuální pozice. Ale k tomu potřebujeme data, které jsou ve statické části portálu. Navrhuji se tomuto tématu věnovat odděleně, ale intenzivně.

**Comment by vodomilka** [comment]
![cpk_04_vysledkyvyhledavani_autor](https://cloud.githubusercontent.com/assets/15191997/16111426/cf4f0194-33b2-11e6-93a3-94242b4c9746.png)

Souhlasím. Pro ukázku doplňuji, jak vypadal lednový návrh UX od Proof and Reason. Je ovšem otázka, zda uživatel potřebuje hned u prvního výpisu vidět oddělení, sbírky apod. u všech svazků, zda toto neukazovat až po rozbalení, že to uživatel vidět chce.

**Comment by Stoklasovab** [comment]
Mně se líbí tlačítko TO CHCI nebo CHCI TO. Podrobný výpis by se měl zobrazit až pak a jen v některých případech, kdy si to bude někdo chtít půjčit. U e-zdrojů bude chtít spíš plný text. A někde může mít obojí. Takže ještě rozbočka:
CHCI TO
- půjčit
- plný text

**Comment by vodomilka** [comment]
A nebyl o by možné to rozlišení CHCI TO půjčit/plný text nabídnout až v dalším kroku? Např. rozbalením možností, pokud jich je více?

**Comment by PetraZabickova** [comment]
My jsme původně chtěli realizovat tlačítko CHCI TO, ale ustoupili od toho řešení po konzultaci s firmou Direct People, kteří dělali uživatelská testování. Zásadní důvod proč k tomu došlo byl ten, že uživatele prý matou tlačítka, která nejsou konzistentní a pokaždé nabízí něco jiného. Doporučovali nám tehdy, že je mnohem lepší nabízet každou službu samostatně.

Většina knihovních systémů a OPACů je dělaná na principu objednávání konkrétní jednotky.  To je něco co nejsme schopni změnit. Každá konkrétní jednotky se může zásadní způsobem lišit od jiné (vícesvazková díla popsaná shora, periodika, jazykové učebnice skládající se s pracovního, studijního a učitelkého sešitu, ...).

Jsme přístupní diskusi a rádi budeme s Vámi hledat lepší řešení, který bude vyhovovat jak stávajícím tak novým uživatelům. Myslím si, že v tomto případě by bylo ale lepší osobní diskuse na příštím setkání ES.

Jen pro informaci, že na "tah na branku" úplně nevypouštíme :-). V tuto chvíli chystáme propojení mezi záznamy v portálu, adresářem knihoven. Chystáme "infoboxy" knihoven, kde necháme knihovnám možnost přidat vlastní individualizované texty a nápovědy. Chystáme úpravy v textacích a propagaci registrací ...

Rozhodně bychom ale ocenili, kdyby návrhy nových funkcí byly více konkrétnější.

**Comment by HankaHornychova** [comment]
Také by se mi líbilo nějaké návodné/nápadné tlačítko - možná bych volila něco méně expresivního - např. ZÍSKAT.
Ale naprosto rozumím Petře Žabičkové. Realizace tohoto návrhu není tak jednoduchá, jak se na první pohled zdá. Bylo by potřeba udělat hlubší analýzu.
Navrhuji - buď nechat současný stav a problém uzavřít, nebo problém nechat prozatím otevřený a (jak navrhuje Petra) probrat ho na schůzce ET.

**Comment by Stoklasovab** [comment]
Tlačítko pokládám za poměrně zásadní věc. Je to přiděleno k projednání, takže projednáme na schůzce ET - pravděpodobně v srpnu, kdy zřejmě bude třeba uzavřít i další věci před zveřejněním CPK.

**Comment by Stoklasovab** [comment]
Probereme 22.8. Je to hodně zásadní věc, prosím, napište názory v předstihu a dobře se na diskusi připravte.

**Comment by vojtisev** [comment]
Tlačítko, které navrhuji by mělo vést v podstatě k průvodci objednávkou (eshop) - ať už MVS, rezervace, registrace v knihovně nebo získání el. verze. Nemyslím, že vadí, když to bude na víc kliknutí, když ty kroky budou srozumitelné. Jde mi hlavně o to, že od uživatele vlastně v současné podobě portálu nic nechceme (mimo sekce Můj účet) - to by mohl být problém nejen z pohledu UX, ale také pro stanovení KPI.

**Comment by Stoklasovab** [comment]
Toto mi poslal J. Pokorný:
V roce 2017 planujeme na zaklade letosni analyzy zrealizovat (naprogramovat) system pro rizeni EDD a MVS, tedy nastupce VPK, bude mit nazev Ziskej. Bude integrovat v jednom systemu vsechny bezne dorucovaci sluzby, tedy EDD, MVS a repro.

**Comment by Stoklasovab** [comment]
Takze tlacitko Získat nebo Ziskej a dále uz bude uživatel pesmerovan na sluzbu Ziskej? Přechod by měl být "bezešvý" a uživatel by neměl změnu rozhraní moc zaregistrovat.

**Comment by black23** [comment]
nevím jestli tomu rozumím správně. Prolink na Získej bude řešit dodání z jiné knihovny, než z "mateřské" konkrétního uživatele. Představuji si, že pokud je možná výpůjčka v "jeho" lnihovně(nách) mělo by se to chovat tak, že si provede rezervaci. Toto je v plánu? Druhá věc je, že Získej bude někdy v průběhu roku 2017. Do té doby nebudeme tuto možnost nabízet vůbec nebo využijeme nějakého stávajícího řešení?

**Comment by Stoklasovab** [comment]
Řekneme si zítra. Honza Pokorný bude snad připojen z Prahy. Představovala jsem si to (možná naivně) jako řešení podobné tomu, co jsem kdysi viděla v Austrálii: systém prohledával spoustu knihoven a po stisknutí tlačítka CHCI TO nebo ZÍSKAT nabídl řadu možností s mateřskou knihovnou v čele.

**Comment by Stoklasovab** [comment]
Tlačítko TO CHCI - směrování na stávající nabídku, následně přihlášení, registrace, vyjasnění vazby na ZÍSKEJ

**Comment by zabak** [comment]
Budeme řešit v návaznosti na službu Získej

**Comment by xmorave2** [comment]
Bude implementováno v relativně blízké budoucnosti. Je to v koncepci rozvoje CPK.
