### ISSUE TITLE
Obohacování katalogů knihoven o záznamy elektronických zdrojů z linkserverů

### ISSUE THREAD

**Issue by PetraZabickova** [moravianlibrary/CPK#115]
Již nyní řada knihoven využívá exporty z SFX JIB obohacené službou MARCit k importu záznamů elektronických zdrojů do svých katalogů. Zmínit můžeme např. Národní knihovnu,  Moravskoslezkou vědeckou knihovnu v Ostravě nebo Vědeckou knihovnu v Olomouci. Předpokládáme, že jich je ale víc, ale nejsou všechny. Součástí tohoto procesu u nich ještě bývají různá opracování včetně obohacení o česká předmětová hesla, možné jsou i různé manuální úpravy.  

Mnohé knihovny ale záznamy elektronických zdrojů do svých katalogů nepřidávají. Abychom předešli zbytečným duplicitám, tak rozhodnutí o tom, zda v portálu každá knihovna zveřejní záznamy elektronických zdrojů na přímo ze svých obohacených katalogů nebo zda využijí naší nabídky, kdy export a obohacení zůstane na starosti CPK, necháme konfigurovatelně na ní.

Jsou proti tomuto řešení nějaké námitky?

**Comment by Stoklasovab** [comment]
Zdá se mi to rozumné.

**Comment by PavlinaDolezalova** [comment]
Určitě nechat na rozhodnutí konkrétní knihovny i s ohledem, že SFX JIB poskytuje MARCit záznamy jen z těch EIZ, které předplácí NK ČR, takže např. periodika v ProQuestu, nejsou v této službě zdarma vůbec zahrnuta.

**Comment by vojtisev** [comment]
Souhlasím, jenom aby platilo _"Abychom předešli zbytečným duplicitám"_, pak by to, myslím, mělo být obráceně - typicky nabízet export dat z CPK, jednotný pro všechny jako výchozí nastavení a na straně knihoven, které by potřebovaly data jinak, možnost úpravy na své straně. Je-li to možné. Jinak si myslím, že bez předchozího upozornění to při exportu nikdo promýšlet nebude, pošle prostě vše, co má a duplicity vzniknou ve stejném rozsahu.

**Comment by jrmeixner** [comment]
Návrh MZK je určitě rozumný, rozhodnutí kterou variantu zvolit bych nechal na knihovně. Důležitá je poznámka kolegyně Doležalové, že obohacené záznamy službou MARCit v SFX JIB, se týkají jen portfolia EIZ, předpláceného NK ČR (takže v případě KNAV by šlo obohatit asi 50% portfolia EIZ). Také je potřeba brát v úvahu, že ostatní lokální instalace SFX (kromě JIB) v českých knihovnách nejsou automaticky s MARCit licencí (nebyla součástí základní instalace ale jako služba navíc za příplatek).

**Comment by black23** [comment]
Nejek kvůli diplicitám, ale i celistvosti například zmíněných předmětových hesel by obohacování mělo probíhat na jednom místě, tedy na straně CPK. Zprování na knihovně by mělo zůstat jen případě nějakého skutečně specifického zdroje.

**Comment by lenkamaixnerova** [comment]
Souhlasím s návrhem MZK.

**Comment by jiripavlik88** [comment]
CPK bude pouzivat take export SFX JIB, je to tak, Petro? Knihovny se tedy maji rozhodnout, zda do indexu CPK zaznamy e-casopisu pujdou pres jejich katalog nebo primo. Souhlasi?

**Comment by KarolinaKostalova** [comment]
Souhlasím s návrhem MZK.

**Comment by Stoklasovab** [comment]
Realizovat návrh MZK.

**Comment by zabak** [comment]
Řešení bude modifikováno v návaznosti na implementaci CI.

**Comment by PetraZabickova** [comment]
Na vyžádání si může každá knihovna zvolit, zda chce exporty přidávat i do svých zdrojů lokálního indexu.
