### ISSUE TITLE
Realizace evýpůjček přes eReading (alternativy řešení)

### ISSUE THREAD

**Issue by PetraZabickova** [moravianlibrary/CPK#116]
Máme dilema ohledně toho, jak zapojit eVýpůjčky realizované přes eReading.

Tyto zakládající knihovny umožnují eVýpůjčky přes eReading:

Jihočeská vědecká knihovna v Českých Budějovicích
Krajská knihovna Františka Bartoše ve Zlíně
Krajská knihovna Vysočiny
Krajská vědecká knihovna v Liberci
Městská knihovna Česká Třebová
Městská knihovna Kutná Hora
Městská knihovna Tábor
Severočeská vědecká knihovna v Ústí nad Labem
Středočeská vědecká knihovna v Kladně

Každá z těchto knihoven v tuto chvíli nabízí trochu jinou sadu knih z té celkové nabídky, kterou eReading nabízí. Je to dáno tím, jakým způsobem odkazy do svých katalogů přidávají.
- někdo to má jako samostatný import
- někdo přidává pouze link k již existujícím záznamů
- ne každému se podaří deduplikace absolutně správně
- někdo nabízí jen to, co nemá ve svém katalogu
- někdo nabízí jen to, co má ve svém katalogu

Co s tím můžeme dělat v CPK:
### Varianta1

Můžeme od eReading stáhnout celou sadu záznamů určených eVýpůjčce a:
-  obohatit o linky stávající záznamy nebo
-  přidat jako nový záznam, který můžu nebo nemusím deduplikovat vůči papírové verzi

Tahle varianta je nejjednodušší z hlediska implementace. Ten kdo nabízí eReading, tak přes CPK nabízí celou nabídku toho, co je na eReading k dispozici.

To se ale asi nemusí líbit těm knihovnám, protože oni v  jejich katalogu mohou nabízet tu nabídku z nějakého důvodu neúplně. Ten důvod může být záměrný nebo jen nepovedená deduplikace.
### Varianta 2

Každá knihovna nám sama dodá záznamy, které nabízí přes eReading nebo doplní své stávající záznamy o nějaký jednotný předem dohodnutý příznak, kterým poznáme, že tento záznam je určen pro e-výpůjčku přes eReading. Ty knihovny to v tuto chvíli neposílají a těžko říct, jestli to všechny budou umět.
### Varianta 3

Kombinace předchozích dvou alternativ, některé knihovny si zvolí volbu vše a jiné budou vybírat. Nejpracnější a nejméně přehledné. Snažila bych se této variantě vyhnout.

Není možné provádět deduplikaci pouze na základě ISBN, jak to některé knihovny dělají. Část ISBN použitých u záznamů v eReading je vadných (ISBN $z, shoda není 100% může dojít k chybám propojení)

Budu ráda, za nápady a reakce, jak problematiku řešit.

**Comment by black23** [comment]
Za MKCT se přikláním k variantě 1. My se snažíme mít vše, co eReaging nabízí. Vzhledem ke kvalitě jejich metadat se to ne 100 % daří. Takže máme jen tituly, které dá nějak spojit se záznamy z ČNB.  Tzn., že varianta 1 jde "naším směrem". 
Druhou částí otázky se konsolidace obou variant dodání (papír, ebook) do jednoho záznamu. Jsem za spojení do jednoho. Nicméně mělo by dojít na dohodu napříč knihovnami. Nechápu například, proč má někdo v nabídce jen to, co nemá papírově nebo naopak co má také papírově. Může za tím být obva s finanční náročnosti provozu eVýpůjček. Nám se nabízení co nejširší nabídky zatím zdá jako nejlepší.

**Comment by vojtisev** [comment]
Týká se to pouze titulů eReading, nebo také dalších e-výpůjček ze seznamu těch v ČR dostupných:

https://sites.google.com/site/eknihyproknihovny/home

Ptám se proto, zda hledat nějaké obecné řešení, nebo je to jenom tento konkrétní příklad.

**Comment by black23** [comment]
Myslím, že je třeba hledat obecné řešení. IMHO například FlexiBooks používají technicky velmi podobné řešení jako eR.

**Comment by vojtisev** [comment]
@black23 já bych byl se slučováním záznamů papírových a elektronických knih opatrný. Ono je to vlastně z podstaty špatně - každý titul by měl být přeci jiný (ISBN). V MKP toto rozlišujeme např. tím, že agregujeme-li do katalogu e-knihu, která vyšla opravdu elektronicky (podle ISBN), má samostatný záznam. Pokud jde o digitální obraz tištěné verze (typicky PDF pro tiskárnu vystavené někde na webu vydavatele), pak pouze přidáváme k záznamu tištěného titulu odkaz na soubor na webu vydavatele.

**Comment by black23** [comment]
@vojtisev To je fakt. Pokud obsahově stejný dokument existuje jako ebook ke stažení nebo vypůjčení, tak by se pak mohl zobrazit v detailu, pod linkem e-kniha. Ale pak by měl mít záznam svůj. 
Takže opravuji svoji původní reakci: spojovat záznamy jen v případě, že jde o stejné ISBN/ISSN. Pokud bude technicky možné u papírové verze dodat odkaz na elektronickou verzi.

**Comment by black23** [comment]
Otevrrel jsem to tema i s kolegou Moravcem a nakonec jsme se shodli, ze do budoucna je jedinym resenim vytvaret titulove zaznamy a pod ne sdruzit vsechny verze dila. Zkousel vyvojovy tym neco takoveho a pripadne s jakym vysledkem?

**Comment by PetraZabickova** [comment]
Pokud na nás v budoucnu přijdou požavky na realizaci dalších způsobů e-výpůjček, tak samozřejmě máme zájem o hledání univerzálního řešení.

**Comment by PetraZabickova** [comment]
Titulové záznamy jsou i pro nás cíl, jehož realizace je ale v tuto chvíli neprioritní. Mezi hlavní problémy realizace deduplikace na této úrovni je premisa toho, že CPK zvládne zpracovat všechny záznamy bez ohledu na rozsah a kvalitu. Další debatu na toto téma bych ráda odložila do doby, kdy nám nebudou hořet jiné termíny a úkoly.

**Comment by black23** [comment]
ve svetle odpovedi @PetraZabickova bych tedy navrhoval cistou variantu 1 a zaznamy pairove a elektronicke verze nespojovat. Resme to, az budou titulove zaznamy.
Pokud myslim na ciloveho uzivatele, tak by myslim ocenil, kdyby alespon v related byla nabize pripadne elektronicka verze papiroveho dokumentu nebo eVypujcka, pokud je k dispozici. Protoze to podporuje nase snahy o konverze navstev na provedene sluzby. Stazeni ebooku nebo eVypujcka je tou nejdostupnejsi primo z prostredi internetu. Proto by mela byt nabizena je-li to mozne.

**Comment by jiripavlik88** [comment]
Knihovny maji zaznamy e-knih eReading.cz a Flexibooks v katalogu. Zatim mam za to, ze zadna z variant neni potreba. Nebo mas, Petro, ambici realizovat vypujcky eReading.cz a Flexibooks v CPK volanim eReading.cz, Flexibooks API?

**Comment by black23** [comment]
@jiripavlik88 Však o to právě jde, že je mají v katalogu. Ale pokaždé v jiném rozsahu, Vlastně podle toho, jak jejich systém umí/neumí deduplikovat. Jinak nevidím důvod, proč by výpůjčka nemohla proběhnot na straně CPK, pokud bude zajištěna bezpečnost a dojte k ověření oprávněnost požadavku čtenáře (má platnou registraci, nemá vyčerpaný limit výpůjček atp.). Ale otázka se týkala jen otázek jak a kde vytvářet set titulů k vypůjčení, protože v tom panují značné rozdíly.

**Comment by Stoklasovab** [comment]
Teď: Varianta 1. Neslučovat záznamy papírových a elektronických dokumentů.
Záznam na titul - plán pro vzdálenou budoucnost.

**Comment by xmorave2** [comment]
Záznamy Palmknih jsou indexované. Budou přidány odkazy do jednotlivých knihoven pro umožnění půjčování.
