### ISSUE TITLE
Faseta autor

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#117]
Je možné sjednotit autora z pole 100 s autorem z pole 700 i v případě, že pole 700 obsahuje podpole $t a pak je dle katalogizační praxe nutné dávat za $d tečku? Ukázka na Karlu Čapkovi.
![cpk_faseta_autor](https://cloud.githubusercontent.com/assets/15088603/15469073/27fd1bec-20e8-11e6-882e-a931484bfde1.jpg)

Lze nastavit fasetu autor i alternativně podle abecedy (nyní defaultně podle četnosti výskytu ve výsledcích)? Ideálně, kdyby si mohl uživatel přepínat podle obou možností četnost x abeceda.

**Comment by PetraZabickova** [comment]
Děkujeme za upozornění. 

S tečkama je trochu problém. Může se jednat o zkratku nebo iniciálu. Některé záznamy mají mnohdy tečky duplicitně nebo naopak tečky chybí, nedá se na to úplně spoléhat.

V tomto případě to můžeme zkusit, ale oprava nebude úplně 100% a je možné, že v některých případech tečku odstraníme i když bychom neměly (převážně v případě nestandartně použitých zkratek v podpoli c)

**Comment by PetraZabickova** [comment]
Ještě jsem porovnávala řešení konkurenčních portálů, kde tuhle problematiku řeší trochu jinak a to tak, že fasetu autor tvoří pouze z podpole a.

**Comment by PavlinaDolezalova** [comment]
$d je důležité pro rozlišení autorů stejného křestního jména, to bych ve fasetě nechala. V tomto případě by se týkalo odstranění tečky právě jen v $d.
