### ISSUE TITLE
Fasety - logika uvnitř a mezi nimi

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#118]
Možnost v rámci jedné fasety spojovat termíny OR (nyní nelze). Kombinovat fasety navzájem pomocí AND - to je v CPK již nyní.
Varianta Národní technické knihovny - ubírání (NOT) z výsledků https://vufind.techlib.cz/. Varianta Krajské knihovny F. Bartoše ve Zlíně - zaškrtávání http://katalog.kfbz.cz/.
![cpk_fasety_logika](https://cloud.githubusercontent.com/assets/15088603/15470449/1a732bd4-20f1-11e6-9543-3f06198294f7.jpg)

Též viz https://docs.google.com/document/d/1x1Chl5wm9HqhmtHPlLRjxsBrhEgnlcdSB0j1yI5hDCU/edit#

**Comment by PetraZabickova** [comment]
Děkujeme za Vaši připomínku. Jaké je Vaše doporučení? V příkladu uvádíte 2 možná řešení a v odkazovaném dokumentu dokonce 3. Které z nich je to, co by portál měl umět?

Přiznáme se, že to, že fasety v NTK umožňují NOT je pro nás novinka, přestože jsme s jejich vufindem dost obeznámeni.  Dodnes jsme mysleli, že x u číslovky fasety je jen grafický prvek, který znázorňuje slovo krát. Navíc nám připadá škoda, že toto řešení vůbec nereflektuje logiku OR.

Naše aktuální nastavení je nyní následující. Mezi fasety navzájem AND. Uvnitř faset v některých případech OR a v některých případech AND. Ty fasety, které obsahují čtverečky s možností zatržítka jsou OR, ty které čtvereček neobsahují jsou AND. Naše tendence je spíše použít pro všechny faset  uvnitř logiku OR, i když jsme ke změně ještě všude úplně nepřistoupili. 

Nejsme si úplně jistí tím, že pokud fasety budou umožňovat všechny kombinace, tak budou uživateli při použití pochopitelné. Také by se mohlo stát, že z důvodů nedostatečné rychlosti odezvy, bychom museli v některých případech použít tlačítko Aktualizovat výsledky namísto okamžitého přepočítání výsledků.

Jediná věc, kterou v tuto chvíli ještě upravujeme je logika fasety Typ výpůjčky, která nyní nereflektuje lokální záznamy knihoven, ale sloučené a bude v příštím releasu upravena. 

Možných řešení je hodně a některé z navhovaných úprav jsou pro realizaci složitější než jiná.  Jaké je  rozhodnutí Expertní skupiny?

**Comment by PavlinaDolezalova** [comment]
OK, přehlédla jsem, že u faset: Obor, Jazyk a Země vydání je možnost OR zaškrtnutím. Byla bych pro, aby OR bylo u všech faset (tedy vyjma Roku vydání, tam nynější nastavení vyhovuje) a pak by při takovém množství bylo asi vhodnější tlačítko "Aktualizovat" než přepočítávání výsledků po každém zakliknutí. Kdyby u čtverečků byla nápověda, že je to součet (v NTK "vynechat"), tak by si snad uživatelé byli schopni poradit. Expertní skupina bude na tohle téma ještě zřejmě jednat, už jsme to kdysi nakousli.

**Comment by vojtisev** [comment]
Myslím, že na toto máme Pokročilé vyhledávání, proč to komplikovat? Fasety by mi měly pomoci přesně třídit výsledky v reálném čase - pokud bych je měl dlouho studovat, abych pochopil, jak fungují a ručně aktualizovat, tak to IMHO rozhodně není dobře. Pokud si dobře vzpomínám, na posledním (prvním) setkání ET jsme to po delší diskuzi shrnuli tak, že bychom to nastavení faset měli odpilotovat, sledovat metriky, popř. uživatelsky otestovat a případně upravit. Současné nastavení mi připadá OK.

**Comment by PavlinaDolezalova** [comment]
Vzhledem k tomu, že již nyní je OR v některých fasetách formou zaškrtnutí více termínu přítomné, tak v rámci zjednodušení pochopení CPK bych byla pro, aby tato možnost byla u všech faset.

**Comment by lenkamaixnerova** [comment]
Já bych to také příliš nekomplikovala a nechala bych klidně současné nastavení.

**Comment by jrmeixner** [comment]
Možnost kombinace termínů pomocí OR pouze v rámci faset Obor, Jazyk, Země vydání mi přijde dostačující. S implementací komerčního centrálního indexu v CPK se termíny ve fasetách ještě znásobí. CI nabízí specifickou fasetu "Poskytovatel/Zdroj obsahu" - četnost výsledných záznamů v jednotlivých zdrojových kolekcích/databázích indexu. U ní také bude otázka zda umožnit filtrování výsledků pomocí OR - zaškrtnutím vybraných kolekcí - např. pro citační báze SCI OR SSCI OR Scopus.

**Comment by PavlinaDolezalova** [comment]
A co alespoň přidat OR do fasety autor a předmět? Tím by bylo možné pospojovat výskyty jména/korporace s autoritní i neautoritní podobou.

**Comment by black23** [comment]
Souhlasím s @vojtisev. Jedním z výsledků uživatelské testování bylo, že fasety téměř nikdo nevyužívá. Potvrdilo se to i ve statistikách, které poslalo několik knihoven na vyžádání ET. Fasety smysl mají, ale musí být pochopitlně strukturované a jejich použití konzistentní. Také si myslím, že by bylo nejlepší nechat je ve stávající podobě a ještě se k tomuto tématu vrátit později, až budeme mít nějakou zpětnou vazbu od uživatelů a hlavně data o používání. Jak píše @jrmeixner, věci zkomplikuje idalší zapojování zdrojů a bude nutné se tomu opravdu věnovat opakovaně.

**Comment by vodomilka** [comment]
Ještě uživatelská poznámka k rozhraní - pokud budou fasety fungovat jako OR, pak by neměly vypadat jako zatrhávací pole (na což jsou uživatelé zvyklí, když mají možnost zatrhnout více možností). Každopádně by bylo vhodné, aby fasety fungovaly a tedy i vypadaly stejně, aby k tomu uživatel nepotřeboval nápovědu a po zatrhnutí některé z faset mu bylo jasné, co se touto volbou stane.

Ještě bych zvážila také zobrazení u položky Instituce - v součansém stavu to vypadá, že není defaultně zatrženo nic, ačkoli se vyhledává ve všem. Také by bylo vhodné nabídnout jako první Katalogy knihoven a nikoli Ostatní zdroje.

**Comment by Stoklasovab** [comment]
Ponechat stávající stav - tj, OR tam, kde je možnost zatržení (křížky), jinak AND.
