### ISSUE TITLE
Faseta - Typ dokumentu - Noviny a časopisy

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#119]
"Noviny a časopisy" v Typu dokumentu obsahují i nepravá periodika - sborníky pokud mají souborný záznam tak je v LDR/07 "s". Nepřidáte do označení tohoto typu "Noviny, časopisy, sborníky"?

**Comment by PetraZabickova** [comment]
Souhlasím s tím, že "knihovnicky" by bylo označení Noviny, časopisy a sborníky přesnější - respektive bychom mohli ještě použít alternativy "Seriály nebo Periodika", o kterých ale víme, že jsou uživatelsky docela nesrozumitelné. 

S ohledem na uživatelské zaměření portálu bych ráda zvážila, jestli terminologická přesnost převáží fakt, že se nám ta hodnota ve fasetě rozleze na dva řádky. Prosím o vyjádření.

**Comment by PavlinaDolezalova** [comment]
Ano je to dlouhý název, bohužel ale málo koho napadne, že sborníky jsou mezi novinami a bude je hledat mezi knihami, kde v lepším případě narazí na jednotlivě zpracované svazky. Zkusím tento návrh předložit naší PS.

**Comment by black23** [comment]
Jsem za "Noviny a časopisy". Je to "jen" zpřesňující faseta. Nejen uživatelské testévání ukazuje, že nejčastěji uživatelé hledají přes název, autora nebo tématickou oblast. Sborník tak pravděpodobně najdou bez ohledu na to, pod kterou fasetou se schovává. Ale určitě by pomohlo, kdyby obecně celý systém měl integovanou kontexotvou nápovědu, kde bylo možné takové nuance popsat.

**Comment by vojtisev** [comment]
Souhlasím s @black23

**Comment by lenkamaixnerova** [comment]
Taky souhlasím s @black23

**Comment by black23** [comment]
Uzavřeme to nebo ještě budeme debatovat?

**Comment by HankaHornychova** [comment]
Souhlasím s @black23.
Debata už asi žádná nebude :-).

**Comment by PavlinaDolezalova** [comment]
OK, tak tedy "Noviny a časopisy" a někdy možná do kontextové nápovědy i ty "sborníky".

**Comment by lenkamaixnerova** [comment]
Souhlasím s @black23

**Comment by Stoklasovab** [comment]
Souhlas s "Noviny a časopisy" + do nápovědy sborníky
