### ISSUE TITLE
"Poslat e–mailem" umožnit i pro nepřihlášené

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#12]
navrhuje Mgr. Pavlína Doležalová

**Comment by vojtisev** [comment]
Toto IMHO řeší návrh #14 (přidávání do oblíbených pro nepřihlášené).

**Comment by vojtisev** [comment]
Navrhoval bych textaci ve formuláři pro posílání e-mailu změnit u "Do" na "Komu".
![e-mail_-_formular](https://cloud.githubusercontent.com/assets/11600358/10073464/6464380a-62c9-11e5-9c9e-0f7fb806a707.png)
