### ISSUE TITLE
CPK v MSIE 11

### ISSUE THREAD

**Issue by KarolinaKostalova** [moravianlibrary/CPK#121]
Po otevření http://beta.knihovny.cz v MSIE 11 (11.06.9600.18314, Win 7) celé okno exploreru, ve kterém jsou beta.knihovny.cz otevřené, přestane reagovat a "vytuhne" a to včetně jednotlivé záložek otevřených v rámci aktuálně použitého okna prohlížeče. Zdá se, že to nezávisí na tom, zda potvrdím nebo nepotvrdím sledování polohy. Ve FF 46.0.1  k tomu nedošlo. Stalo se mi to s verzí Čenda a teď i s Jelenem.

**Comment by vojtisev** [comment]
V Microsoft Edge 25.10586.0.0 CPK běhá v pořádku.

**Comment by Stoklasovab** [comment]
Mám stejný problém jako Karolína, pouštím přes FF.

**Comment by vodomilka** [comment]
Na Win 7 Professional v MSIE 11 mám stejný problém. Ani nešlo skrolovat po stránce, a už samotná HP se načítá mnohem déle než ve FF.

**Comment by black23** [comment]
Jelen: OS X: FF 47.0 = OK Safari 9.1.1 = OK, mobilní zařízení otestuji následně.

**Comment by PetraZabickova** [comment]
Budeme se snažit o nápravu.

**Comment by Stoklasovab** [comment]
Problém je, že pokud má někdo defaultně nastaven MSIE a jde na betu přes nějaký odkaz, vytuhne mu to také a je nutno ho shodit přes správce úloh :-(

**Comment by black23** [comment]
@Stoklasovab Pak je problém primárně v MSIE, nikoli CPK :-)

**Comment by Stoklasovab** [comment]
To já vím. Také vím (protože mi to kdysi někdo poradil), že se to vyřeší přepnutím prohlížeče. Ale je spousta lidí, kteří to nevědí a budou si myslet, že nefunguje CPK :-(

**Comment by vojtisev** [comment]
@Stoklasovab @black23 určitě by bylo vhodné přidat informaci typu "prohlášení o přístupnosti" - web je vytvořen podle standardů XY a optimalizován pro prohlížeče 1 2 3 ve verzích abc. Myslím, že není rozumné snažit se kompatibilitu napříč, problém je, že zrovna MSIE (bohužel) pořád má ještě trochu relevantní podíl na trhu, viz např. http://www.w3schools.com/browsers/browsers_stats.asp aj.

**Comment by Stoklasovab** [comment]
Ta statistika je zajímavá. Když jsme nedávno aktualizovali naše psí stránky http://www.zlesnizahrady.cz , uvažovali jsme, kterými prohlížeči se zabývat a zjistili jsme ze statistik, že přes MSIE k nám chodí skoro polovina návštěv...

**Comment by PavlinaDolezalova** [comment]
Nyní, myslím, že je to lepší. Ve Win 7 a IE 11 již CPK podstatně více bez problémů. Ano je mezi námi spousta konzerv s MS a dokonce i IE staršími, než mám já, jak uvádí naši čtenáři, zejména poté, co jsme si vylepšili webový alephovský katalog a narazili jsme.

**Comment by black23** [comment]
Na některých webech se svého času využovalo takové okno,které vyskočilo pokud uživatel měl starou verzi IE. A nabídl se mu mu přechod na jiný prohlížeč nebo omezené fungování webu. Z technického hlediska je těžké zachovat všechny funkce v 10 let starém prohlížeči. Na nás je to uživateli říci pochopitelně a nabídnout mu možnosti.

**Comment by PavlinaDolezalova** [comment]
V srpnu jsem psala, že v IE 11 je to s CPK už lepší, sice celé CPK nezamrzá a není nutné přes Správce úloh vypínat aplikaci IE, ale pokročilé vyhledávání jaksi nefunguje - kolečko se marně točí a k aktualizaci výsledků nedochází, nezobrazí se ani předhledané výsledky, které mají být použitím pokročilého vyhledávání "aktualizované" (jak uvádí velké tlačítko vpravo).
