### ISSUE TITLE
Časová osa

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#122]
Vyhledávací faseta funguje, ale popup okno ne:

![screenshot-beta knihovny cz 2016-05-25 16-12-31](https://cloud.githubusercontent.com/assets/11600358/15543119/e68d1498-2293-11e6-8254-ecedaa352834.png)

(Chrome Verze 50.0.2661.102 m)

**Comment by black23** [comment]
Stejné i ve FF
