### ISSUE TITLE
Žádost o svolení prozrazení polohy

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/CPK#123]
Žádost o svolení prozrazení polohy se (ve Firefoxu - jinde jsem netestoval) zobrazuje pri prichodu na beta.knihovny.cz, pri zobrazeni vysledku dotazu, pri vstupu do detailu... Slo by to povolit jen jednou a zapamatovat? Omlouvam se, pokud je jiz reseno jinde.

**Comment by PetraZabickova** [comment]
Již opraveno.
