### ISSUE TITLE
Přihlašování skrolování a překlepy

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/CPK#125]
Přihlašování se objeví jako shadow box, ale skrolování v institucích je možné jen postraním skrolováním okna celého firefoxu, nebylo by možné přidat skrolování na stranu shadow boxu, tím spíše, když tam je i křížek pro sbalení části boxu?

**Comment by vodomilka** [comment]
Nejde o prioritní záležitost, ale našla jsem pár překlepů v názvech univerzit - nebo jen název zkratkou či v angličtině, lze opravit následující?:

Univerzita Karlova v Praze
Vysoká škola chemicko-technologická v Praze
Masarykova univerzita
Ostravská univerzita v Ostravě

**Comment by paulusova** [comment]
Názvy univerzit opravíme.
