### ISSUE TITLE
Našeptávač

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/CPK#126]
Mam problem s naseptavacem: pusobi na me dojmem uzavrenosti - uplnosti - neni z nej nijak zrejme, ze hodnot je vlastne MNOHEM vice, prestoze se nabizi jen malinko - neznaly muze mit dojem, ze shod opravdu vice neni. Jeho strukturovana podoba s ohledem na vyse recene mi neprinasi velky benefit. Kdyz prejedu mysi pres rozbalene nabidky, "chytne se" nejaky onHover a i kdyz z toho sektoru "odjedu", zustane zvyraznena jedna z moznosti. Ja ji nechci, ale ona zustava jakoby vybrana a ja se obavam, ze bude pri kliku na Vyhledat pouzita a muj vysledek dotazu omezen. Mel bych radeji nestrukturovany pomichany naseptavac s moznosti rolovani a mozna i s preferenci shody na zacatku retezce (tzn. pri zadavani "hrůza" bych tam nechtel mit vysoko "Tichá hrůza"). Anebo zadny...
![naseptavac](https://cloud.githubusercontent.com/assets/16186956/15860678/52f79abe-2cca-11e6-9971-f1281ab175aa.jpg)

**Comment by black23** [comment]
Tohle se resilo uz davno. A ET to takhle odhlasoval. Souhlasim s tim, ze tam mohla byt nejaka zjemnujici formulace ve smysl "Možná hledáte..." nebo neco takoveho. Nicmene aktualne ve Vindaloo
 mi naseptavac nefunguje vubec. Takze nelze obeveri "onhover" chovani.

**Comment by HankaHornychova** [comment]
Potvrzuji popsané chování našeptávače (viz jankanka) a souhlasím s výhradami.

Shrneme-li, kde všude už se téma našeptávače objevovalo....
Téma se diskutovalo na: https://github.com/moravianlibrary/CPK/issues/19
Bylo zmíněno v dokumentu: https://docs.google.com/document/d/1RCh74Rvq0spOcS-UxvSi1FVUrlLPvViDuXD8N268mpA/edit
Je součástí mailové komunikace ET.
Pozn.: Zápis z jednání ET (podle mého názoru) nehovoří o hlasování kolem našeptávače.

Nicméně - navrhuji, abychom toto téma uzavřeli, nechali současnou podobu našeptávače a počkali
na názory uživatelů. Pokud od nich vzejdou nějaké výhrady, můžeme se k tématu vrátit.

**Comment by PetraZabickova** [comment]
Našeptávač nastavíme aby se ignorovala malá a velká písmena v dotazu. 
Přidáme zjemňující formulaci a počkáme na názory uživatelů.

**Comment by PetraZabickova** [comment]
Bylo zjemněno.
