### ISSUE TITLE
Chování "Podobné" v případě, že jsem přihlášený 

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#127]
Modul Podobné i přihlášenému ukazuje i dokumenty, které nemají ve fondu jeho knihovny. Půjde s tim něco udělat? Je to dost matoucí.

**Comment by PetraZabickova** [comment]
Pokusíme se vyřešit. V tuto chvíli nejsme schopni odhadnou nakolik budeme schopni realizovat.

**Comment by PetraZabickova** [comment]
Podobné ukazuje dokumenty ze stejné knihovny jako je ta, která se zrovna zobrazuje. Pokud je uživatel příhlášený, tak se mu zobrazuje dokument jeho knihovny a tím pádem i podobné jsou z jeho knihovny.
