### ISSUE TITLE
Nový VuFind 3: fasety

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#129]
Řešili jsme tu intenzivně fasety a jejich využití. Nedávno vyšel VuFind 3 a ten nabízí nové rozšířené možnosti v oblasti faset.
Lze je dorozbalovat (více) a dlouhé seznamy zobrazilt v ligtboxu.
![screenshot at cvn 17 15-56-34](https://cloud.githubusercontent.com/assets/5516936/16152902/3d5acfbe-34a4-11e6-948f-4e8f536ac49a.png)
V lightboxu je možné měnit parametr seřazení. Buď podle výskytu nebo podle abecedy.
![screenshot at cvn 17 15-56-22](https://cloud.githubusercontent.com/assets/5516936/16152903/3d5b33dc-34a4-11e6-953a-b71a7dd69f1a.png)
![screenshot at cvn 17 15-56-03](https://cloud.githubusercontent.com/assets/5516936/16152904/3d5cae74-34a4-11e6-9489-39c905ad4ae6.png)
Takže do budoucna máme k dispozici i tyto možnosti, pokud to vyhodnotíme jako potřebné.

**Comment by Stoklasovab** [comment]
Probereme 22.8. v Brně - prosím v předstihu o názory.

**Comment by vojtisev** [comment]
Osobně bych se držel spíše toho, že méně je více - nabízel bych uživatelům méně možností, ale srozumitelně. Takhle na první pohled mě ta spousta možností trochu vyděsí.

**Comment by PavlinaDolezalova** [comment]
Parametry řazení jsou zajímavé, třeba autoři abecedně... by ušetřili práci, viz https://github.com/moravianlibrary/CPK/issues/117.

**Comment by black23** [comment]
Je to zajímavé zvláště na "dlouhé" fasety. Vnímám to ne jako další možnost, ale rozšíření stávajících.

**Comment by vodomilka** [comment]
Na první pohled to nevypadá jednoduše. Fasety mají sloužit jako pomoc pro zúžení dotazu a ne jako náhrada pokročilého vyhledávání. O využití rozšířených faset bych uvažovala až budeme mít k dispozici zkušenosti s tím, jak uživatelé portál používají. Bude možné z analytiky návštěvnosti CPK vytáhnout také zda uživatelé používají fasety (a případně jaké?)?

**Comment by black23** [comment]
@vodomilka Myslím, že screeny nedostatečně ilustrují momenty, kdy se toto zobrazení faset dá využít. Typycky je to tam, kde je položek v jednom modulu faset mnoho položek, například Předmět. Nyní je tam napevno X položek. Nově řešení při kliku na "Více" otevře ligtbox, kde lze zobrazit obsáhlejší seznam. Ale jinak to opravdu funguje k zúžení dotazu. Navíc pokud si pamatuji, tak se počet, respektive jeho omezování, ve fasetech docela řešilo. 
Každopádně souhlasím s tím, že tato věc musí být revidována až po nějakém čase veřejného provozu. Ze statistik získáme spoustu užitečných informací o tom, jak a co lidé opravdu využívají. Piwik, který CPK na statistiky využívá by měl zvládat i sledování faset. My v našem katalogu tyhle věci sledujeme a jednou začas přehazujeme například pořadí modulů faset nebo zde zmiňovaný počet.

**Comment by xmorave2** [comment]
Bude řešeno nad VuFind 6+
