### ISSUE TITLE
Nový VuFind 3: rozbalení detailu záznamu

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#130]
FYI: Další zajímavou možností nového VF je zobrazení detailu v accordion. K detailu se dostanete přímo z výsledku hlání. Není tedy nutné načítat novou stránku s detailem. Funkce je poměrně dobře parametrizovaná a její chování může být tedy individuální, podle potřeb konrétního rozhraní nebo cílové skupiny uživatelů.
![screenshot at cvn 17 16-06-19](https://cloud.githubusercontent.com/assets/5516936/16153178/83e53626-34a5-11e6-8c96-4f56de1ab149.png)

![screenshot at cvn 17 16-00-14](https://cloud.githubusercontent.com/assets/5516936/16152981/99f8da4a-34a4-11e6-9f1b-72f00bbf0e5d.png)

**Comment by PetraZabickova** [comment]
Děkujeme za návrh. Jedná se poměrně o velký zásah do rozhraní. Nebude realizováno v letošním roce. Možnost nasazení v budoucnosti je potřeba konzultovat v širší skupině a odborníky na UX rozhraní.

**Comment by Stoklasovab** [comment]
Pokud je parametrizovtelné podle skupiny uživatelů, bylo by to fajn. Probereme 22.8. v Brně a když tak zařadíme do plánu pro přští rok.

**Comment by xmorave2** [comment]
Nebude implementováno.
