### ISSUE TITLE
MVS: Vytváření a rušení rezervací na titul

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#131]
Stálo by za debatu, jak (až) budeme řešit odjednávání MVS. Teď CPK umožňuje rezervace jen na jednotky, ale pro administraci MVS by bylo vhodnější mít možnost vytvářet i obecnější požadavky na titul. NCIP vytvořit rezervaci na titul umí, ale nemá možnost ji rušit. Umožníme tedy případně rezervovat tituly knihovnám kvůli MVS nebo to případně rozšíříme i na běžné uživatele. My jsme původně v knihovně nabízeli spíše rezervace na jednotku, ale časem jsme od toho odstoupili, protože to výrazně zpomaluje cirkuční proces. Protože se velmi často stává, že konkrétní kus volný není, ale jiné ano. Nebo MVS povolíme jen na volné jetnotky/tituly? Vnímám to jako důležitou věc, která ovlivní hodně věcí, měli bychom tomu věnovat odpovídající pozornost.

**Comment by vojtisev** [comment]
Rezervace na titul v MKP umožňuje přesně z důvodu, o kterém píšeš. Pro nás to tedy určitě dává smysl.

**Comment by black23** [comment]
Takže, jak se k tomu postavíme? :-)

**Comment by PetraZabickova** [comment]
Objednávání MVS bude realizováno prostřednictvím VPK. V tuto chvíli probíhají analýzy na straně NTK. 

Na druhou stranu pro účely MVS půjde o objednávku titulu přes zdeduplikované záznamy všech knihoven. Přesto bude muset být zohledněno, že na bibliografický záznam můžou být napojeny různé exempláře (vícesvazková díla, periodika, ...). Z tohoto hlediska považuji debatu na tomto místě v tuto chvíli za irelevantní.

**Comment by Stoklasovab** [comment]
Znovu cituji vyjádření J. Pokorného:
V roce 2017 planujeme na zaklade letosni analyzy zrealizovat (naprogramovat) system pro rizeni EDD a MVS, tedy nastupce VPK, bude mit nazev Ziskej. Bude integrovat v jednom systemu vsechny bezne dorucovaci sluzby, tedy EDD, MVS a repro.
