### ISSUE TITLE
Otvírat "Odkaz" a "Metadata" v nové záložce prohlížeče

### ISSUE THREAD

**Issue by HankaHornychova** [moravianlibrary/CPK#132]
Bylo by možné otvírat odkaz na elektronickou verzi dokumentu ze záložky "Odkaz" a původní záznam z "Metadata" do nové záložky/okna prohlížeče? Pro uživatele by bylo lepší, kdyby měl ve výchozí záložce stále kontakt s výsledky vyhledávání.
![cpk_odkazy](https://cloud.githubusercontent.com/assets/15137682/16840422/f3dac6fa-49d4-11e6-8f97-da389b4ded26.jpg)

**Comment by PetraZabickova** [comment]
Odkazy v novém okně již upravujeme. 

Nejsme si jisti návrhem otevírat metadata do nového okna. Prosíme o vyjádření ET.

**Comment by vodomilka** [comment]
Dobrý den, podle zkušeností z uživatelských výzkumů bych otevírání do nového okna nedoporučovala, neodpovídá to tomu, aby se web choval pokud možnos stejně (a toto je záložka, takže by se měla otevřít a zobrazit stejně jako ostatní záložky).

**Comment by HankaHornychova** [comment]
Podstatou návrhu je vyřešit otvírání odkazů. 
Nyní jsou odkazy např. do Krameria řešeny tak, že uživatel rozklikne Odkaz (viz obrázek nahoře), ten se otevře do stávající záložky a překryje obsah původního okna. Některá rozhraní to takto mají a uživatel se s tím může jinde setkat.
Druhý způsob je - otevřít další záložku prohlížeče. Uživatel pak může pracovat se seznamem výsledků, nechat online zdroje otevřené a věnovat se jim později. Např. takto:

![cpk_odkaz3](https://cloud.githubusercontent.com/assets/15137682/17056936/3598570e-5017-11e6-8a5a-9db29567c006.jpg)

Odkaz a Metadata se ani v současné podobě nechovají stejně.
Petra má pravdu - ať rozhodne skupina.

**Comment by vodomilka** [comment]
Zobrazovani stranky z odkazu v nejakem shadowboxu primo na strance by mohlo
byt pro uzivatele prijemne.
Jeste dovysvetleni Odkaz a Metadata se nemaji chovat stejne, jsou to jine
prvky stranky. Zato Metadata jsou jedna ze zalozek a musi se chivat stejne
jako oayatni zalozky. U metadat nevidim z hlediska uzivatelske zkusenosti
duvod, proc by se mely uzivatelum otvirat v jine zalozce ci v shadowboxu. V
jednom z issue se resilo,zda vubec zalozku s metadaty zobrazovat. U
uzivatelu neknihovniku, pro ktere je portal urcen, lze predpokladat jeji
minimalni vyuziti.
Dne 22. 7. 2016 14:50 napsal uživatel "HankaHornychova" <
notifications@github.com>:

**Comment by Stoklasovab** [comment]
Prosim o nazor i ostatni, uzavreme 22.8. v Brne.

**Comment by vojtisev** [comment]
Za mně souhlas s @PetraZabickova - externí odkazy (např. Kramerius) do nového tabu, současné chování záložky Metada je z mého pohledu OK.

**Comment by PavlinaDolezalova** [comment]
Souhlasím s @vojtisev - externí služby do nového okna, co je součástí CPK zobrazovat ve stránce (v případě metadat tak je to nyní).

**Comment by lenkamaixnerova** [comment]
Souhlasím s @vojtisev a @PavlinaDolezalova a  @PetraZabickova - externí služby do nového okna, co je součástí CPK zobrazovat ve stránce

**Comment by jrmeixner** [comment]
Souhlasím s návrhem - externí služby zobrazovat v novém okně (př. odkazy do Krameria, odkazy do nativních databází, odkazy k fulltextu přes linkservery) - ale co je součástí CPK zobrazovat ve stránce.

**Comment by Stoklasovab** [comment]
Také souhlasí s:  externí služby do nového okna, co je součástí CPK zobrazovat ve stránce

**Comment by Stoklasovab** [comment]
Zřejmě se shodneme na závěru: externí služby do nového okna, co je součástí CPK zobrazovat ve stránce
