### ISSUE TITLE
Report chyb u přihlášených uživatelů

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/CPK#133]
Ahoj, narazila jsem na několik zvláštností, když jsem přihlášený uživatel, nevím, zda je to problém přenosu dat mezi MKP a CPK, ale u nás jsme nezjistili, čím by to mohlo být: 

1) U jednoho konta kolegyně se u 18 z 56 půjčených knih ukazuje místo názvu "Titul není k dispozici" , přitom není žádná logika, u kterých titulů se místo názvu objeví tato hláška.
![beta_titul neni k dispozici](https://cloud.githubusercontent.com/assets/15191997/16916230/13d05ff4-4cfc-11e6-89b3-9e9c53042798.png)
2) U jiného konta se dnes dopoledne zobrazovaly jen 2 ze 3 výpůjček (přitom byly půjčeny všechny ve stejný den), nyní už se zobrazují všechny 3.
3) Odhlašování nefunguje spolehlivě. I když jsem se odhlásila a následně se v tom samém okně a panelu ve Firefoxu přihlašoval kolega, jakmile si v shadow boxu vybral, že se také přihlašuje pod účtem MKP, ani nemusel zadávat jméno a heslo a byl rovnou přihlášený v mém uživatelském účtu. Zkoušeli jsme to víckrát a opakovalo se to.

A pak zde mám jen marginálii, pro něž mi přijde zbytečné zakládat samostané issue:
4) Bylo by fajn, aby se záhlaví stránky s logem Knihovny.cz v levém rohu chovalo stejně. Standartně vede uživatele na homepage. To funguje pro nepřihlášené. Ale pro přihlášené uživatele je vede na Můj účet (a na HP se lze dostat jen klikem prostřednictvím drobečkové navigace. Přitom na Můj účet se uživatel může dostat kliknutím na své jméno nahoře vpravo, tak mi přijde zbytečné ho tam směřovat i po prokliku z loga.

**Comment by PetraZabickova** [comment]
Body 1-2 se týkají nastavení testovacího prostředí na straně MKP.
Bod 3, je otázka realizace IdP na straně MKP. Bližší informace k způsobu řešení zaslány předány MKP.
V obou případech řešeno individuálně mimo github prostředí.

Bod 4. Děkujeme za upozornění. Opravu chystáme.
