### ISSUE TITLE
Zavedení fasety pro autoritní záznamy

### ISSUE THREAD

**Issue by HankaHornychova** [moravianlibrary/CPK#135]
Autoritní záznamy – jmenné – jsou nyní integrovány do fasety Typ dokumentu jako hodnota Osoby.
Nebylo by vhodné pro tento zdroj zavést vlastní fasetu?
Také bych se přimlouvala za vlastní ikonu pro autoritní záznam (místo současného přeškrtnutého fotoaparátu).

![ikona_autorita](https://cloud.githubusercontent.com/assets/15137682/17807018/60ed6fd2-6608-11e6-9424-2a54b0747d88.jpg)

**Comment by Stoklasovab** [comment]
Do typu dokumentu nepatří. Otázka je, jak autoritní záznamy prezentovat uživateli. Autoritní záznam mu nic neříká. Když to nazveme Info o autorovi nebo tak nějak, bude čekat něco úplně jiného...

**Comment by PavlinaDolezalova** [comment]
Autoritní báze by měla být úplně zvlášť od bibliografických. Například zřídit stránku faktografických či slovníkových informací? Do CPK budeme v budoucnu integrovat i tento typ informací než jen bibliografických.

**Comment by Stoklasovab** [comment]
Pod Ostatní - Informace o osobách

**Comment by lenkamaixnerova** [comment]
Taky jsem pro @Stoklasovab dát pod Ostatní - Informace o osobách
