### ISSUE TITLE
Přejmenování fasety Zdrojový dokument

### ISSUE THREAD

**Issue by HankaHornychova** [moravianlibrary/CPK#136]
Prosím o názor: co takhle přejmenovat fasetu "Zdrojový dokument" na "Název periodika"?
Pro uživatele by to bylo asi názornější.

![faseta_zdroj_dokument](https://cloud.githubusercontent.com/assets/15137682/17807624/1320a428-660c-11e6-8896-37c5e028e63d.jpg)

V úplném zobrazení záznamu by zůstal Zdrojový dokument - tam se nejedná pouze o název, ale o další údaje ke zdroji.

**Comment by Stoklasovab** [comment]
Jsem pro. Pro uživatele je to srozumitelnější.

**Comment by PavlinaDolezalova** [comment]
"Periodikum" je nesrozumitelné slovo. 773 obsahuje i název monografie nebo sborníku, který chápou uživatelé jako knihu.

**Comment by Stoklasovab** [comment]
Publikováno v:
