### ISSUE TITLE
Uložená instituce nezůstává vybraná

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#137]
Uložená instituce nezůstává vybraná a výsledky jsou tedy relevatní ke všem zdrojům. To je poměrně velký problém.

**Comment by black23** [comment]
Je tam ikona, která potom preferované zdroje aktuvuje, ale je nutný zásah uživatele. Ale není to logické a není to ani nijak proaktivně zobrazeno. Nepůjde to vyřešit elegatněji?

**Comment by PetraZabickova** [comment]
V minulosti bylo doplněno do fasety instituce "hemžítko. Naše zkušenosti říkají, že toto řešení funguje. Můžeme issue nyní uzavřít?
