### ISSUE TITLE
Provedení strany 404

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#138]
Není to asi úplně zásadní, ale už se mi to sešlo od několika lidí. Stávající podoba se nejenže moc nelíbí, ale je hlavně taková neproaktivní. Nenabízí elegantní řešení, jak z ní pryč.
<img width="837" alt="screenshot at zar 14 21-15-16" src="https://cloud.githubusercontent.com/assets/5516936/18526321/67719564-7ac0-11e6-9c9d-3782c913e00b.png">

Tady jsou velmi použitelná řešení:
https://designschool.canva.com/blog/404-page-design/
Preferoval bych něco ve stylu 14. = nabídněte možnosti nebo 27. vytvořte emocionální spojení.

**Comment by PetraZabickova** [comment]
Děkujeme za připomínku. Neexistující (vytržená) strana 404 z knihy nám připadala jako dobrý vtip. Možná se nám to uplně nepodařilo graficky ztvárnit, tak jak jsme zamýšlely. 

V první fázi přidáme řešení, jak z této strany ven. A další možná řešení do budoucna promyslíme.

**Comment by PetraZabickova** [comment]
Přidali jsme cestu zpět na hlavní stránku a v tuto chvíli zásadní redesign nechystame. Můžeme issue zavřít?

**Comment by vojtisev** [comment]
Za mně je to OK.
