### ISSUE TITLE
RSS feed - kosmetická úprava

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#139]
RSS feed funguje dobře, bylo by hezké přidat do xml anotaci ze záznamu daného titulu. Nyní se posílá toto:

![cpk_rss](https://cloud.githubusercontent.com/assets/11600358/18544145/a6388668-7b33-11e6-8ad6-e72b5f7c1cee.png)

**Comment by PetraZabickova** [comment]
Děkujeme za návrh. Přidáme si to do fronty úkolů.

**Comment by PetraZabickova** [comment]
Anotace přidána.
