### ISSUE TITLE
"Přidat do oblíbených" pro nepřihlášené

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#14]
"Přidat do oblíbených" – bude nějaká alternativa této služby i pro nepřihlášené? Vytváření seznamů záznamů by mělo být pro kohokoli, nejen pro ty "s průkazkou".

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
Alternativou by mohla být funkce schránky, kterou jsme zatím schovali. Jak funguje můžete vyzkoušet třeba na adrese vufind.mzk.cz. Máme obavy, aby uživatelé v případě používání dvou podobných funkcí nebyly zmateni. 

Rádi bychom znali i názory ostatních na daný problém.

**Comment by vojtisev** [comment]
Podle mého názoru je tento typ funkce typicky pro registrované uživatele - přihlásit se může kdokoliv (kdo má e-mail) nezávisle na vlastnictví průkazky (mojeID, google, facebook atd.); nevidím to jako velkou bariéru.

**Comment by Stoklasovab** [comment]
Probereme a uzavřeme na jednání 12.11.

**Comment by PavlinaDolezalova** [comment]
V uživatelských scénářích je na straně 12 toto: "Zároveň uživatele nenutíme se přihlásit, pokud to není bezpodmínečně nutné – má tak například možnost používat místo kam si průběžné odkládat zajímavé knížky a přihlásit se až v moment, pokud by chtěl nějakou objednat." A na straně 11 toto: "Neobjednat si, jít s papírkem do knihovny".
Ráda bych CPK používala jako anonymní rešeršní nástroj při asistovaných rešerších, které řešíme společně s klientem u jednoho pc, výsledkem našeho snažení nebývá často výpůjčka či stažení plného textu, ale přehled literatury k tématu.

**Comment by Stoklasovab** [comment]
Přihlášení neznamená registraci, jak píše V. Vojtíšek. Vzhledem k tomu, že jsem toto upřesňovala při prototypování v NTK já, možná na to ostatní respondenti nebyli upozorněni. Ale je pravda, že bychom měli poskytnout maximum možného i zcela anonymním uživatelům.

**Comment by PetraZabickova** [comment]
Ještě bych jen přidala poznámku:

- oblíbené ukládáme v databázi a musí k ní být registrace
- schránka používá cookies, tzn. může dojít k jejímu vysypání a navíc je není možné sdílet na různých zařízeních

**Comment by Stoklasovab** [comment]
Viz předcházející požadavek

**Comment by vojtisev** [comment]
Předcházející požadavek je #15
