### ISSUE TITLE
Spárování záznamů časopisů - print + e-verze

### ISSUE THREAD

**Issue by jrmeixner** [moravianlibrary/CPK#140]
Při testování linkování z CPK na e-časopisy jsem narazil na chybu při spárování záznamů časopisů v CPK. U časopisu European Journal of Entomology ISSN 1210-5759, 1802-8829 nejsou spárovány pouze záznamy příslušné print verze a e-verze ale také záznamy časopisu European Journal of Phycology ISSN 0967-0262, 1469-4433, záznamy časopisu European Journal of Soil Biology ISSN 1164-5563 a záznamy časopisu European Journal of Philosophy ISSN 0966-8373, 1468-0378. Ve finále to "smíchané" vypadá takto 
![eje_cpk](https://cloud.githubusercontent.com/assets/15102976/19274029/0de5c316-8fcf-11e6-868d-d8f4ad62ab17.jpg)

**Comment by paulusova** [comment]
Děkujeme za nahlášení, došlo k procesnímu problému s deduplikací, který jsme už vyřešili.
