### ISSUE TITLE
Spárování záznamů časopisů - print + e-verze (2. část)

### ISSUE THREAD

**Issue by jrmeixner** [moravianlibrary/CPK#141]
Příklad na prověření pravidla pro slučování a spárování záznamů časopisů - časopis Photosynthetica (ISSN 0300-3064). Na dotaz "Photosynthetica" v CPK, odfiltrovaný přes fasetu Typ dokumentu pouze pro "Noviny a časopisy" dostanu 3 výsledné záznamy:
![cpk_photosynthetica](https://cloud.githubusercontent.com/assets/15102976/19474223/f8a2aeaa-952e-11e6-8f4a-972a59a2de2c.jpg)
Pro KNAV nedošlo ke spárování záznamů print a e-verze titulu v jednom výsledku - https://www.knihovny.cz/Record/sfxknav.000004158 je u prvního výsledku, https://www.knihovny.cz/Record/knav.KNA01-000592184 u druhého výsledku. Přitom všechny záznamy mají stejné ISSN takže se nabízelo sloučení všech záznamů titulu do jednoho výsledku.

**Comment by xmorave2** [comment]
SFX je vyřešeno jinak. Toto je tím pádem irrelevantní.
