### ISSUE TITLE
Najít knihovnu - počet zobrazení záznamů na stránku

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#142]
Bylo by možné zvýšit počet zobrazených záznamů knihoven na stránku, stejně tak jak je to možné při vyhledávání dokumentů, kde lze zvolit 10-20-40? Aktuálně je defaultně 10 knihoven na stránku. A nebo listovací tlačítko přidat i na začátek seznamu (nyní jen dole).

**Comment by PetraZabickova** [comment]
Hotovo

**Comment by paulusova** [comment]
Nastavení více výsledků na stránku lze zatím pouze u vyhledávání dokumentů, na adresáři ještě budeme pracovat.

**Comment by vodomilka** [comment]
A bude možné u adresáře opět zobrazovat výpis knihoven podle jiného klíče než abecedního. V jedné verzi z podzimu byly sežazené podle velikosti/dosahu (první byla NK).

**Comment by PavlinaDolezalova** [comment]
Adresář knihoven  #165

**Comment by PetraZabickova** [comment]
Defaultní řazení upraveno.
