### ISSUE TITLE
Souhlas se zpracováním osobních údajů

### ISSUE THREAD

**Issue by mjtecka** [moravianlibrary/CPK#144]
Zdravím,

po přihlášení do portálu na mě vyskočilo okýnko 
![cpk-souhlasudaje](https://cloud.githubusercontent.com/assets/11203453/19689053/5f56ddcc-9acc-11e6-81b4-2be4fbf6f8ad.png)

Nešlo by tam napsat co přesně (nebo alespoň přibližně) si portál ukládá a tu právnickou poznámku nechat spíš jako doplňující text? Tohle na mě působí jako bych měl otevřít zákon č.101/2000sb. ve aktuálním znění - než to odkliknu. Poněvadž jinak nevím s čím souhlasím a to se mi nelíbí ;-)

MJ.

**Comment by PetraZabickova** [comment]
Celé hlášení jsme upravili.
