### ISSUE TITLE
Koupit

### ISSUE THREAD

**Issue by Stoklasovab** [moravianlibrary/CPK#146]
Když kliknu na KOUPIT, dostanu nabídku knihoven, ne míst, kde mohu knihu koupit. To asi není úplně ono :-( Kniha je na trhu, nedávno jsem si ji kupovala.
![koupit](https://cloud.githubusercontent.com/assets/11761577/19744320/532a7c64-9bcd-11e6-92ad-876db7c98337.jpg)

**Comment by zabak** [comment]
V tomto případě nemá být záložka koupit aktivní (klikatelná), protože se daná kniha koupit nedá. Podobně by neměla být klikatelná ani záložka E.verze, protože žádná E-verze není dostupná. Příklad knihy která se koupit dá je např. https://www.knihovny.cz/Record/mzk.MZK01-000537505/Buy - odkaz na antikvariáty se objeví dole pod záložkou Koupit

**Comment by Stoklasovab** [comment]
A nešlo by to udělat tak, aby se záložka koupit nebo E-verze zobrazovaly jen tehdy, když jsou relevantní?

**Comment by paulusova** [comment]
Zobrazují se růžově, pokud jsou relevantní, v opačném případě jsou šedě. Mysleli jsme si, že to takto pro přehlednost bude stačit.

**Comment by Stoklasovab** [comment]
Technické řešení je ok. Nyní jde spíše o otázku "politickou", zda navigovat i na komerční agregátory nebo ne. Bude řešit Řídicí výbor na svém příštím zasedání, proto uzavírám.
