### ISSUE TITLE
Nelze propojit dvě identity ze stejné instituce

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#147]
Zkoušel jsem propojit dva účty z MKP s výslednou hláškou "Nelze propojit dvě identity ze stejné instituce" - asi to má svůj důvod, chápu. Následně jsem vyzkoušel propojit s testovacím účtem z MZK se stejným výsledkem - máme otestované úspěšné propojování více identit z knihoven? Přidávání dalších účtů OpenID (soc. sítě) funguje.
![cpk_chyba_identity](https://cloud.githubusercontent.com/assets/11600358/19764942/02e19f16-9c46-11e6-8b03-34a757e43096.png)

**Comment by paulusova** [comment]
Dvě identity ze stejné instituce skutečně nelze propojit, nicméně různé instituce propojovat lze. Zkoušela jsem to podle vašeho postupu a problém jsem neměla. Není možné, že testovací účet z MZK už měl připojený jiný účet MKP? V tom případě byste se snažil o propojení MKP s MZK+MKP, což nelze.

**Comment by vojtisev** [comment]
To bude ten problém, díky za rozklíčování.
