### ISSUE TITLE
E-zdroje (e-knihy) - násobné záznamy?

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#148]
Narazil jsem na podivné chování u záznamu e-knihy:

https://www.knihovny.cz/Record/mkpe.4131046

Proklikal jsem se k němu přes seznam e-knih z hlavní strany (po předchozí domluvě generujeme tento seznam pro CPK zvlášť, sklízí se přes OAI-PMH).

CPK jej nabízí v řadě katalogů, MKP je tu hned 3x, proč? 2x bych pochopil, máme zvlášť vylistovaný katalog MKP a katalog E-knihovny (zde bych poprosil o přejmenování fasety z E-zdroje na E-knihovna). Kromě MKP je ale zároveň ještě 3x v MZK (2x pouze jako Moravská zemská knihovna a Kramerius zvlášť). Držíme digitální knihovny jako samostatné instituce?

![screenshot-www knihovny cz 2016-10-28 23-39-42](https://cloud.githubusercontent.com/assets/11600358/19823504/27774870-9d69-11e6-879c-0296263b1370.png)

Poslední související problém - je zvláštní, že na detailu záznamu z vybrané knihovny MKP se mi zobrazuje e-kniha dvakrát v MKP (chápu, jednou e-knihovna, jednou klasický katalog MKP), ale zároveň také Kramerius MZK. To je divné.

![screenshot-www knihovny cz 2016-10-28 23-38-59](https://cloud.githubusercontent.com/assets/11600358/19823520/38fab00a-9d69-11e6-9f66-632bf57ad78f.png)

**Comment by paulusova** [comment]
Ano, digitální knihovny držíme jako samostatné instituce, proto je záznam z MKP 3x, tedy dvakrát z katalogu a jednou ještě z E-knihovny (to samé u MZK, 2x z katalogu, třetí přímo z Krameria). Na příští schůzce Expertního týmu bychom se chtěli pobavit o tom, jestli ze záznamů z digitálních knihoven nenechat pouze odkaz v E-verzi a zbytek nezahodit, což má svá rizika.
V záložce E-verze se zobrazují odkazy ze všech zdeduplikovaných záznamů, díky tomu se do záznamů MKP dostane informace o tom, že je kniha volně dostupná v Krameriu. 
U Krameriů děláme malou úpravu odkazů, pokud se ze záznamu z katalogu (pole 856) dostane do E-verze odkaz na digitální knihovnu obsahující daný dokument, a úplně stejný odkaz nám přijde přímo z Krameria, zobrazujeme pouze ten z Krameria, protože u něj známe přístupnost (u odkazů z 856 je přístupnost "Zkuste získat", protože nemáme jak zjistit, co se pod odkazem skrývá). Stejnou úpravu do příštího releasu uděláme pro E-knihovnu, v případě Swarmwise se tedy z položek v E-verzi z MKP zobrazí pouze ten první s dostupností.
