### ISSUE TITLE
Grafické znároznění možnosti skrolovat "Zobrazit další instituce"

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#149]
Pokud vyskočí okno s nabídkou institucí není v něm přítomen žádný grafický prvek, který by uživatele informoval o možnosti skrolovat v seznamu. Na desktopu je dost místa (zatím) a tak jsou všechny instituce přehledně zobrazeny. Ovšem na mobilu málokoho napadně, že je možné v okně skrolovat. Pomohla bytypická plovoucí čára vpravo. Případně lišta dole (případně nahoře) okna. To okno je také poměrně malé a na meších rozlišeních to může uživatelům způsobovat problémy s ovládáním.
![img_3598](https://cloud.githubusercontent.com/assets/5516936/19832347/eaa29f76-9e21-11e6-8e92-1550da2cb372.PNG)

**Comment by PetraZabickova** [comment]
Děkujeme za připomínku, zapracujeme ji.

**Comment by PetraZabickova** [comment]
Hotovo
