### ISSUE TITLE
Možnost přidávat záznamy do "oblíbených" či do nějaké podobné služby již ze seznamu výsledků

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#15]
Nyní je až z jednotlivých záznamů.

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
Děkujeme za názor. Bude projednáno s PS. Je v rozporu s výsledky uživatelského testování (MKP).

**Comment by paulusova** [comment]
není možnost v seznamu výsledků vyhledávání označit záznamy a hromadně je např. exportovat či poslat e-mailem

navrhují Monika Oravová a Dagmar Smékalová

**Comment by Stoklasovab** [comment]
Probereme a uzavřeme na jednání 12.11.

**Comment by PavlinaDolezalova** [comment]
U nás čtenáři většinou nechtějí pročítat jednotlivé záznamy, v OPAC Aleph jim vesměs k orientaci stačí tabulkové zobrazení (autor, název apod.), často jim doporučujeme rozkliknout celý záznam a podívat se na věcnou katalogizaci kvůli zpřesnění rešerše, proč je tedy nutit procházet jednotlivé záznamy kvůli "vhození" do košíku? Proč by tedy požadovalo těch několik z cca 50 lidí "hodně záznamů na stránce" (uživ. scénáře, s. 10)?

**Comment by Stoklasovab** [comment]
Možnost dostat seznam bez přihlášení ano

**Comment by PetraZabickova** [comment]
Funkce oblíbených se přepracovává, tak aby fungovala, jak pro přihlášené uživatele tak při nepřihlášené. 

Vzhled výsledků dotazů byl přepracován dle návrhu UX, tzn. mimo jiné tak, že neobsahuje možnost přímo z něj přidat záznam do oblíbených. 

Můžeme toto issue uzavřít?

**Comment by PavlinaDolezalova** [comment]
Ano.
