### ISSUE TITLE
Nezobrazení výsledků hledání

### ISSUE THREAD

**Issue by indrakm** [moravianlibrary/CPK#150]
1.hledaný dotaz: miloslav ištvan
2.filtr: typ dokumentu -> hudebniny
3. další filtr ->katalogy knihoven: přidám jednu - načte, přidám druhou - načte, přidám třetí - načte atd.... a dříve nebo později to spadne a už se točí jenom kolečko bez výsledku (po páté minutě už jsem neměřil). Někdy to spadne dokonce už při přidání druhé knihovny přitom výsledků je na toto heslo celkem málo.

![knihovny cz - nacitani](https://cloud.githubusercontent.com/assets/12444931/19929896/f94a47b8-a105-11e6-9393-58bf95b07a55.JPG)

**Comment by PetraZabickova** [comment]
Za použití tohoto hledacího postupu portál zvládne postupně přidat již cca 7 filtrovaných knihoven. 
V případě, že uživatel má zájem filtrovat složitěji, může volbu knihoven provést najednou a pak není nijak omezen.
