### ISSUE TITLE
Dlouhé načítání obálky

### ISSUE THREAD

**Issue by Stoklasovab** [moravianlibrary/CPK#152]
Anotace se načítá několik minut - pak jsem to vzdala.
![obalky](https://cloud.githubusercontent.com/assets/11761577/20402234/2949d5b2-acfc-11e6-848a-fb3c309ee7bd.jpg)

**Comment by zabak** [comment]
Pokud nejedou obálky knih, tak to anotaci nestáhne. V takových případech je nutné otestovat, jak se to chová přímo na webu obalkyknih. Teď to jede, proto zavírám.
