### ISSUE TITLE
Přetečení textu z modulu faset do výsledků hledání

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#156]
Dlouhé texty faset přetíkají do modulu s výsledky hledání.
<img width="477" alt="screenshot at lis 24 07-59-54" src="https://cloud.githubusercontent.com/assets/5516936/20589332/1b29eb8c-b21c-11e6-9c37-73da138962e0.png">

**Comment by PetraZabickova** [comment]
Hotovo
