### ISSUE TITLE
Slučování metadatových záznamů - E-verze

### ISSUE THREAD

**Issue by jrmeixner** [moravianlibrary/CPK#158]
Narazil jsem na záznam e-knihy "Japanese Foreign Policy", kde je na záložce E-verze ve druhém řádku přímý odkaz do Ebrary pro NK viz http://site.ebrary.com/lib/natl/Doc?id=5001666. Otázka je odkud se tento link vzal (ve zdrojovém záznamu z SFX KNAV není) a chybou je v poli Distributor uvedená příslušnost ke KNAV -  viz screenshot.
![cpk_jp_for_pol](https://cloud.githubusercontent.com/assets/15102976/20883890/b347be42-bae8-11e6-9400-380355badaf9.jpg)
Jen pro ověření - platí v CPK, že nastavení uložených dotazů ignoruje filtry/fasety použité v původním rešeršním dotazu?

**Comment by PetraZabickova** [comment]
Bylo vyřešeno.
