### ISSUE TITLE
Knihovny.cz do výsledků Google (sitemap)

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/CPK#159]
Je možné udělat něco, co by postupně dostalo záznamy z Knihovny.cz do výsledků Google na první nebo druhou stranu nálezů? Např. při hledání konkrétního názvu (a/nebo autora)? Jsou již sitemap ve vufindu nastaveny a je to otázka času a zaindexování nebo je třeba ještě něco proaktivně udělat?

**Comment by PetraZabickova** [comment]
Ano, budeme cílit na to, aby se záznamy z portálu dostali do výsledků Google co nejvýše. Z výkonnostních důvodů jsme museli sklízecí roboty z portálu dočasně odstřihnout, návrat jejich indexace děláme postupný.

**Comment by xmorave2** [comment]
Brzy bude vyřešeno.
