### ISSUE TITLE
Interní duplicity

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#16]
Lze toto řešit na úrovni jednotky (996)? Tj. k souhrnnému bibl. záznamu z jedné instituce připojit
jednotky ze všech bibl. záznamů instituce?

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
Toto řešení by bylo v rozporu z funkčním požadavkem zachovat nezměněné původní záznamy. Bude projednáno PS.

**Comment by PetraZabickova** [comment]
Pokud bychom tyto záznamy spojili do jednoho, mohlo by dojít v případě omylem spojených záznamů (chyba v deduplikaci) k závažné nekonzistenci.

**Comment by Stoklasovab** [comment]
Probereme na jednání 12.11. a sdělíme stanovisko, ale k uzavření je, Petro, podle našeho posledního rozhovoru potřebný ještě výzkum v MZK?

**Comment by black23** [comment]
Bylo by možné reportovat interní duplicity podobným způsobem, jak to dělá SKC? Také o ně nestojíme a rádi je opravíme. Stačil by e-mail s našimi ID záznámů. Při dalších shrabání by to bylo vyřešeno. Otázkou je jestli další zapojené knihovny jsou ochotny to řešit tímto způsobem. Podle mého je jediný správný.

**Comment by PetraZabickova** [comment]
Důvody proč některé knihovny ve svém katalogu duplicity mají jsou různé a ne vždy je to z důvodů chyb při vytváření nových záznamů.

Může se jednat např. o sloučení více knihoven/nebo katalogů v dávné historii do jedné a následná neschopnost záznamy díky množství poslučovat: jednak proto, že to manuálně dlouho trvá a proto, že do automatizované definitivní deduplikace si nikdo netroufne.

MZK je jednou z takových knihoven, kde v historii došlo ke sloučení tří Univerzitní, Technické a Pedagogické knihovny) a přestože na slučování pracujeme již léta a stále nemáme všechno hotové. A nejsme jediní.

V každém případě děkujeme za návrh, je to dobrý nápad. Chystáme ještě mírné úpravy deduplikačních procedur, abychom odstranili omylem spojené záznamy. Jakmile budeme mít hotovo, tak rozešleme knihovnám seznamy s návrhy na opravu.

**Comment by zabak** [comment]
Seznamy podezření na interní duplicity budeme knihovnám předávat individuálně na vyžádání.
