### ISSUE TITLE
Geolokace pomocí ikony "Nejbližší" - pořadí výsledků a vlastníků

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/CPK#160]
Nepozoruji, že by klik na mapovou ikonku "nebližší" nějak změnil / přeskládal výsledky dotazu. Zkouším (nepřihlášený) na jednoduchém hledání slova "běhání" - ve výsledcích je na prvním místě titul, který zde (= ve Zlíně) nemáme a nejblíž je v Olomouci, druhý a třetí máme, čtvrtý opět ne - čekal bych, že se po kliku na Nejbližší "propadne" první nález alespoň na třetí místo, ale nestane se tak.
A související věc - bylo fajn, kdyby se po kliku na nejbližší někde objevil výsledek pokusu o geolokaci (např. PSČ nebo název předpokládaného zjištěného místa uživatele) a dynamicky by se přeskládaly seznamy vlastníků u jednotlivých titulů (aby bylo zřejmé, že se ono "přiblížení" odehrálo). Ta přeskládání by asi nebylo lehké - spíš ze sféry přání...
![geo_nejblizsi](https://cloud.githubusercontent.com/assets/16186956/21098417/77b1ee1c-c069-11e6-9ea6-2238845c3594.jpg)

**Comment by PetraZabickova** [comment]
Vypadá to, že na Vašem prohlížeči není povoleno zjišťování geolokace. V případě, že povoleno je, tak se vybere (zatrhne) nejbližší knihovna(y) ve filtru Instituce a dojde přeřazení pořadí záznamů  zobrazovaných knihoven. Zkuste prosím toto funkčnost nejlépe na mobilu, tam to zjištění geolokace bude fungovat nejpravděpodobněji.

Bohužel na naší straně neexistuje způsob, jak znovu vynutit volbu povolení geolokace v případě, že již byla někdy zamítnuta nebo je zablokována. Je to zcela v kompetenci každého prohlížeče a navíc se každý prohlížeč chová trochu jinak.

**Comment by PetraZabickova** [comment]
Prohlížeč v případě, že je geolokace nezjistitelná zahlásí, že "Pozice je nedostupná". Můžete mít ale v prohlížeči nastaveno nezobrazování takovýchto dialogových oken a pak se tuto informace nedozvíte, což bohužel ale nejsme schopni ovlivnit.

**Comment by PetraZabickova** [comment]
Trvá stále problém nebo můžeme issue zavřít?

**Comment by jankanka** [comment]
Problem stale trva, ale asi nebude na strane Knihovny.cz. V prohlizeci (zkouseno ve 4 ruznych) omezeni nastavene nemam, ale jeden z nich (Safari) mi po odsouhlaseni zjisteni rekl, ze je pozice nedostupna - presne, jak pisete. Takze mam asi smulu, protoze sedim v nejake "neviditelne" siti. Nicmene ty moje dva navrhy zakreslene zelene ve screenshotu ponechavam - pokud by to slo, neskodilo by to.

**Comment by PetraZabickova** [comment]
Přidáno hlášení, pokud geolokaci nedokážeme zjistit.
