### ISSUE TITLE
Zobrazovani  hodnoceni cbdb.cz skrze API ObalekKnih

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#161]
Hlasuji za pridani teto funkce, protoze je velmi zajimava pro uzivatele.

**Comment by PetraZabickova** [comment]
Víme, sledujeme, plánujeme a hledáme místo kam umístíme. 

Trochu nám to komplikuje ta situace, že hvězdičku používáme pro označení přidání záznamu do oblíbených. 

A pak je taky na rozhodnutí, zda umistíme už do výsledků hledání nebo jen do úplného zobrazení záznamů. Nějaké nápady a návrhy?

**Comment by vojtisev** [comment]
Řešil bych to zařazením mezi doporučení, doručoval bych jenom celkové hodnocení s odkazem na detail v cbdb.cz. V rychlosti jsem se díval na API, mělo by to umožňovat.

![knihovny cz_cbdb](https://cloud.githubusercontent.com/assets/11600358/22643047/36d7cb58-ec5d-11e6-82d3-3d16fb173f16.png)

**Comment by black23** [comment]
U nás to zobrazujeme i ve výsledcích hledání, kde bych řekl, že to je pro uživatele cenné vodítko.
![screenshot at uno 06 11-17-09](https://cloud.githubusercontent.com/assets/5516936/22643220/d8ffbb3e-ec5d-11e6-94a2-9dab881e188b.png)
Dále zobrazujeme hodnocení i v detailu.
![screenshot at uno 06 11-16-40](https://cloud.githubusercontent.com/assets/5516936/22643221/d91c03ca-ec5d-11e6-80aa-ca81cad22357.png)

Pokud chybí zobrazuje se proaktivní "tlačítko" hodnotit.

**Comment by vojtisev** [comment]
@black23 u nás zobrazujeme ve výsledcích vyhledávání hodnocení také a z rozhovorů s uživateli víme, že to prakticky nevidí. Výsledky vyhledávání mi už teď připadají předimenzované, máme mnoho informací, které na tom místě chceme sdělit - hodnocení bych z toho vyjmul...

**Comment by black23** [comment]
Jasně, je to věc k debatě. Jak jen ukázal. jak to funguje u nás, taky ve VuFindu. Naši uživatelé zase říkají, že hodnocení je pro ně užitečnější ve výsledcích hledání, než v detailu :-) Takže to celé může být o celkovém vnímání rozhraní.

**Comment by PetraZabickova** [comment]
S ohledem na rozhodnutí Řídícího výboru o zákazu veškerých napojení portálu na komerční subjekty budeme raději toto řešení nejprve konzultovat s ním.

**Comment by black23** [comment]
Rozumím. ČBDB považuji za book fan projekt, který propaguje čtenářství a pěstuje komunitu. Prosím @Stoklasovab o tlumočení ŘV. Domnívám se, že těmto typům projektů bychom se neměli uzavírat, protože tam se schází i naše cílová skupina.

**Comment by Stoklasovab** [comment]
Na ŘV se jednalo o navigaci přes KOUPIT na komerční subjekty. Viz citace ze zápisu dále.  Využití dat z ČBDB bychom měli projednat na jednání ET 8.3. a pak předložit podněty ŘV najednou.
BLOK III: ODKAZ NA MOŽNOST ZAKOUPENÍ DOKUMENTŮ U KOMERČNÍCH AGREGÁTORŮ
jde o frekventovaný požadavek vyplývající z testování i reálného provozu. Zároveň je třeba odpovědět těm agregátorům, kteří projevili o spolupráci s portálem zájem.
Proběhla delší diskuse o tom, zda je/není vhodné upozorňovat formou navigace na nákup dokumentů na komerční dodavatele. Byla diskutována možnost významné protislužby – např. poskytnutí plných textů ke zpřístupnění v knihovnách atd.
Závěr: 
Navigace na nákup (záložka KOUPIT) bude z nabídky možností získání dokumentu na portálu Knihovny.cz vypuštěna. Je třeba promyslet vhodný model spolupráce – protihodnotu (např. možnost využití plného textu v knihovnách) a začít vyjednávat. Tématu by měla být věnována kromě jednání expertního týmu i diplomová práce.

**Comment by PetraZabickova** [comment]
Pokud u hodnocení neoznačíme odkud hodnocení přichází (cbdb), bude tato informace pro uživatele užitečná a srozumitelná?

Jít s ní už do výsledků nebo do úplného zobrazení. Do výsledků lze přidávat pouze omezené množství informací, aby byly ještě přehledné.
