### ISSUE TITLE
Důvod přítomnosti nálezů ve výsledcích

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/CPK#162]
Při vyhledání - např. slova Hedvábník, dokonce výběrem z našeptávače ze skupiny V názvech - se najde 332 výsledků. V názvu má to slovo jen zlomek z nich, zbytek ho má - neznámo kde. U některých se zobrazuje info, že jhe slovo ve fulltextu a je tam vidět kontextový úryvek, ale u většiny ne. Je to poněkud frustrující. Pokud se správně domnívám, že i ta většina záznamů, kde slovo není nikde (ani v zobrazení metadat) vidět, je má ve FT, pak se tato informace musí zobrazit u všech. A přemýšlím (jistě ne první) - jak naložíme s "nadvládou" fulltextů při hledání? Nezkusíme je nějak "odštípnout"? Už jsme o tom určitě mluvili... Zkusme vymyslet nějaký jednoduchý filtr (checkbox nebo fasetu - byl bych spíš pro to první), který by před hledáním i po něm dokázal z výsledků ty fulltextové odfiltrovat.
![duvod_nalezeni](https://cloud.githubusercontent.com/assets/16186956/22499887/96f1e3f2-e861-11e6-87c3-19b0e76b2ff5.jpg)

**Comment by PetraZabickova** [comment]
Dobrý den,

Na úpravách relevance a zobrazení úryvků v posledních době intenzivně pracujeme a postupně se snažíme dostat obojí do lepšího stavu.

1,
Zobrazování úryvků z fulltextů dělá problémy. V případě, že se úryvek nezobrazí, tak je to proto, že fulltext dané knihy je příliš velký a úryvek se v daném fulltextu nachází na takovém místě, že přesáhne hranice nastaveného limitu. Když jsme nastavili daný limit tak, aby k takovému stavu nedocházelo, došlo ke značnému zpomalené odezvy SOLRu a odpovědi na jakékoli dotazy byly neúnosně pomalé. Hledáme tu hranici, kdy nás to ještě nezatěžuje, ale zobrazíme maximum možného.

2,
Druhá problematická věc ohledně zobrazení úryvků je ta, že v případě víceslovného dotazu se ne vždy zobrazuje ten nejlepší úryvek, ale ten první, který nám SOLR vrátí. Tento problém máme v plánu řešit brzy, ale je vázán na přechod na novou verzi SOLRu, takže jej musíme pečlivě naplánovat, tak aby nezpůsobil komplikace jinde.

3,
Do třetice celého bych ráda popsala chování našeptávače, které se chová jinak než pravděpodobně očekáváte. Při použití našeptávače uživatel dostane nabídnuty k výběru názvy, autory a témata, výsledky dotazů, ale našeptávač dle těchto kategorií vyhledávání neomezuje. Takové chování našeptávače nebylo zamýšleno.

Děkuji za reakci. Ráda další detaily a nejasnosti dovysvětlím. Naše snaha je skutečně najít co nejlepší řešení.

Petra Žabičková

**Comment by zabak** [comment]
Došli jsme k závěru, že chování našeptávače upravíme dle návrhu - tj. zvolením našeptané položky dojde k omezení vyhledávání na danou kategorii (autor/název/téma).

**Comment by PetraZabickova** [comment]
Našeptávač byl dle návrhu upraven. Jiné chování vyhledávání ve fulltextech můžeme probrat na schůzce ET.

**Comment by PetraZabickova** [comment]
Nadvláda fulltextů nad výsledky hledání bude k řešení.

**Comment by zabak** [comment]
Bude přidán přepínač ovlivňující jestli se hledá nebo nehledá i ve fulltextu.

**Comment by xmorave2** [comment]
Přidáme možnost vyhledávání bez plných textů do pokročilého vyhledávání.
