### ISSUE TITLE
Obálky

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#163]
Katalog CPK v poslední době nezobrazuje prakticky žádné obálky knih, ani fotografie autorů. Jedná se o obálky, které jsou na obalkyknih.cz dostupné. Např.:

http://www.obalkyknih.cz/view?isbn=978-80-7294-348-7

v CPK:

https://www.knihovny.cz/Record/cbvk.CbvkUsCat_0220779

V čem je problém?

(Jinak ten odkazovaný záznam Jihočeské vědecké knihovny obsahuje třikrát pole 520 3 |a s anotací, která je stejná a přece jiná. To je zvláštní.)

**Comment by black23** [comment]
API 3.x?

**Comment by PetraZabickova** [comment]
Obalkyknih mívají občas krátkodobé výpadky, které nebývají dlouhé, ale bývají. Můžete to prosím např. během dneška sledovat a dát nám vědět, zda se jedná o problém trvalý nebo opakovaný. Buďto bohužel máte štěstí na to, že se vždy trefíte do výpadku, nebo máte nějaké problém na straně vašeho prohlížeče. V každém případě my obálky nyní vidíme.

Odkazovaný záznam obsahuje 3x pole 520 s různými anotacemi, proto je zobrazujeme. Pokud záznam konkrétní knihovny anotaci neobsahuje, tak zobrazuje, pokud existuje, anotaci ze serveru obalkyknih.cz

**Comment by vojtisev** [comment]
Aha! Nenapadlo mně, že by to mohl být problém prohlížeče - ve firefoxu se to zobrazuje korektně, Chrome Verze 56.0.2924.87 píše:

> https://cache.obalkyknih.cz/api/cover?multi=%7B%22isbn%22%3A%228074663841%2…bn%22%3A%22cnb002592119%22%7D&type=icon&keywords=Rud%C3%BD%20%C5%A1%C3%A1l Failed to load resource: net::ERR_INSECURE_RESPONSE
https://cache.obalkyknih.cz/api/cover?multi=%7B%22isbn%22%3A%228081110232%2…001-mzk.MZK01001134944%22%7D&type=icon&keywords=Srdce%20v%20temnot%C3%A1ch Failed to load resource: net::ERR_INSECURE_RESPONSE
https://cache.obalkyknih.cz/api/cover?multi=%7B%22isbn%22%3A%228024332795%2…b001817907%22%7D&type=icon&keywords=Almu%C5%BEna%20jen%20pro%20bohat%C3%A9 Failed to load resource: net::ERR_INSECURE_RESPONSE
https://cache.obalkyknih.cz/api/cover?multi=%7B%22isbn%22%3A%228024349043%2…n%22%3A%22cnb002429255%22%7D&type=icon&keywords=Osmansk%C3%BD%20t%C3%A1bor Failed to load resource: net::ERR_INSECURE_RESPONSE
https://cache.obalkyknih.cz/api/cover?multi=%7B%22isbn%22%3A%228074470946%2…ywords=Den%C3%ADk%20mal%C3%A9ho%20poseroutky.%20O%C5%A1kliv%C3%A1%20pravda Failed to load resource: net::ERR_INSECURE_RESPONSE
https://cache.obalkyknih.cz/api/cover?multi=%7B%22nbn%22%3A%22BOA001-mkpe.4040563%22%7D&type=icon&keywords=Ve%20vlasti Failed to load resource: net::ERR_INSECURE_RESPONSE
https://cache.obalkyknih.cz/api/cover?multi=%7B%22isbn%22%3A%220992235707%2…n%22%3A%22BOA001-mkpe.4241477%22%7D&type=icon&keywords=Sleepy%20Mr%20Sloth Failed to load resource: net::ERR_INSECURE_RESPONSE
https://cache.obalkyknih.cz/api/cover?multi=%7B%22nbn%22%3A%22BOA001-mkpe.4272558%22%7D&type=icon&keywords=Vl%C4%8D%C3%AD%20k%C5%AF%C5%BEe Failed to load resource: net::ERR_INSECURE_RESPONSE
https://cache.obalkyknih.cz/api/cover?multi=%7B%22nbn%22%3A%22BOA001-mkpe.3…eywords=O%20pt%C3%A1ku%20Ohniv%C3%A1ku%20a%20mo%C5%99sk%C3%A9%20pann%C4%9B Failed to load resource: net::ERR_INSECURE_RESPONSE
https://cache.obalkyknih.cz/api/cover?multi=%7B%22nbn%22%3A%22BOA001-mkpe.3347532%22%7D&type=icon&keywords=Cesta%20na%20sever Failed to load resource: net::ERR_INSECURE_RESPONSE
medium Failed to load resource: net::ERR_INSECURE_RESPONSE
medium Failed to load resource: net::ERR_INSECURE_RESPONSE
medium Failed to load resource: net::ERR_INSECURE_RESPONSE
medium Failed to load resource: net::ERR_INSECURE_RESPONSE
medium Failed to load resource: net::ERR_INSECURE_RESPONSE

**Comment by vojtisev** [comment]
@PetraZabickova ještě k té anotaci - zdálo se mi, že by bylo dobré na to upozornit, ale je jasné, že je to problém zdrojových dat...

**Comment by PetraZabickova** [comment]
Nemate MACa?

**Comment by vojtisev** [comment]
@PetraZabickova Ne, klasické PC s Windows 7 Proffesional; zkusil jsem vypnout AdBlock na doméně knihovny.cz, ale také beze změny..

**Comment by PetraZabickova** [comment]
Problém je na straně Obálek knih, které používají SSL certifikát, který není prohlížečem Chrome uznáván jako bezpečný. Situaci jsme kolegům nahlásili, nejsme schopni vyřešit na naší straně.

**Comment by paulusova** [comment]
Problém už vyřešili a obálky se zobrazují.
