### ISSUE TITLE
Podivné zřetězení záznamů 

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#166]
Příklad:

https://www.knihovny.cz/Record/svkul.EZ3148000001006980?referer=aHR0cHM6Ly93d3cua25paG92bnkuY3ovU2VhcmNoL1Jlc3VsdHMvP2Jvb2wwJTVCJTVEPUFORCZ0eXBlMCU1QiU1RD1hZHZfc2VhcmNoX3RpdGxlX3NlcmllcyZ0eXBlMCU1QiU1RD1hZHZfc2VhcmNoX3llYXJfb2ZfcHVibGljYXRpb24mbG9va2ZvcjAlNUIlNUQ9QnlsbytuJUMzJUExcytwJUM0JTlCdCZsb29rZm9yMCU1QiU1RD0yMDE2JmpvaW49QU5EJnNlYXJjaFR5cGVUZW1wbGF0ZT1hZHZhbmNlZCZsaW1pdD0xMCZzb3J0PXJlbGV2YW5jZSZwYWdlPTE

**Comment by paulusova** [comment]
Jsou to stejné záznamy, takže se správně zdeduplikují k sobě. Domluvíme se s Ústím, jestli jsou s tím schopni něco dělat.
