### ISSUE TITLE
Patentové dokumenty

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#168]
1. Pokud je v bázi ÚPV přihláška i udělený patent, pak by měl být záznam obou patentových dokumentů v jednom záznamu, stejně, jak je tomu v nativním rozhraní ÚPV. Přihláška již obsahuje veškeré údaje k vynálezu.
CPK
![cpk-patent](https://cloud.githubusercontent.com/assets/15088603/23671859/0ea839b6-036d-11e7-9247-19e634c14361.jpg)

ÚPV
![upv-patenty](https://cloud.githubusercontent.com/assets/15088603/23671874/1d5c0dc0-036d-11e7-96f4-92ea77a4370d.jpg)

2. Přehled položek řízení - bude také v CPK zobrazován například formou odkazu do báze ÚPV? Viz příklad https://isdv.upv.cz/webapp/WEBAPP.rejst.detail

3. Je MPT selekčním údajem? V pokročilém vyhledávání jsem nenalezla. Podle jakých údajů lze vyhledávat patentové dokumenty a užitné vzory?

**Comment by PavlinaDolezalova** [comment]
K bodu 3 zda-li MPT selekčním prvkem - v pokročilém vyhledávání je již kolonka MPT, ale nefunguje dle nápovědy - nelze použít * ani ? (příklad G01L1/18 versus G01L1*; G01L?/18 atd.) - takže upravit nápovědu?
Bylo by možné MPT také přidat do všech polí a základního vyhledávání - pokud dnes zadám MPT do pole "všechna pole", pak dostanu jen knihy (takže všechna pole asi nejsou všechna pole).

4. Zobrazení záznamu přihlášky/patentu - bylo by možné více zdůraznit důležité selekční údaje jakými je číslo přihlášky a číslo dokumentu (například posunutím výše, minimálně mezi pole 300 a 653 nebo analogii k ISBN a ISSN - až na konec záznamu za  pole 024 MPT), z hlediska významu bych tyto údaje nepovažovala za poznámku (pole 500), ale jednoznačný identifikátor dokumentu.

**Comment by PetraZabickova** [comment]
- filtrujeme nyní ty přihlášky, které jsou duplicitní k patentům
- přidali jsme informaci o číslu přihlášky/patentu do pole 013 a zároveň do exportů záznamů

Na ostatních problémech dále pracujeme.

**Comment by PetraZabickova** [comment]
3, K bodu 3 - MPT je nyní jiý možné prohledávat v pokročilém hledání. Bohužel není možné jej přidat do základního hledání, protože znaky obsahují řady speciálních znaků, které musí být speciálně ošetřeny.

2, S indexací Položek řízení v nejbližší době nepočítáme.

4, K případným změnám zobrazení patentů se vrátíme po nasazení nové verze vufindu.

**Comment by xmorave2** [comment]
V nové verzi vyřešeno. Zobrazení upravovat nebudeme.
