### ISSUE TITLE
Báze KKL 

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#169]
Záznamy z báze KKL by bylo dobré označovat jednoznačněji, např. Národní knihovna ČR - KKL Databáze knihovnické literatury a řadit tuto bázi do ostatních zdrojů, ne do katalogů knihoven.
![cpk_anl_2](https://cloud.githubusercontent.com/assets/15088603/25478699/7ab4f764-2b42-11e7-9362-c724a1ef6d1f.jpg)

**Comment by zabak** [comment]
Problém je, že v té databázi jsou i knihy, které půjčují, tj nejde o pouhou bibliografickou databázi a z tohoto hlediska je to prostě pobočka/oddělení NK. Chovat se tedy k záznamům různě podle toho, jestli jde o půjčitelný svazek nebo bibliografický/analytický záznam bez možnosti půjčení?

**Comment by PavlinaDolezalova** [comment]
V KKL vazba LKR nebo HLD nebo 856 (nebo kombinace) není u všech záznamů, u některých vazba na PT není (např. Právo, Kladenský deník apod.). Takže již nyní se CPK chová k různým záznamům v rámci jedné báze různě. Je nutné rozlišovat **bibliografii** bez možnosti objednávat a **katalog** s možností objednávky? Druhově smíšených bibliografií bude víc. Myslela jsem, že by bylo naopak dobré v prostředí CPK obohacovat nejen analytické záznamy o vazby na plné texty z katalogů knihoven (773txq9)

**Comment by xmorave2** [comment]
KKL vnímáme především jako katalog. Podstatná část báze má fyzické jednotky, které je možné vypůjčit.
