### ISSUE TITLE
Souborný katalog 

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#17]
Do fasety město/instituce SK ČR nepatří, je možné odstraňovat duplicity s knihovnami, které
posílají záznamy do CPK přímo? Pokud nikoli, pak záznam z SK ČR zobrazovat jako poslední.

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
Děkujeme za názor. Rádi bychom znali i názory ostatních.

**Comment by Stoklasovab** [comment]
Také myslím, že SK nepatří do kategorie město/instituce. Zdá se mi, že u knih se SK v institucích mnohdy nezobrazuje, ale u audiodokumentů ano.

**Comment by vojtisev** [comment]
Souhlasím s návrhem Mgr. Doležalové.

**Comment by PetraZabickova** [comment]
Pokud Souborný katalog nepatří do fasety Město/instituce, tak kam s ním? Aby byla zachována možnost vyfiltrovat data pouze Souborného katalogu? Stejně tak, kam se zdroji typu Normy, Patenty, Článkové databáze? Jakým způsobem se chovat ke zdrojů, které vytváří jedna knihovna, ale jsou obecně univerzální? Zařadit ji pod danou knihovnu nebo ne? Umožnit ve fasetě Město/Instituce filtrování poboček?

**Comment by Stoklasovab** [comment]
Probereme na jednání 12.11., ale asi neuzavřeme

**Comment by Stoklasovab** [comment]
Viz předcházející bod

**Comment by Stoklasovab** [comment]
SK pořadí - na konec za jednotlivými institucemi
