### ISSUE TITLE
Dostupnost dokumentu/typ výpůjčky a řazení výsledků u titulu

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/CPK#170]
Na workshopu se nám ukázalo, že část lidí vnímá fasetu **Typ výpůjčky** zároveň jako informaci o **dostupnosti**. Respektive podporuje je v tom i skutečnost, že je uvedeno: Volný výběr. Fakticky se však při výpisu záznamu titulu ukazuje Stav, což je pro lidi matoucí. V kolonce stav se zobrazují varianty: absenčně/prezenčně/nelze vypůjčit, což vlastně s fasetou nesouvisí (Volný výběr se ve stavu nezobrazuje). 

Pokud někdo zatrhne ve fasetě Typ výpůjčky "absenční", tak se zobrazí všechny svazky v dané knihovně, ale může se stát, že jednomu absenčnímu svazku je předřazeno 20 prezenčních, takže na první pohled má uživatel dojem, že faseta nefunguje správně (dokud nedoroluje k absenčnímu svazku).

Bylo by možné uvažovat v této oblasti o změně? Buď u výsledků primárně zobrazovat to, co odpovídá výběru ve fasetách (podobně když má uživatel vybrané jen některé knihovny, tak aby se jako první instituce ve zkráceném podobě v boxu zobrazují právě vybrané) a tedy předřadit ze svazků absenční, pokud si je uživatel vybral ve fasetě?
 
Dávám k úvaze, zda spíše než tato faseta zajímá uživatele skutečná dostupnost dokumentu - co si může vypůjčit, a zda by tedy data z OAI PMH neumožnila alespoň výhledově vytvoření fasety dostupnosti dokumentu (Dostupné/Lze rezervovat/Prezenčně/Neznámá dostupnost).

**Comment by PetraZabickova** [comment]
Není možné ani výhledově indexovat aktuální dostupnost. Rychlost sklizně přes OAI většiny knihovních systémů je taková, že neumožňuje celodenní průběžné sklízení záznamů, navíc by to znamenalo průběžnou celodenní indexaci, která by byla nároční i na strojový čas a ještě zhoršovala odezvu.

Nepomohlo by srozumitelnosti fasety upravit textaci jednotlivých položek ve fasetě a případné doplnění doplňkových faset. Např.
- není nutno objednávat/volný výběr/bez objednání, ...
- objednávka ze skladu/po objednání, ...
- prezenčně/nelze odnést domů, ...
- absenčně/lze odnést domů, ...?

**Comment by PetraZabickova** [comment]
Změna řazení jednotek by byla znatelný zásah do stávajícího algoritmu a nejsme si jisti, jestli by vynaložený čas byl adekvátní úpravě.

**Comment by vojtisev** [comment]
Z mého pohledu je nejdůležitější, co znamená "část lidí vnímá" - faseta má celkem dobře popsanou nápovědu v hoverboxu (při najetí) a typ výpůjčky skutečně neznamená informace o dostupnosti (navíc, toto neřeší protokol OAI, nýbrž ncip).

Řazení by mi dávalo větší smysl, než hledat ideální pojmenování faset (takové neexistuje) - pokud mi vyhledávač nabídne, co potřebuji, nebudu fasety potřebovat. V momentě, kdy portál bude umět něco půjčit, soustředil bych se na to, abychom uživatelům dokázali "podstrčit" ten nejdostupnější titul. Podle harmonogramu bychom se tomu pravděpodobně mohli věnovat s koncem roku - předpokládám, že bychom tou dobou mohli mít i více dat z analytiky.

Za sebe tedy navrhuji to odložit do doby, než budeme řešit implementaci služby Získej.

**Comment by vodomilka** [comment]
OK, díky za vysvětlení. Chápu, že je to náročné a ponechme případné úpravy a textace na později.
Snažím se přinášet zpětnou vazbu ze školení, kdy lidé často reagují překvapeně, respektive mají například pocit, že systém nefunguje správně, když si zatrhli "absenční výpůjčky" a první co vidí jsou prezenční.

**Comment by PetraZabickova** [comment]
Kvůli optimalizaci (zrychlení) načítání faset a zjednodušení chování dojde v nové verzi Vufindu k zásadní změně fasety dostupnosti. Faseta nebude umožňovat filtrovat fyzickou dostupnost, ale pouze online dostupnost. 

Toto rozhodnutí jsme udělali na základě toho, že tato faseta nejvíce zpomalovala odezvu portálu a zároveň byla minimálně používáná tak, aby její výsledky dávali uživatelům smysl. Správné hodnoty totiž dávala pouze tehdy, pokud ji uživatel použil v kombinaci s filtrováním konkrétních knihoven, což se nestávalo.
