### ISSUE TITLE
Nastavení - neukládá se

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/CPK#171]
V uživatelském účtu se mi nedaří uložit v části Nastavení pro citace, řazení či počet výsledků na stránku.
Plus - bylo by možné/užitečné sem vřadit pro přihlášené uživatele i nastavení preferovaných knihoven, které se nyní provádí jen ve fasetě?

**Comment by paulusova** [comment]
Nastavení citací, řazení a počtu na stránku jsme spravili, na přidání preferovaných knihoven ještě pracujeme.

**Comment by PetraZabickova** [comment]
Bylo již opraveno.
