### ISSUE TITLE
Proměnlivé řazení knihoven ve fasetě instituce

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/CPK#172]
Všimla jsem si, že když omezuji výsledky vyhledávání podle typů dokumentů, tak se poté mění i pořadí měst ve fasetě Instituce. Možná je to podle počtu výskytů, ale přišlo by mi komfortnější pro uživatele, kdyby města/knihovny ve městech byly ve fixním pořadí a uživatel nemusel města různě hledat. Navíc zde se uživateli u knihoven nenapovídá, kde toho mají nejvíc. Respektive ne zřetelně.
![cpk2017_razeni knihoven u vyfiltrovanych vysledku](https://cloud.githubusercontent.com/assets/15191997/24103851/e1c9476e-0d80-11e7-9fc8-581b30e70480.png)

**Comment by PetraZabickova** [comment]
Stejně jako u všech ostatních faset/filtrů se jednotlivé položky řadí podle počtu výskytů. V nejbližší době bychom se rádi vyhnuly zásahům do chování faset. Budeme tento požadavek ale samozřejmě brát v potaz a na toto chování se zaměříme při příštích uživatelských testech.

**Comment by xmorave2** [comment]
V nové verzi řazeno vždy podle abecedy.
