### ISSUE TITLE
Odkaz do Ebook Central na záložce E-verze

### ISSUE THREAD

**Issue by jrmeixner** [moravianlibrary/CPK#173]
Zjistil jsem, že u všech záznamů e-knih z Ebook Central, které byly naimportované z SFX KNAV je na záložce E-verze kromě odkazu k SFX KNAV i direct link do rozhraní Ebook Central - www.proquest.com/products-services/ebooks-main.html. Příklad záznamu viz screenshot https://www.knihovny.cz/Record/sfxknav.000248172
![cpk_odkazebc](https://cloud.githubusercontent.com/assets/15102976/24952509/f93856ca-1f77-11e7-8573-c07b593bfd60.jpg)
Problém je, že odkaz nevede k fulltextu do rozhraní Ebook Central a uživatele zavede na info stránky Proquestu. Pro přístup k fulltextu má direct link do Ebook Central pro KNAV syntax:
http://ezproxy.lib.cas.cz/login?url=https://ebookcentral.proquest.com/lib/knav/detail.action?docID=XXXXXX
kde docID je identifikátor e-knihy v EBC. Hodnoty docID pro daný titul nejsou ale součastí exportů z SFX.
Takže bych ze záložky E-verze direct linky do EBC úplně odstranil a přístup k fulltextům nechal na odkazech k SFX Menu - viz pole 856 v exportním souboru z SFX.

**Comment by jiripavlik88** [comment]
OpenURL by spravneji mel generovat CPK. Podle zpracovani exportu ve formatu Google Scholar by CPK mel nabizet prolinkovani pres OpenURL ve vsech knihovnach, kde e-kniha je dostupna. Titul je dostupny take na Karlovce, pres SFX UK je dostupne prolinkovani na plny text.

**Comment by jrmeixner** [comment]
OK, Jirko tady není problém s OpenURL nebo SFX - první odkaz na SFX KNAV je vygenerován z exportní souboru (pole 856) a metadata v OpenURL formátu fungují správně a uživatele KNAV po přihlášení k EZproxy přivedou k fulltextu . Druhý odkaz (http://www.proquest.com/products-services/ebooks-main.html) s exportem z SFX KNAV nemá nic společného (v datech není) a k fulltextu uživatele KNAV nepřivede a i když to podle popisků tak vypadá:-(. Fakt by mě zajímalo odkud se v CPK vzal.

**Comment by PetraZabickova** [comment]
Opraveno.
