### ISSUE TITLE
Řazení báze ANL ve výsledcích hledání

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#174]
Bylo by možné zacházet s bází  Výběr článků v českých novinách, časopisech a sbornících - ANL jako se Souborným katalogem ČR v řazení výsledků? Tj. pokud si nezaškrtnu konkrétní zdroj a článek bude mít výskyt ve více zdrojích, tak ANL řadit až na konec?
![cpk_anl](https://cloud.githubusercontent.com/assets/15088603/25477734/dbe9bd66-2b3e-11e7-9a5a-66d13fbe77eb.jpg)

**Comment by PetraZabickova** [comment]
Provedeno.
