### ISSUE TITLE
Indexace holdingu z linkserveru - využití jak v LI tak v CI CPK

### ISSUE THREAD

**Issue by jrmeixner** [moravianlibrary/CPK#178]
Problém, který nastal teď po spuštění centrálního indexu v CPK kdy byly z LI CPK odstraněny zaindexované holdingy z linkserveru. Tady bych volbu nechal na rozhodnutí zapojené knihovny, protože třeba pro KNAV, která nemá elektronický fond přímo v Alephu, mi to dává smysl. Kromě toho CI EDS nemusí všechny holdingy pokrýt - záleží na aktivaci jednotlivých kolekcí v CI EDS. Někdy to vyřeší až zaindexování MARC záznamů titulů od vydavatele v lokální části EDS - viz příručky nebo encyklopedia Springera např.  "Encyclopedia of Microfluidics and Nanofluidics" (číslo záznamu v exp. z SFX KNAV 000297657). 
Další věc, na kterou jsem u záznamů e-knih v CI CPK narazil, že často je uvedeno u dostupnosti "Plný text nenalezen" přitom tituly jsou v KNAV dostupné  - např.  "Základy sportovní výživy" (číslo záznamu v exp. z SFX KNAV 000314759) nebo "Street Design: The Secret to Great Cities" (číslo záznamu v exp. z SFX KNAV 000254033).

**Comment by PetraZabickova** [comment]
Indexace holdingu v LI je na vyžádání znova možná.
