### ISSUE TITLE
Linkování z centrálního indexu na úrovni článek = článek

### ISSUE THREAD

**Issue by jrmeixner** [moravianlibrary/CPK#179]
Současné nastavení CI EDS umožňuje linkování na úrovni článek = titul. Uživatel se tak dostane v koncovém rozhraní databáze jen na seznam ročníků a čísel. Pravdou je, že kvalita metadatových záznamů v CI EDS je dle zdrojových kolekcí dost odlišná, to ovlivňuje i přesnost přenesených metadat v OpenURL formátu na linkserver a pak výsledné prolinkování. Záznamy např. ze Scopusu nebo WOS indexů jsou ale v CI EDS spolehlivým zdrojem pro prolinkování přes linkserver přímo na článek. Např. článek "The gradient superconvergence of the finite volume method for a nonlinear elliptic problem of nonmonotone type"
CI CPK umožní ze záznamu článku prolinkování na titul http://msfx.lib.cas.cz/sfxlcl3?url_ver=Z39.88-2004&sfx.ignore_date_threshold=1&rft.object_id=958480168425&sfx.institute=KNAV
Pro srovnání prolinkování stejného článku (záznamu Scopus v EDS KNAV) http://msfx.lib.cas.cz/sfxlcl3?ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2Fvufind%3Agenerator&rft.date=20151022&disable_directlink=true&sfx.directlink=off&atitle=The+gradient+superconvergence+of+the+finite+volume+method+for+a+nonlinear+elliptic+problem+of+nonmonotone+type&rft.au=Zhang%2C+T.&rft.issn=15729109&rft.volume=60&rft.issue=5&rft.spage=573&sfx.ignore_date_threshold=1&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&rft.title=The+gradient+superconvergence+of+the+finite+volume+method+for+a+nonlinear+elliptic+problem+of+nonmonotone+type&rft.creator=Zhang%2C+T.

**Comment by zabak** [comment]
Problém je, že to SFX tlačítko dost často nikam nevede, viz. https://vufind.lib.cas.cz/ustav/KNAV/EBSCO/Search?lookfor=The+gradient+superconvergence+of+the+finite+volume+method+for+a+nonlinear+elliptic+problem+of+nonmonotone+type&type=AllFields&service=articles&filter[]=addfacetfilter%28ContentProvider%3ABASE%29 
a příslušné SFX volání http://msfx.lib.cas.cz/sfxlcl3?ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2Fvufind%3Agenerator&rft.date=2015&disable_directlink=true&sfx.directlink=off&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&rft.creator=Zhang%2C+Tie&rft.title=The+gradient+superconvergence+of+the+finite+volume+method+for+a+nonlinear+elliptic+problem+of+nonmonotone+type

**Comment by jrmeixner** [comment]
Ano ten metadatový záznam článku z BASE viz https://vufind.lib.cas.cz/ustav/KNAV/EBSCO/Record?id=edsbas.ftdmlcz.oai.oai.dml.cz.10338.dmlcz.144392|edsbas je z pohledu OpenURL k ničemu - chybí ISSN, volume, issue nebo DOI, takže linkserver se pro prolinkování nemá čeho chytit. Kladem záznamu je ten přímý link do DML-CZ https://dml.cz//handle/10338.dmlcz/144392 ale k fulltextu to nepomůže - embargo 24 měsíců. Ale když si udělám rešerši na název tohoto článku tak se dostanu k metadatovému záznamu článku ze Scopusu viz https://vufind.lib.cas.cz/ustav/KNAV/EBSCO/Record?id=edselc.2-52.0-84941948062|edselc který mě přes SFX prolinkuje na článek do EBSCA, Proquestu nebo Springera. No skoro si říkám, že tu metadatovou kolekci BASE pak bude lepší v CI EDS deaktivovat, negativa převažují nad pozitivy.

**Comment by xmorave2** [comment]
Vyřešeno v nové verzi.
