### ISSUE TITLE
Fasety obecně

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#18]
nechat zabalené 

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
Děkujeme za názor. Bude projednáváno PS.

**Comment by PetraZabickova** [comment]
Výsledky uživatelských testování (MKP) ukazují, že uživatelé fasety vůbec nechtějí a nepotřebují. Budeme rádi za názor ostatních. Sami se s neexistencí faset nedokážeme úplně smířit.

**Comment by Stoklasovab** [comment]
Nechat zabalené

**Comment by vojtisev** [comment]
Nebudeme se vracet k těm několika (třem?) nejrelevantnějším, které by zůstaly rozbalené? (typicky by mně zajímala např. dostupnost, rok vydání)

**Comment by Stoklasovab** [comment]
Petro, zkuste to kompromisní řešení a když nebude vyhovovat, vrátíme se k tomu.

**Comment by PetraZabickova** [comment]
Které z těch řešení je to kompromisní?

**Comment by Stoklasovab** [comment]
Probereme a uzavřeme na jednání 12.11.

**Comment by PavlinaDolezalova** [comment]
V dokumentu "Známé chyby, otevřené problémy a nedokončené práce, plány na rozvoj" jsme navrhli variantu nechat všechny fasety pootevřené, zobrazit např. jen první tři hodnoty.
Z uživatelského testování vyplynulo, že na zobrazení záznamů mají uživatelé minimální požadavky: autor, název, rok, nakladatel, ale při výběru z nalezených záznamů požadují témata - což přeloženo pro mne znamená fasety  (už. scénáře, s. 10)

**Comment by Stoklasovab** [comment]
Autor, název, téma - to jsou nejčastější požadavky i podle zahraničních průzkumů řádově větších, než ten náš. Ještě se tam objevuje rok, nakladatel ne. U průzkumů, kde jsem byla, nakladatele vypíchnutého nahoře nikdo nechtěl a navíc je zde problém s neautoritní podobou/mnoha podobami téhož nakladatele.

**Comment by Stoklasovab** [comment]
PŽabičková: problém hierarchických faset

**Comment by Stoklasovab** [comment]
Korespondenčně - které fasety a jak 
Na GD dokument - "hlasování"

**Comment by PetraZabickova** [comment]
Rádi bychom uzavřeli problematiku seznamu, počtu, pořadí, rozbalení a faset. V případě dalších požadavků na změny prosíme o přesnou specifikaci do konce května. Alternativně budeme považovat issue za uzavřené.

**Comment by Stoklasovab** [comment]
Stačí toto? https://docs.google.com/document/d/1aeF-rVZpvZ4AS3z_e3ef8xMMLrLZPaE7qeKntGjaYTw/edit

**Comment by zabak** [comment]
Ne, potřebujeme konsolidovanou, jednoznačnou odpověď/zadání. V této chvíli už spíše vymezení se k současné podobě faset. Tj. členové týmu by si měli fasety proklikat, vyzkoušet práci s nimi a v případě že jsou připomínky, tak je potřeba, aby se pak celý tým shodnul na tom, co je potřeba změnit a jak.

**Comment by Stoklasovab** [comment]
OK, zkonsolidujeme :-)

**Comment by PavlinaDolezalova** [comment]
Připomínky jsem již zadala jako https://github.com/moravianlibrary/CPK/issues/117 a https://github.com/moravianlibrary/CPK/issues/118.

**Comment by jrmeixner** [comment]
Když procházím sdílený dokument https://docs.google.com/document/d/1aeF-rVZpvZ4AS3z_e3ef8xMMLrLZPaE7qeKntGjaYTw/edit tak se připomínky v beta verzi projevily (odstranění faset Edice a Období, pořadí faset, rozbalenost X nerozbalenost). Fasety Žánr a Typ dokumentu v CPK odpovídají fasetě Formát dokumentu v CI, problém ale může představovat velká variabilita termínů v Žánru. Bude možné unifikovat termíny v Žánru?

**Comment by jankanka** [comment]
Jen pro úplnost: moje návrhy byly ve výše odkázaném dokumentu povětšinou v opozici vůči ostatním, takže je tady nechci opakovat a prosazovat (byť si za většinou z nich stojím ;)

**Comment by HankaHornychova** [comment]
Připomínky k současné podobě faset nemám.

**Comment by Stoklasovab** [comment]
Ponechat současnou podobu faset.
