### ISSUE TITLE
Index: články s plným textem v DOAJ Directory

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#180]
Ačkoli je plný text veřejně dostupný, nejsou (pravděpodobně) všechny články z DOAJ Directory opatřeny odkazem.
Např.:
https://www.knihovny.cz/EdsRecord/edselc,edselc.2-52.0-85010379913
se tváží, že je dostupný pouze v NKP a KNAV.
http://prntscr.com/glnrfw
Po kliknutí na NKP se dozvím, že to je DOAJ http://prntscr.com/glnrsa
A po dalším kliku jsem na hlavní stránce časopisu. Musím hledat znovu tam, abych se dostal k článku. 
Přijde mi tohle strašná škoda. Ten full text je zdarma dostupný, ale tuhle cestu p němu vytrpí asi málokdo.

**Comment by zabak** [comment]
Čekáme na export volných dokumentů z SFX JIB, na základě kterého toto budeme moci vyřešit.

**Comment by vojtisev** [comment]
Toto chování platí (dočasně) pro všechny články, nejen OA.

**Comment by jrmeixner** [comment]
V SFX je u DOAJ umožněno prolinkování jen na úrovni "Journal" viz screenshot
![alis_linking](https://user-images.githubusercontent.com/15102976/30543502-b88ad696-9c83-11e7-8123-4e4e001dfe4c.jpg)

**Comment by jiripavlik88** [comment]
Zalezi na databazi - jak pise Jarda, u DOAJ je pres SFX prolinkovani na
uroven casopisu.
U jinych databazi je prolinkovani az na uroven clanku.

Pekne pondelni odpoledne

        jp

**Comment by PetraZabickova** [comment]
Vyřešeno.
