### ISSUE TITLE
Zobrazování úryvků z Krameriů v úplném zobrazení záznamu

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#181]
Bylo by možné zobrazovat úryvky z Krameriů také v úplném zobrazení záznamu, nyní lze jen v seznamu výsledků?
![schranka01](https://user-images.githubusercontent.com/15088603/30591175-077d5aa8-9d42-11e7-8dd6-11d6b42c8e9b.jpg)

**Comment by xmorave2** [comment]
Toto má význam pouze v kontextu vyhledávání, nikoliv v detailu záznamu.
