### ISSUE TITLE
zahraniční zdroje = žádné výsledky (automatické použití vyhledávacích operátorů)

### ISSUE THREAD

**Issue by michalMZK** [moravianlibrary/CPK#182]
Zadáním dotazu [**_Autumn Knausgaard_**](https://www.knihovny.cz/Search/Results/?lookfor0%5B%5D=Autumn+Knausgaard&searchTypeTemplate=basic&type0%5B%5D=AllFields&page=1&bool0%5B%5D=AND&join=AND&limit=20&sort=relevance&keepEnabledFilters=true&database=EDS) získám 0 výsledků, což nedopovídá skutečnému obsahu CI, viz dotaz [**_Knausgaard_**](https://www.knihovny.cz/Search/Results/?join=AND&searchTypeTemplate=basic&database=EDS&bool0%5B%5D=AND&lookfor0%5B%5D=Knausgaard&type0%5B%5D=AllFields&limit=20&sort=date&page=1)…

**UPDATE**: zjistil jsem, že stačí přidat AND, abych získal [12 výsledků](https://www.knihovny.cz/Search/Results/?lookfor0%5B%5D=Autumn+AND+Knausgaard&searchTypeTemplate=basic&type0%5B%5D=AllFields&page=1&bool0%5B%5D=AND&join=AND&limit=20&sort=date&keepEnabledFilters=true&database=EDS). 

**Neměl by ale být vyhledávací operátor AND použit automaticky?** 

Považoval bych to za logičtější chování.

Děkuji za ověření.

**Comment by zabak** [comment]
K tomu ještě doplněk - v EDS KNAV je na stejný dotaz 273 hitů ale na dotaz Autumn AND Knausgaard  jen 52 hitů.

**Comment by michalMZK** [comment]
Díval jsem se předtím taky do EDS v NKP, tam je to [246 výsledků](http://search.ebscohost.com/login.aspx?direct=true&bquery=knausgaard+AND+autumn&lang=cs&type=0), s AND nebo bez něj :) Ale tam je to v nativním rozhraní…

**Comment by jrmeixner** [comment]
Podívejte se na nastavení Search Modes pro EDS API profil v EBSCOAdmin. Je to na první záložce Searching, dá se to editovat přes Modify a vetšinou je tam defaultně aktivní mode All - "Find all my search terms" - jestli není tak by to možná vysvětlovalo nulové výsledky na dotaz v CI CPK. Na záložce Searching je také přepínač pro "Require uppercase Boolean operators (AND, OR, NOT)". Podle testu - v EDS KNAV je těch 273 výsledků z pole TX (včetně prohledávání fulltextů článků) ale jak se dá se Booleovský operátor tak těch 52 výsledků je bez bez prohledávání fulltextů. Pro automatické hledání ve fulltextech je také přepínač na záložce Searching volba Expanders editace přes Modify.

**Comment by PetraZabickova** [comment]
Zdá se, že změna konfigurace na Find all my search terms, skutečně pomohla. Děkuji.
