### ISSUE TITLE
Návrat na záznam dokumentu pokud jej nelze objednat

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#186]
Pokud nelze dokument objednat, a výsledkem je hláška "Nepodařilo se vytvořit požadavek...", lze se z tohoto formuláře dostat zpět na bibl. záznam nebo seznam výsledků pouze přes tlačítko "zpět" v prohlížeči. Bylo by možné pro tento případ nastavit možnost návratu na bibl. záznam?
![schranka02a](https://user-images.githubusercontent.com/15088603/31880167-07fe0550-b7e0-11e7-894a-207d52fbbe43.jpg)

**Comment by PetraZabickova** [comment]
V minulosti již opraveno.
