### ISSUE TITLE
Vyhledávání podle ISBN / ISSN / ISMN

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#187]
1. Do návodu by bylo dobré doplnit, že je nutné v pokročilém vyhledávání při použití parametru ISBN/ISSN/ISMN důsledně zadávat číslo pouze v lidským okem čitelné podobě , tj. se spojovníky např. 978-80-246-3071-7. Při používání vyhledávání "ve všech polích" jak v pokročilém, tak základním vyhledávání stačí varianta skutečného ISBN, ISSN, ISMN, tj. bez spojovníků, např. 9788024630717.

2. Jsou indexovány všechny výskyty pole 020 v záznamu? Jako příklad uvádím sysno 000848730 SVK Hradec Králové, s prvním výskytem ISBN 978-80-246-3071-7, další výskyt ISBN 9788024630830 již v CPK vyhledat nelze. Zvážit, zda-li indexovat i 776##z.
![schranka04a](https://user-images.githubusercontent.com/15088603/32102801-2f884d24-bb1e-11e7-8300-42f07c4170c0.jpg)
![schranka04b](https://user-images.githubusercontent.com/15088603/32102811-38698d18-bb1e-11e7-9388-c87d5700f4ee.jpg)

**Comment by PetraZabickova** [comment]
Opravili jsme, již se indexují skutečně všechny výskyty a nerozlišujeme zda byl identifikátor zadán se spojovníkem nebo bez.

V tuto chvíli pole 776z neindexujeme.
