### ISSUE TITLE
Našeptávač

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#19]
našeptávat i autory a klíčová slova

navrhuje Mgr. Pavlína Doležalová

**Comment by vojtisev** [comment]
V MKP to máme nastavené na 1. názvy, 2. autory, 3. klíčová slova (deskriptory), 4. články na webu:
![naseptavac](https://cloud.githubusercontent.com/assets/11600358/10072974/be004d1c-62c5-11e5-9430-e646bd894c1c.png)

Důležitější IMHO je, aby načítání / našeptávání nezpomalovalo zadávání dotazu; nevím, jaké je u nás globálně využití u kategorií 1 - 4, ale pokud by to pomohlo, mělo by to jít dohledat.

**Comment by black23** [comment]
Pokud našeptávač nabídne název dokumentu dávalo by mi smysl doplnit ho o typ dokumenru. Dokud nebudeme schopni sloučit pod jeden název všechna provedení, mohlo by tento detail pomoci uživatelům v nalezení. Zvlášť pokud hledají audioknihy nebo e-knihy.

**Comment by PetraZabickova** [comment]
Díky za ukázku našeptávače v MKP. Můžeme se inspirovat. Je otázka jestli jít cestou našeptávání v různých polích nebo přidat typ dokumentu. Nejsem si jistá jestli by fungovalo obojí, obávám se, že byl to bylo velmi nepřehledné. Co myslíte?

**Comment by zabak** [comment]
Doplnění typu dokumentu si nedokážu představit - resp. v případě že bude babička jako film, kniha, audiokniha a článek, tak to místo jednoho nabídne 4 výsledky? Podle mě to není dobrý nápad. Leda jako miniikonky na jednom řádku, ale... nevím. Tematické dělení našeptávače MKP je zajímavé, rozhodně bude nutno při našeptávání zohlednit v podrobném vyhledávání. Jestli to dělit u zjednodušeného nevím - nebo jestli tam jen dát nejpravděpodobnější varianty ale nerozlišovat jejich typ nadpisem ale třeba jen ikonou nebo nijak...

**Comment by black23** [comment]
Pokud budou záznamy sjednoceny FRBRizací, tak to doplnění informace o typu dokumentu nemá význam. Má připomínka je relevantní pouze v situaci, kdy vyhledávání najde Babiček x. Tak to v současném stavu je. Ale vím, že deduplikaci a sjednocování se ještě pracuje.

**Comment by zabak** [comment]
Spíš mi jde o jinou věc: našeptávač našeptává slova nebo fráze. Ty budou deduplikované v každém případě. Nevyjede tam 10x Babička ale 1x i když v datech je těch babiček 10. Ale bude tam jednou "Babička" a jednou "babička obrazy z venkovského života" a jednou "Babička Josef"...

**Comment by jrmeixner** [comment]
Aktuálně mi nefunguje našeptávání při zadávání dotazu. Je na vině přechod na novou verzi?

**Comment by paulusova** [comment]
Ano, v příští verzi už by měl být znova funkční.

**Comment by vojtisev** [comment]
Typ dokumentu IMHO má význam až ve výsledcích vyhledávání (+ FRBR) - u našeptávání vidím význam v tom, že se "trefím" s názvem knihy, nebo jménem autora, popř. zmiňovaných klíčových slov.

**Comment by Stoklasovab** [comment]
Probereme na jednání 12.11., ale asi neuzavřeme.

**Comment by Stoklasovab** [comment]
Pustit více údajů, otestovat
Rolovací okno - podle statistik využití

**Comment by paulusova** [comment]
našeptávač nyní našeptává názvy, autory a témata

**Comment by vojtisev** [comment]
Současné nastavení se mi líbí - je to funkční, přehledné. Jenom se to načítá poměrně dlouho (protože beta?).

**Comment by PetraZabickova** [comment]
Ano, bohužel v tuto chvíli je pomalá odezva daná hardwarem. Chystáme na nejbližší měsíce velkou reorganizaci, posílení hardwaru a následně velké zátěžové testy.
