### ISSUE TITLE
Formát pro knihovníky

### ISSUE THREAD

**Issue by Stoklasovab** [moravianlibrary/CPK#191]
Toto se mi objevilo jako formát pro knihovníky https://www.knihovny.cz/EdsRecord/edb,113193637/Details?referer=#tabnav
Je to v pořádku?

**Comment by zabak** [comment]
EDS neobsahuje MARC, ale uvedenou datovou strukturu, proto se i zobrazuje v této podobě. Zkusíme vymyslet lepší formátování.

**Comment by Stoklasovab** [comment]
Ok. B


Odesláno ze Samsung Mobile.

<div>-------- Původní zpráva --------</div><div>Od: zabak <notifications@github.com> </div><div>Datum:21. 01. 2018  2:20  (GMT+01:00) </div><div>Komu: moravianlibrary/CPK <CPK@noreply.github.com> </div><div>Cc: Bohdana Stoklasová <stoklasovabohdana@gmail.com>, Author <author@noreply.github.com> </div><div>Předmět: Re: [moravianlibrary/CPK] Formát pro knihovníky (#191) </div><div>
</div>EDS neobsahuje MARC, ale uvedenou datovou strukturu, proto se i zobrazuje v této podobě. Zkusíme vymyslet lepší formátování.

**Comment by PetraZabickova** [comment]
Hotovo.
