### ISSUE TITLE
E-knihy ke stažení - aktualizace dat

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#192]
Bylo by prosím možné aktualizovat feed s novými e-knihami z OAI MKP? Jedná se o tyto tituly:

https://www.knihovny.cz/Search/Results?lookFor0[]=&type0[]=AllFields&bool0[]=AND&join=AND&searchTypeTemplate=basic&page=1&keepEnabledFilters=true&limit=20&sort=relevance&filter=JYOwzgDsBOCGAuwD2IBcAiApgaxMAFgJ4D62mxY8sAXpnukA

Sklízení toho OAI setu funguje v pořádku?

**Comment by paulusova** [comment]
Sklízení funguje. V nové verzi máme úpravu, která nám umožní přidávat záznamy hromadně (doteď to šlo pouze po jednom). Čekáme na tuto změnu a hned poté e-knihy přidáme, seznam už mám nachystaný.

**Comment by PetraZabickova** [comment]
Řeší se

**Comment by black23** [comment]
Nějaký posun v této věci?

**Comment by PetraZabickova** [comment]
Tohle je už vyřešeno dávno. Omlouváme se, za včasné neinformování.

**Comment by vojtisev** [comment]
Omlouvám se, ale nedá mi to a musím to znovu otevřít. Jak je nastavený filtr pro "E-knihy ke stažení"? Výsledky pro vyhledávání:

https://goo.gl/rvYbG2

ukazují 520 titulů. Přes OAI jich nabízíme momentálně 1482. Co je špatně?

**Comment by paulusova** [comment]
Je to vaše E-knihovna, momentálně jich tam vidím 1520, takže máme nějaké navíc (asi problém se smazanými záznamy, ověřím to).
 
![eknihovna_search](https://user-images.githubusercontent.com/14090956/54749407-b72f6f80-4bd4-11e9-96d2-e54c336d6962.png)

**Comment by vojtisev** [comment]
Aha. Moje chyba - je tam 1 520, ale já viděl jenom "520". Díky za reakci.
