### ISSUE TITLE
Duplicitní kontrolní čísla / pole 001

### ISSUE THREAD

**Issue by matyasbajger** [moravianlibrary/CPK#193]
V bázi našeho katalogu (MSVK Ostrava) je bohužel větší množství duplicitních kontrolních čísel v Marc poli 001. Používá CPK pro spárování Marc21 pole 001 nebo OAI element /record/header/identifier (založený na Aleph sysnu, které je naštěstí ok) ?  Pokud pole 001/kontrolní číslo, bude asi nejlepší celou bázi po opravě znova přeharvestovat. Díky!

**Comment by PetraZabickova** [comment]
Dobrý den,

dejte nám po opravě prosím vědět a my si data stáhneme celý znova. Děkujeme.
 
Zdraví,
Petra Žabičková
