### ISSUE TITLE
Prezentace deduplikovaných záznamů v rámci jedné organizace ve výsledcích hledání

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#195]
Pokud jsou bibl. záznamy v rámci báze jedné organizace deduplikovány, pak ve výsledcích hledání je nabízen pouze jeden bibl. záznam a ty ostatní jsou přístupné z detailu záznamu pod odkazem "Knihovna má i další záznam(y) pro tuto publikaci: zde". 
Příklad: Skizzen und Fragmente / von Ignaz Lederer. Pilsen : Druck von Reiner & Smid, 1838. 
sysno PNA01 000394013 má exempláře 8F187/8 a 20A156 - schováno pod odkazem.
sysno PNA01 000648521 má exemplář 1G234 - nabízí se jako první (ve výsledcích hledání).
Podle jakého principu se zobrazují tyto záznamy ve výsledcích hledání, podle kvality bibl. zpracování? 

Navrhuji 
a) zobrazovat jako první ten, který má více připojených exemplářů, pokud takový není, pak použít stávající pravidlo pro zobrazení ve výsledcích.
b) graficky zvýraznit text: "Knihovna má i další záznam(y) pro tuto publikaci: zde". Nyní jej lze snadno přehlédnout a zrovna v tomto případě preferujeme výpůjčku 8F187/8 (lze objednat do studovny) před exempláři z badatelny (1G234 a 20A156).

**Comment by xmorave2** [comment]
Vyřešeno v nové verzi. 

Ad b) nelze určit jaký záznam  je preferovaný, my to totiž nevíme  a nemáme to jak zjistit.
