### ISSUE TITLE
"Nedostupné" jednotky

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#197]
V Alephu u nás v případě, že má jednotka </z13><status>On Hold</status> je v CPK označena „Nedostupné“ (status požadavku S, je připravena na regále rezervací a čeká na čtenáře). Mohlo by být označeno jinak než nedostupné? Protože ona je dostupná zhruba stejně, jako ta vypůjčená. U nás používáme asi dlouhé „Připraveno k vypůjčení“. Aktuální příklad on hold jednotky je třeba signatura 32A3800-12, sysno 000364087 (https://bit.ly/2PhsnYc).

Tyto jednotky mají také v CPK čtenářském kontě "Rezervace a objednávky" zaškrtávací okénko, takže to vypadá, jako že je lze smazat, ale nelze.
![cpk_onhold_1](https://user-images.githubusercontent.com/15088603/49496463-5454db00-f866-11e8-9043-5525fbbb44ff.jpg)
![cpk_onhold_2](https://user-images.githubusercontent.com/15088603/49496466-56b73500-f866-11e8-8608-d99b827fa640.jpg)

**Comment by PavlinaDolezalova** [comment]
Dobrý den, aktuální "on hold" jednotka je VEJLUPEK, Miroslav. Okrajem k románové tvorbě Karla Matěje Čapka-Choda : články, causerie, eseje.  Písek: MiradiX, 2013. exemplář 51A2385a.

**Comment by xmorave2** [comment]
Aktuálně irrelevantní. V nové verzi je to vyřešeno jinak.
