### ISSUE TITLE
Chci vypůjčit - pořadí ve frontě

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#199]
Dobrý den, ve formuláři "Chci vypůjčit" v řádce "Vaše pořadí ve frontě" se zobrazuj čísla od 1. do 10., pokud je pořadí ve frontě vyšší (tedy dvoumístné) od 11. výše, zobrazuje se jen 1., 2. ... 9. I když jednotky mají v RESTful API v <queue> příslušný počet požadavků na items.
![cpk_rezervace_1](https://user-images.githubusercontent.com/15088603/49523538-4d4fbc00-f8aa-11e8-9e41-879eb3666f4c.jpg)

Pokud pořadí končí na číslo 9, pak se vždy zobrazí jen číslo 10 (počet požadavků 39, mé pořadí ve frontě je 10.)
![cpk_rezervace_2](https://user-images.githubusercontent.com/15088603/49523573-5e003200-f8aa-11e8-9a9f-6df4e92fccf0.jpg)

**Comment by PavlinaDolezalova** [comment]
Dobrý den, budete se tomuto případu věnovat?

**Comment by PetraZabickova** [comment]
Dobrý den, chyba bude opravena v nové verzi portálu.

**Comment by xmorave2** [comment]
Bude dořešeno příští týden. Zavírám
