### ISSUE TITLE
E-knihy ke stažení: formáty

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#204]
U odkazů ke stažení postrádám jednoznačné rozlišení souborů

Nyní je to takto:
Web | Dostupné | Plný text | Městská knihovna v Praze - E-knihovna
Web | Dostupné | Plný text | Městská knihovna v Praze - E-knihovna
Web | Dostupné | Odkaz na plný text | Městská knihovna v Praze - E-knihovna
Web | Dostupné | Plný text | Městská knihovna v Praze - E-knihovna
Web | Dostupné | Plný text | Městská knihovna v Praze - E-knihovna
Web | Dostupné | Obálka | Městská knihovna v Praze - E-knihovna

Není jasné, že to jde stáhnout v PDG, ePUB, PRC a HTML. A také by tomu myslím pohla nějaká proaktivní pobídka typu Stáhněte si zdarma. Tím to doplní ten výborný nápad "50 e-knih do nové čtečky".

![Screenshot_2019-03-19 Kyberpunk heavy ](https://user-images.githubusercontent.com/5516936/54641368-53049280-4a92-11e9-9631-78c814051e66.png)

**Comment by PetraZabickova** [comment]
Zobrazujeme tam text podpole y z pole 856. Záznamy Městké knihovny v Praze, které pro zobrazení těchto záznamů upřednostnujeme, obsahují pouze text "Plný text" bez rozlišení.  @vojtisev Nemohli byste pri generovani 856 poli, do podpole y, pridat informaci o fotmatu plneho textu?

**Comment by black23** [comment]
Nechci se přít, ale v metadatech to je. Konkrétně v podpoli $y. Ten screenshot čerpá ze stejných vstupních dat.

856 | 4 | 1 | \|u https://web2.mlp.cz/koweb/00/04/29/90/58/valka_s_mloky.epub  \|y Plný text (EPUB)  \|4 N

4 | 1 | \|u https://web2.mlp.cz/koweb/00/04/29/90/58/valka_s_mloky.html  \|y Plný text (HTML)  \|4 N
4 | 1 | \|u https://web2.mlp.cz/koweb/00/04/29/90/58/valka_s_mloky.pdf  \|y Plný text (PDF)  \|4 N
4 | 1 | \|u https://web2.mlp.cz/koweb/00/04/29/90/58/valka_s_mloky.prc  \|y Plný text (PRC)  \|4 N

**Comment by PetraZabickova** [comment]
Je to v metadatech ale ne Městské knihovny v Praze. Pole 856 přichází z různých knihoven. Deduplikujeme je, abychom je nezobrazovali multiplicitně, pokud to je možné.  Pokud duplicitní pole zahazujeme, tak je to vždy, pokud to jde, od zdroje, které daný dokument nevlastní.

https://www.knihovny.cz/Record/svkos.MVK01-000744378/Details
https://www.knihovny.cz/Record/mkpe.4345510/Details

**Comment by PetraZabickova** [comment]
Zobrazujeme tam text podpole y z pole 856. Záznamy Městké knihovny v Praze, které pro zobrazení těchto záznamů upřednostnujeme, obsahují pouze text "Plný text" bez rozlišení.  @v

**Comment by PetraZabickova** [comment]
Rádi bychom se vyhnuly parsování podpole u, pokud by to bylo možné.

**Comment by black23** [comment]
To parsování vadí z jakých důvodů? Je to pár řádků kódu, např.:

> $ebookUrls = [];
    foreach ($urls as $url) {
        $ext = preg_replace('/.*\.([a-z]*)$/', '$1', $url['url']);
        if( isset($formatTexts[$ext]) ) {
            $ebookUrls[] = [
                'description' => $formatTexts[$ext],
                'url'         => $url['url'],
                'icon'        => $icons[$ext],
            ];

**Comment by vojtisev** [comment]
Aktualizovali jsme po dohodě OAI feed a posíláme pole 856. Prosím zavřít.
