### ISSUE TITLE
Prázdný dotaz způsobí pád aplikace

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#206]
Došlo k chybě - zkuste, prosím, zopakovat svůj požadavek později.
Omlouváme se za nepohodlí.

V případě přetrvávajících problémů se na nás můžete obrátit prostřednictvím formuláře zpětné vazby nebo emailem na cpk-support@mzk.cz.
Zpět na Hlavní stránku

**Comment by martinkrcal** [comment]
Zrovna jsi se trefil do výpadku. To je nyní vyřešeno a funguje. Můžeš vyzkoušet.
