### ISSUE TITLE
Zobrazení informací o recenzovaném dokumentu

### ISSUE THREAD

**Issue by stastnap** [moravianlibrary/CPK#217]
Bylo by možné nastavit u zobrazení článků, které jsou recenzí nějaké publikace, informace o této publikaci? 
Informace jsou uvedené v poli 787 záznamu článku. 
Příklad:
záznam na knihovny.cz: https://www.knihovny.cz/Record/anl.ANL01-001501525
záznam v bázi ANL: https://aleph.nkp.cz/F/?func=direct&doc_number=001501525&local_base=ANL

![recenze-zobrazeni](https://user-images.githubusercontent.com/5681041/69245965-21574480-0ba8-11ea-90fb-cbb07ecfb738.jpg)

**Comment by xmorave2** [comment]
Bude implementováno
