### ISSUE TITLE
varianty názvu ve fasetách

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#22]
ve fasetě Vydavatel sjednotit varianty typu: Colour production?], [Colour production], Colour production?, Colour production

Monika Oravová a Dagmar Smékalová

**Comment by PetraZabickova** [comment]
Děkujeme za upozornění na problematiku. Nejednotnou interpunkci budeme schopni během indexace vyřešit. Musíme nejprve zmapovat, kde všude má takový zásah smysl.

**Comment by paulusova** [comment]
První část úprav je v v2.7.0, budeme dále upravovat.
