### ISSUE TITLE
Oblíbené: řazení

### ISSUE THREAD

**Issue by michalMZK** [moravianlibrary/CPK#225]
Všiml jsem si dvou věcí:

1. po aktualizaci tam chybí možnost seřadit oblíbené položky **podle data přidání**, v MZK vufindu je to označeno "**od nejnovějších**"
2. v řazení podle abecedy je "č" dříve než "c", ale nejspíš jen v případě CD  :)

![screenshot-2022-03-01 09 12 10 www knihovny cz e4d75d8d69c9](https://user-images.githubusercontent.com/3798932/156130380-3a1f068f-3fba-4736-8c04-0aab82f25269.jpg)

Díky!

**Comment by xmorave2** [comment]
ad 1) Řazení oblíbených podle data přidání budeme řešit

ad 2) Řazení podle názvu už by mělo fungovat spránvě
