### ISSUE TITLE
co se prohledává v základním vyhledávání

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#23]
je záměrem, že se vyhledají i podobná/příbuzná slova k vyhledávanému termínu? - př. zadám-li do jednoduchého vyhledávání Harmon, vyhledá se kromě autorů s tímto jménem i kniha, která obsahuje v názvu harmonized

Monika Oravová a Dagmar Smékalová

**Comment by PetraZabickova** [comment]
Děkujeme za upozornění. Tohle nebyl úplně záměr. Vufind vyhledávání je optimalizováno pro anglický jazyk. V příští verzi již budeme mít opraveno a záměrné pravostraná expanze  bude probíhat pomocí *.
