### ISSUE TITLE
Požadavek na přihlášení pro možnost komentovat - nekonečné načítání

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#25]
- po kliknutí na tlačítko "Nejprve se musíte přihlásit".

![komentar_prihlaseni](https://cloud.githubusercontent.com/assets/11600358/10071725/49d75844-62bc-11e5-820b-bf92aba03fea.png)

**Comment by PetraZabickova** [comment]
Děkujeme za náhlášení chyby. Bude opraveno.
