### ISSUE TITLE
Chybějící obálky - doplnit univerzální pro jednotlivé druhy dokumentů

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#26]
Chybějících obálek bude asi obrovské množství, vypadalo by lépe, kdyby se nahradily jednotným obrázkem podle druhu dokumentu. V MKP to vypadá např. takto: http://search.mlp.cz/cz/titul/age-ageing/500000371/

![obalky_no_image](https://cloud.githubusercontent.com/assets/11600358/10071808/0f4d88e6-62bd-11e5-81bf-a2fb80850cb9.png)

**Comment by paulusova** [comment]
Na tomto se pracuje, v další verzi by už ikony pro jednotlivé typy dokumentu měly být.
