### ISSUE TITLE
E-zdroje MZK - chybějící odkaz na dokument

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#27]
Při dohledání článku:
![e-zdroje_1](https://cloud.githubusercontent.com/assets/11600358/10071971/34f2eeb4-62be-11e5-8632-c3dafcc2dcc1.png)
Hledám v detailu záznamu odkaz, kudy se na něj dostanu:
![e-zdroje_2](https://cloud.githubusercontent.com/assets/11600358/10071983/4d4ba42e-62be-11e5-8649-d9c9093f310c.png)
a nenacházím:
![e-zdroje_3](https://cloud.githubusercontent.com/assets/11600358/10071989/56321406-62be-11e5-9432-393055d1f33c.png)

**Comment by PetraZabickova** [comment]
Toto je chyba, zdá se, že se nám linkování rozpadlo. Děkujeme za upozornění. Opravíme to.

**Comment by jrmeixner** [comment]
Pokouším se otestovat linkování u e-zdrojů do databází. Vycházím z toho, že jste vyzkoušeli indexaci exportu z SFX JIB pro MZK, takže "lovím" v e-zdrojích MZK :-). Bohužel ale vidím přesně to samé co kolega Vojtíšek - prázdné E-verze:-(. Přitom na screenshotu z Olomouce je vidět, že to asi fungovalo:-)
![scr_e-verze](https://cloud.githubusercontent.com/assets/15102976/10481477/169f3c98-7271-11e5-91c1-7b7d7d50a9a3.jpg)

**Comment by PetraZabickova** [comment]
Omlouváme se, rozbilo se nám to. 

Na vývojovém serveru již máme opraveno, veškeré opravy a novinky by se měli na betu dostat začátkem příštího týdne (tzn. do 20. října)
