### ISSUE TITLE
Responzivita pole pro hledání

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#28]
Chová se responzivní šablona na většině zařízení správně? Na okrajovém blackberry q10 se čtvercovým displejem se na většině stránek přizpůsobí správně (výsledky vyhledávání), na domovské obrazovce malinko ujíždí pole pro vyhledávání:

![img_20150924_115654](https://cloud.githubusercontent.com/assets/11600358/10072014/9df74b12-62be-11e5-9ca6-b40d1931f608.png)

**Comment by PetraZabickova** [comment]
Děkujeme za upozornění. Tohle nám uteklo. Opravíme.
