### ISSUE TITLE
Tlačítko pro zobrazení Shibboleth Assertions po přihlášení

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#29]
Má to nějaký význam pro testování? Pro uživatele potom asi příliš ne...
![shibb_assertions](https://cloud.githubusercontent.com/assets/11600358/10072112/54bc0a04-62bf-11e5-9560-be2ffa2cab52.png)

**Comment by paulusova** [comment]
má význam pro testování, časem ho odstraníme
