### ISSUE TITLE
Ikona a popisek typu dokumentu

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#30]
Jsem jediný, kterému "trhá oči" současné umístění ikony a popisku typu dokumentu umístěné vpravo? Často se tato informace umísťuuje do oblasti pod názvem a autorem, prípadně po obálku. Pokud se ovšem budou místo chybějících obálek používat ikony právě podle typu dokumentu, může to být poněkud divné.

**Comment by PetraZabickova** [comment]
Ano, v případě neexistující obálky se použije první ikonka typu dokumentu. 

Umístit ikonky a popisky pod název nebo pod obálku jsme zvažovali. Pod názvem nám to nepřipadalo dostatečně přehledné a pod obálkou byl problém s tím, že v případě více typů tento údaj zabral příliš moc místa. 

Jsme ale otevření další diskusi a budeme rádi za názory ostatních.

**Comment by Stoklasovab** [comment]
Kromě umístění je problém i kombinace plurálu (Knihy, Články) a singuláru (Elektronický zdroj), to je určitě třeba sjednotit.

Umístění probereme a uzavřeme na jednání 12.11.

**Comment by black23** [comment]
<img width="624" alt="screenshot at lis 12 11-05-19" src="https://cloud.githubusercontent.com/assets/5516936/11115635/4bdc0468-892d-11e5-8c36-472795531537.png">

**Comment by Stoklasovab** [comment]
Přesunout doleva, zarovnat pod text
