### ISSUE TITLE
Detail dokumentu: možnost řadit jednotky

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#31]
Zatím je záznamů o jednotkách málo, ale až jich bude více, mohlo by být užitečné mít možnost seřadit seznam například podle data, do kdy jsou půjčené a najít nejdříve dostupný.

**Comment by PetraZabickova** [comment]
V tuto chvíli zobrazujeme v detailu jednotky pouze od daného jednoho bibliografického záznamu. A to i  u sloučených (zdeduplikovaných) záznamů. Tzn. velké množství jednotek se zobrazuje hlavně u seriálů. Např. zde https://cpk-front.mzk.cz/Record/mzk.MZK01-000872211
V případě seriálů bychom mohli přidat filter na Roky vydání.

Sloučení všech jednotek do jednoho zobrazení se nebráníme. Stejně tak nalezení nějaké uživatelsky srozumitelnějšího způsobu, jak zobrazit pouze relevantní informace (ty dostupné, apod.) nebo jak jednotlivé údaje srozumitelně seřadit.

Doufáme, že získáme nějaká doporučení, jak se s problematikou vypořádat jako výsledek Uživatelského testování (MKP) a že toto řešení bude aplikovatelné a bude vyhovovat všem.

**Comment by jankanka** [comment]
Mozna jsem pesimista, ale domnivam se, ze takovych uzivatelu, kteri budou registrovani (a tim padem s sanci na vypujcku) ve vice nez 2-3 knihovnach, tzn. mohli by vybirat z dlouheho seznamu - mnoho nebude.

**Comment by black23** [comment]
@jankanka Zjevne si nerozumime. Opravdu se bude jednat spise o detail serialu a spise u velkych knihoven, ktere mohou mit od nekterych titulu mnoho jednotek. Takze se ctenarem to temer nema spojitost. 
Navic v mezicase se rozhrani v tomto ohledu vylepsilo. Nyni existuje roletka pro vyber instituce, takze se zobrazi jen jednotky, ktere ji prislusi. V dobe vytvoreni issue to tak nebylo a Pokud se titul byskytoval v nekolika knihovnach, tak byl seznam jednotek spojeny do jednoho detailu. Tim ten seznam mohl narust do velkych rozmeru. Da se tedy rici, ze kombinace roletky pro vyber instituce a filtr na roky vydani a svazek vec resi. Takze mozna muzeme sissue uzavrit. Pripadne to muzeme odlozit na pozdeji, az budeme mit zpetnou vazbu od prvnich uzivatelu verejneho pilotniho provozu.
<img width="941" alt="screenshot at cvn 07 21-03-57" src="https://cloud.githubusercontent.com/assets/5516936/15871224/c4adae72-2cf3-11e6-913b-3cd839e9906a.png">

**Comment by jankanka** [comment]
Ok, uz rozumim, omlouvam se.

**Comment by Stoklasovab** [comment]
Uzavrit jako vyresene.
