### ISSUE TITLE
Vymazání obsahu vyhledávacího pole jedním klikem

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#32]
Osobně bych ocenil existenci křížku, který po kliku vymaže aktuální obsah vyhledávacího pole.

**Comment by PetraZabickova** [comment]
To zní jako dobrý nápad, předpokládám, že by to asi využili hlavně uživatelé mobilních telefonů a tabletů.  

Pokud bychom ten křížek umístili přímo do vyhledávacího okna jako má např. www.seznam.cz, nedojde pak ale k zbytečnému zmenšení plochy pro zápis dotazu? 

Před případnou implementací bychom byli rádi za názory ostatních.

**Comment by Stoklasovab** [comment]
Probereme a uzavřeme na jednání 12.11.

**Comment by Stoklasovab** [comment]
OK, zkusit

**Comment by Stoklasovab** [comment]
Opravdu to tam už je :-)
![krizek](https://cloud.githubusercontent.com/assets/11761577/11130104/77c987ca-8983-11e5-98c4-e2be437d0356.jpg)

**Comment by zabak** [comment]
Ale funguje jen v Exploreru, takže rovnou hlásím bug :-)
