### ISSUE TITLE
Našeptávávání v pokročilém hledání

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#33]
Pokročilé vyhledávání by také mělo využívat našeptávání,  u autora, názvu. Velmi užitečné může být u předmětu, kde může pomoci člověku, který dost tápe. Zadáj jen část výrazu a hned vidí možnosti. Nevím ovšem, jak zásadní vliv našeptávání má na rychlost. Problematické může být také převedení formuláře do responzivního designu.

**Comment by PetraZabickova** [comment]
Našeptávat budeme i v pokročilém hledání, chtěli bychom ale nejprve, aby si nastavení vyhledávání sedlo a nemuseli jsme opakovaně provádět nové reindexace.

Jako neproblematičtější u responzivního designu vidím zobrazení hierarchických filtrů v pokročilém hledání. Je na zvážení zda by tyto filtery měli být hierarchické (např. město/instituce).
