### ISSUE TITLE
Nevýrazné označení možnosti rozbalit roletku pro výber knihovny

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#36]
Roletka pro výběr knihovny může některé uživatele mást, respektive nepochopí, že klikem mohou rozbalit a vybrat jinou knihovnu. Co coplit o barevký obdélníček např. s textem DOSTUPNÉ v X KNIHOVNÁCH a výraznou šipku dolů.
<img width="361" alt="screenshot at zar 25 20-22-31" src="https://cloud.githubusercontent.com/assets/5516936/10108771/44ef2a20-63c3-11e5-8040-5439cc59d08f.png">

**Comment by PetraZabickova** [comment]
Ano, souhlasíme, že stávající stav není úplně pochopitelný. Rádi bychom problematiku vyřešili rovnou komplexně, včetně otázky "interních duplicit" a otázky toho zda uživatelé očekávají, že v každé knihovně je trochu jiný záznam. Požadavek za zachování všech původních záznamů byl pro nás při realizaci portálu ale mandatorní. Budeme rádi také za názory ostatních.

**Comment by vojtisev** [comment]
Také souhlasím - roletku jsem zaznamenal až při zkoumání téhle issue. Vzhledem k tomu, že by to uživatele mělo vést k výpůjčce v té knihovně, kterou potřebuje, mělo by to být asi hodně výrazné.

Pro srovnání, stejná roletka (zdrojová knihovna) ve Finna:
![knihovny_drop_down_ finna](https://cloud.githubusercontent.com/assets/11600358/10218652/ca8a8dae-6838-11e5-87a8-0bfb07e0890b.png)

IMHO by to ale mohlo být v podstatě jako skladová lokace u webového srovnávače zboží, řešená ikonou (jako uživatele mě budou primárně zajímat dostupné zdroje):
![dostupnost_heureka](https://cloud.githubusercontent.com/assets/11600358/10218675/f1d7ebe0-6838-11e5-912b-f8d1c65cf550.png)

Asi bych se nebál místo drop downpoužít pop up okno, např.:
![dostupnost_alza](https://cloud.githubusercontent.com/assets/11600358/10218694/0d7a8f60-6839-11e5-9613-81a9e68d7a1d.png)

IMHO uživatele různé záznamy spíše zmatou, než aby to očekávali - detaily záznamu budou zkoumat pouze ve specifických požadavcích (citace).

**Comment by PetraZabickova** [comment]
V příští verzi bude přesunuto přepínání záznamů dle návrhu UX.
