### ISSUE TITLE
Nepřehledné Podobné jednotky

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#37]
Bylo by skvělé každý záznam nějk oddělit od dalšího. Co třeba nějaké pozadí střídané s jeho vynecháním. Předpokládám, že uživatelské testování upozorní na používání "knihovštiny", které běžný člověk nerozumí.

**Comment by PetraZabickova** [comment]
Děkujeme za upozornění.

**Comment by vojtisev** [comment]
Ano, MKP je pověřená web otextovat - konkrétní návrhy jsou samozřejmě velmi vítané.

**Comment by PetraZabickova** [comment]
Ano, konkrétní návrhy jsou vítané :-).
