### ISSUE TITLE
Výsledky vyhledávání a souborný katalog

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/CPK#38]
Souborný katalog by neměl být vidět v tom zkráceném seznamu dvou institucí ve výsledcích vyhledávání (při anonymním přístupu) u každého záznamu. Měly by tam být knihovny plně zapojené do CPK a jen pokud takové nejsou, měl by být vidět SK.

**Comment by Stoklasovab** [comment]
Ano, to, co navrhuje Petr, je rozumné

**Comment by PetraZabickova** [comment]
Budeme rádi za názory ostatních. V průběhu poslední diskuse o tom, jak zapojit Souborný katalog se objevil i názor, že by Souborný katalog měl být naopak jako první. Sami bychom jej nejraději umístili až za všechny zapojené knihovní katalogy tzn. na konec a je otázkou zda před nebo za Českou národní bibliografii.

**Comment by zabak** [comment]
Mimochodem, není to tak, že celá Česká národní bibliografie je i v SK? Nebo je tam jen její část? A ta část, která v SK případně není: jde o knihy, které má nějaká knihovna? Nebo jen knihy o kderých se ví, že asi v minulosti vyšly, ale nikdo je nemusí mít?

**Comment by Stoklasovab** [comment]
Svuj nazor jsem napsala. Jednoznačně na konec, ale asi před ČNB. B

**Comment by vojtisev** [comment]
Souhlasím s umístěním SKC na konec. Detaily k ČNB bohužel neznám.

**Comment by PavlinaDolezalova** [comment]
SK před ČNB. Obé až na konec pouze v případě, že si je vědomě nevyberu v pokročilém vyhledávání - v tomto případě by mohly být záznamy zamíchané mezi všechny výsledky?

**Comment by zabak** [comment]
SK na konec za jednotlivé instituce
