### ISSUE TITLE
Umístění odkazu Zobrazit další knihovny

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/CPK#39]
Odkaz Zobrazit další knihovny ve výsledcích vyhledávání by měl být umístěn zarovnaný doprava pod těmi dvěma zobrazenými knihovnami, jako pokračování toho seznamu. Jinak si člověk nevšimne, že je to nejen v těch dvou zobrazených ale v řadě jiných knihoven. Jiné řešení by mohlo být nahradit seznam dvou knihoven něčím jako "Moravská zemská knihovna a 12 dalších knihoven". Vyjde to skoro nastejno a pro nepřihlášeného uživatele to uspoří místo na obrazovce. Neříkám jak to má být u přihlášeného uživatele. Prosím o diskusi.

**Comment by PetraZabickova** [comment]
Je otázkou zda zobrazování seznamu knihoven na tomto místě vůbec mít, protože to zabírá docela dost místa. Na druhou stranu si myslíme, že ano, protože se pak s výsledky dotazů lépe pracuje. Budeme rádi za názory ostatních.

**Comment by vojtisev** [comment]
Současné nastavení se mi zdá funkční - právě to zarovnání na střed tím, že není ve stejné linii jako vše ostatní, správným způsobem "trčí". Funguje to také na menších obrazovkách:

![vysledky_vyhledavani_iphone](https://cloud.githubusercontent.com/assets/11600358/10552134/faea54aa-7451-11e5-8614-6385705f981b.png)

**Comment by Stoklasovab** [comment]
Probereme a uzavřeme na jednání 12.11.

**Comment by PetraZabickova** [comment]
Zadavatel souhlasí se stávajícím řešením.
