### ISSUE TITLE
Data - interpretace odkazů do K4 NK vs. MZK

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/CPK#40]
https://beta.knihovny.cz/Record/svkhk.HKA01-000830528 - e-verze

jedná se o odkazy na stejnou knihu do Krameria NK a MZK, jsou ale zcela rozdílně označeny. Tuším proč to tak zatím je, ale měli bychom to pokud možno sjednotit, protože takto duplicitních e-verzí bude přes 100.000.

**Comment by PetraZabickova** [comment]
Duplicitní odkazy z různých knihoven jsou nyní již odstraňovány. V tomto případě se jedná o dva různé odkazy. Jeden do Kraméria Národní knihovny a druhý do Kraméria MZK. Vzhledem k tomu, že se jedná o autorsky chráněnou publikaci, nedojde při odstranění jednoho z odkazů k znemožnění uživatelů druhé knihovny získat dokument elektronicky v jeho knihovně?

**Comment by zabak** [comment]
Dojde, musí tam být oba odkazy. Šlo mi o to, že u každého z nich jsou různé informace o dostupnosti a popisek co je to za odkaz. Navíc fakticky jde o geograficky podmíněnou dostupnost - musím do knihovny.

**Comment by PetraZabickova** [comment]
Jeden odkaz je získán přímo z Kraméria. Druhý odkaz byl přidán z pole 856. V tuto chvíli nedokážeme správně a dostatečně analyzovat obsahy všech polí 856. Nesou příliš nesourodé informace na které se nelze zcela spolehnout. Tento případ je poněkud specifický, protože se jedná o NDK, ještě se nad problematikou zamyslíme.

**Comment by zabak** [comment]
Tohle by mělo být řešeno tím že se sklidí ČDK, z toho by měly být odvozeny oba linky do Krameria. Ale pak tam bude duplicitní link z bibliografického záznamu (nebo z několika, vedoucích do stejného krameria, hlavně u volných dokumentů).

**Comment by PetraZabickova** [comment]
Ano, jakmile sklidíme ČDK nebo kompletně všechny Kramérie. Budeme moci definitivně vypustit odkazy do nich z pole 856.
