### ISSUE TITLE
lepší text popisující blokaci uživatele

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/CPK#42]
Když se přihlásím (svým účtem MZK), skočí beta do profilu uživatele, kde mi v oranžovém obdélníku zobrazí "Block 70". Chtělo by to zobrazit textový popis problému.

**Comment by PetraZabickova** [comment]
Jedná se o zobrazení textu delikvence pro Alephovské knihovny. Zobrazuje se pouze takový text delikvence u kterého CPK bude znát překlad, což řeší jak samotný překlad, tak to, že některé delikvence knihovny používají pouze z interních důvodů a nemají význam pro uživatele. Na způsobu předávání mapování mezi knihovnami a CPK se pracuje.

Opraveno. Bude zveřejněno v příštím verzi.
