### ISSUE TITLE
umístění historie vyhledávání

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#43]
Chybi mi moznost jak se jednoduse dostat se zpatky na posledni vysledky hledani - historie vyhledavani je dobra vec, ale na prvni pohled jsem si ji vubec nevsiml. Takze bych odkaz historii vyhledavani posunul nekam vice na oci - treba nekam vpravo od vyhledavaciho boxu, plus nejaky odkaz na posledni hledani. 

navrhuje Filip Kříž

**Comment by PetraZabickova** [comment]
Souhlasíme s tím, že současné umístění je poněkud schované.

**Comment by jrmeixner** [comment]
Souhlasím, stejný problém se týká lišty "Vyhledávací nástroje: RSS - Poslat emailem - Uložit hledání", která je až pod stránkováním výsledků. Co jí přesunout vpravo nahoru nad fasetový blok?

**Comment by vojtisev** [comment]
Co takhle?

![vyhledavaci_nastroje](https://cloud.githubusercontent.com/assets/11600358/10552324/71a97f70-7453-11e5-9d12-9aca9dfb7510.png)

**Comment by PetraZabickova** [comment]
Tohle byla původní varianta, která ale byla docela nepřehledná a pro "běžného" nepokročilého uživatele matoucí. Pokud bude panovat shoda, tak přesuneme.

**Comment by jrmeixner** [comment]
Za sebe bych hlasoval pro přesunutí nad výsledky (tedy asi původní variantu). V databázových rozhraních (ScienceDirect, Proquest...) umisťují odkazy na služby (jako poslat emailem, uložit hledání, RSS) také přímo nad výsledné záznamy nebo vpravo nahoru.

**Comment by Stoklasovab** [comment]
Probereme a uzavřeme na jednání 12.11.

**Comment by Stoklasovab** [comment]
Poslat e-mailem, uložit výsledky
