### ISSUE TITLE
Dostupnost časopisu

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#44]
Zatim tam chybi nejake souhrnne informace a navigace - jake roky, rocniky/cisla jsou dostupne. Je nutne zjistovat konkretni dostupnost jednotek/holdingu az pote, co si uzivatel vybere, jaky rocnik/cislo potrebuje. Aktualne se stahuje dostupnost pro vsechny holdingy casopisu, coz je problem - zatezuje to NCIP server(y) knihoven a trva to strasne dlouho a vetsinou to ani nedobehne.

navrhuje Filip Kříž

**Comment by PetraZabickova** [comment]
Určitě chystáme přidat fitr na rok a v případě velkého množství jednotek zobrazit defaultně pouze nejnovější ročník. Pomohlo by to?

**Comment by PavlinaDolezalova** [comment]
Starší ročníky by tedy byly schované pod odkazem?

**Comment by PetraZabickova** [comment]
Dá se to tak nazvat, respektive byly by schované pod filtrem.
