### ISSUE TITLE
Popisky lokací/oddělení

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#45]
Jednotky - Oddeleni - chtelo by to od knihoven ziskat nejake kodovniky s uzivatelsky privetivymi popisky jejich lokaci, tedy napr. 001=Studovna ... a ty pak zobrazovat misto kodu ziskanych pres OAI-PMH. Mozna by stalo za to poladit specifikaci pro OAI-PMH metadata.

navrhuje Filip Kříž

**Comment by PetraZabickova** [comment]
Již máme nachystáno mapování na naší straně pro případy, kdy knihovna neumí zasílat hodnoty a posílá pouze kódy. V tuto chvíli hledáme nejvhodnější způsob pro přenos informace mezi knihovnou a portálem.
