### ISSUE TITLE
Seznam svazků u periodik - řazení dle roku

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/CPK#46]
Stavky periodik jsou nyní řazeny náhodně. Chtělo by to podle roku vzestupně nebo sestupně.

**Comment by PetraZabickova** [comment]
Chystáme zprovoznění filtru periodik na Rok vydání, kdy přímo budeme zobrazovat pouze nejnovější ročník s možností volby jiné. Pomůže to?

**Comment by zabak** [comment]
Ne, i tak by mělo být řazeno, protože může být za rok víc svazků a ty by měly být pokud možno správně seřazeny. To může být problém např. u 12 svazků za rok, mělo by se používat numerické řazení, ne textové (bude se řadit podle řetězců typu "1970 1", "1970 2",...,"1970 10"...
