### ISSUE TITLE
Přidání uvozovek

### ISSUE THREAD

**Issue by Stoklasovab** [moravianlibrary/CPK#48]
Když chci pokračovat ve vyhledávání podle některého z témat zobrazeného v záznamu a ťuknu na ně, přidají se do dotazu uvozovky a nic se nenajde

**Comment by PetraZabickova** [comment]
Děkujeme za upozornění, již o tom víme a opravujeme.  viz https://github.com/moravianlibrary/CPK/issues/21

**Comment by Stoklasovab** [comment]
Aha, musím si podrobněji číst, na čem se už pracuje :-) B
