### ISSUE TITLE
další úprava rešerše v historii vyhledávání

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#49]
Bylo by mozna dobre, kdyz mam v historii hledani nejakou "vypiplanou" resersi, abych si ji zase mohl otevrit v pokrocilem hledani a dal upravit, ulozit atp.

navrhuje Filip Kříž

**Comment by vojtisev** [comment]
Funkcionalita uložených hledání a ukládání jejich historie toto nepokrývá?

**Comment by paulusova** [comment]
Ne, z historie vyhledávání se dostanu pouze na stránku s výsledky vyhledávání, ne na úpravu řešerše v pokročilém vyhledávání.
