### ISSUE TITLE
faseta Typ dokumentu v Pokročilém vyhledávání

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#5]
seřadit dle relevance ( např. knihy, mapy, audio, video, hudebniny)

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
Prosíme o specifikaci  pořadí. Děkujeme.

**Comment by PavlinaDolezalova** [comment]
Alespoň knihy jako první a ostatní zatím dle četnosti výskytu? Předpokládám, že uživatelé hledají nejčastěji knihy.
