### ISSUE TITLE
Ve výpůčkách se zobrazuje jen název dokumentu

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#51]
Zcela schází informace o autorovi atp. Uživatelé by mohlu ocenit také odkaz do katalogu CPK, pokud by chtěli zjistit o jaký dokument jde. Skvělé by bylo zobrazovat i obálku. Při větším počtu výpůjček by měl uživatel mít možnost řadit seznam podle různých parametrů.
- datum vrácení
- autor (abecedně, ASC/DESC)
- název (abecedně, ASC/DESC)

Skvělá by bylo možnost barevně označit prošlé výpůjčky (nevrácené včas). Ty by ve výchozím řazený bylo užitečné mít nahoře a doplněny o textovou poznámku typu "Již mělo být vráceno"

**Comment by PetraZabickova** [comment]
Děkujeme za připomínku. Ráda bych problematiku rozdělila do dvou bloků:

1. nezobrazuje se informace o autorovi
2. manipulace ze seznamem výpůjček (jejich řazení)

U bodu 1, se jedná o otázku vyřešení zapojení konkrétní knihovny/systému. U některých knihoven máme i autora. Prověříme, kde je problém.

Bod 2 považuji za návrh na vylepšení.

**Comment by paulusova** [comment]
Na chybějící informace o autorovi se podíváme, pro řazení výpůjček jsem založila novou issue https://github.com/moravianlibrary/CPK/issues/78
