### ISSUE TITLE
Historie výpůjček v detailu čtenáře

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#53]
Už o tom proběhla diskuze, ale nedá mi to. Věřím, že i uživatelské testování potvrdí, že uživatelé na této funkcionalitě budou trvat. V běžném provozu je jeden z nejčastějších dotazů "už jsem tuto knihu měl půjčenou". S tím souvisí i označování položek, které uživatel měl, přímo ve výsledcích hledání. Debatujme, prosím o podpoře této funkcionality, kterou osobně považuji za nezbytnou.

**Comment by zabak** [comment]
Jak by mělo být označované u periodik a vícesvazkových děl? Četl jsem první díl nebo ročník 1970. Ale ne další díly nebo ročníky. Nebo semafor? Muselo by se to dotahovat přes API (si myslím) takže by to tam nebylo hned ale až se zpožděním a mohl by to být další poměrně vylký nápor na servery.

**Comment by black23** [comment]
Ano, periodika i vícesvazky jsou složitý problém. V rámci jedné knihovny to jde rozlišit na úrovni například jednotky za pomocí čárového kódu. Ale při spojení údajů z více knihoven to může být o dost složitější. Stejně jako to označení v katalogu.

**Comment by PetraZabickova** [comment]
U Alephu můžeme dotáhnout přes API, ale je to dost velký nápor na server v případě uživatelů, kteří těch výpůjček mají hodně (až tisíce). 

V případě NCIPu se jedná o funkčnost nad dohodnutý rámec. Tzn. dodavatelé knihovních systémů s tím nepočítají a budou chtít v případě zprovoznění za vývoj zaplatit. Asi bychom mohli bychom tuto funkci (seznam historie výpůjček) nabídnout pouze knihovnám, které to umožňují. Tzn. nefungovala bych konzistentně všem uživatelům ale pouze některým knihovnám.

**Comment by black23** [comment]
Zvážíme tuto funkcionalitu implementovat v Koha. Přímo ve VuFindu ji máme a celkem funguje, byť superrychlé to není. Řešit by to mohlo nové API, které se vyvíjí.

**Comment by Stoklasovab** [comment]
Probereme, ale nevím, zda uzavřeme na jednání 12.11. Podívejte se, prosím, na poslední Petřin komentář k této věci. Nabízet něco pouze uživatelům některých knihoven by asi nebylo dobré. Vlastně se na tom shodla i Rada CPK při diskusi, zda pustit CPK do provozu s tím, že u některých knihoven bude k dispozici lepší funkcionalita (možnost vidět dostupnost dokumentu atd.) a u některých horší.

**Comment by black23** [comment]
Za sebe říkám, že bychom se v rozsahu funkcionalit něměli spokojit s tím, co umí nejméně připravený knihovní systém/knihovna. Věřím, že jen ukazování toho, že jsou některé věci řešitelné je motivační.Stejně vytváření jakéhosi konkurečního prostředí. Ale ano, je to nad rámec dohodnutých věcí. Pokud však prostudujeme výsledky uživatelského testování, zaznívá tam dporučování, nabízení podobných titulů nebo od stejného autora. A to se bez historie dá provést jen velmi těžko. A požadavky cílové skupiny bychom měli brát velmi vážně.

**Comment by zabak** [comment]
Individualizované doporučování konkrétnímu uživateli na základě jeho výpůjční historie je jediná oblast, kde je historie jeho výpůjček nutná (a pak samotné zobrazení historie výpůjček danému uživateli). Ostatní požadavky lze realizovat na základě jiných údajů. Nejsem si ale jistý, že je možné doporučené knihy "vypočítat" v reálném čase na základě údajů stažených přes API, zvlášť pokud by těch výpůjček v historii bylo hodně. Možná by byla na toto lepší nějaká forma sklízení a indexace, ale to s sebou nese další problémy.

**Comment by Stoklasovab** [comment]
Půl roku testovat na systémech, které to umí, pak rozhodnout, zda pustit/nepustit do ostrého provozu.

**Comment by PetraZabickova** [comment]
Historie bude implementováno pro Aleph a respektive pro Českou Třebovou jakmile bude schopna posílat údaje přes NCIP.

Individuální doporučování analyzujeme.

Navrhuji rozdělit issue 53 na dvě části.

**Comment by paulusova** [comment]
issue rozdělena na historii a doporučování
