### ISSUE TITLE
Formulář pro vytvoření rezervace

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#56]
Z uživatelského hlediska by v tomto formuláři mělo bát minimálně:
- co rezervuji (název, autor, typ dokumentu)
- kde to rezervuji (název instituce)
- popis toho, co vlastně dělám a co bude po odeslání formuláře následovat

![vytvoreni_rezervace](https://cloud.githubusercontent.com/assets/5516936/10245388/60f18a58-6907-11e5-8d75-c26f5e6c78d2.jpg)

Mírně matoucí formulace: Komentáře a oblíbené:

Nástin:
Rezervujete si knihu název, autor.
V Městské knihovně Dolní Horní
Pokud nám chcete ke své rezervaci sdělit další informace, napište je zde:

Dokument potřebuji nejpozději do: vyplňte datum

Odesláním rezervace souhlasíte s podmínkami služby. Jakmile bude dokument připravený k vyzvednutí nebo doručení, bude Vás informovat pracovník vaší knihovny.

**Comment by PetraZabickova** [comment]
Děkujeme za návrh změny. Budeme modifikovat.

**Comment by vojtisev** [comment]
Pro inspiraci připojuji screenshot rezervačního okna z MKP; 

![rezervace_mkp](https://cloud.githubusercontent.com/assets/11600358/10547130/c2cd9f42-7432-11e5-8f0f-d55a6deb2f10.png)

z feedbacku našich uživatelů bychom doporučovali celý proces rozkouskovat do jednotlivých kroků (aka instalace programu) - informací, které jsou v rezervačním okně je příliš a uživatel se v tom těžko orientuje. Kroků bude hodně (výzva k přihlášení nepřihlášeného uživatele, výběr knihovny / pobočky, výběr způsobu doručení apod.).

**Comment by PetraZabickova** [comment]
Úprava rezervačního / objednacího okna dle návrhu black23 můžeme udělat relativně snadno. Pokud bychom měli celý způsob objednávání / rezervace řešit podobným způsobem jako v MKP, tak  takový zásah by nebyl úplně snadný. Zamyslíme se nad tím.

**Comment by Stoklasovab** [comment]
Probereme a uzavřeme 12.11.

**Comment by PetraZabickova** [comment]
Vzhledem k tomu, že v různých knihovnách je podporováno bud pouze objednávání na konkrétní jednotku nebo objednávání pouze na titul, budeme schopni podporovat obě varianty.  Pokud bude expertní skupina souhlasit. Uživatel tedy nebude mít zcela shodné chování u všech knihoven.

**Comment by Stoklasovab** [comment]
Obě varianty
