### ISSUE TITLE
tlačítko navrhnout k digitalizaci

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/CPK#58]
Doplnit (ale nějak systémově, nespěchá) tlačítko "navrhnout k digitalizaci" jako máme ve vufindu. Ale s drobným rozdílem: pokud nějakou knížku navrhnu, měla by se dostat do mých oblíbených, abych se k ní mohl vrátit.

**Comment by PetraZabickova** [comment]
Prosím o upřesnění požadavku. Návrhnout k digitalizaci komu a čeho?  Jedná se o implementaci funkce, kterou používá i někdo jiný než MZK? Bude MZK sbírat požadavky celého CPK na digitalizaci nebo jde o sběr požadavků pouze u záznamů MZK pro MZK?

**Comment by zabak** [comment]
U knih které má MZK ve fondu můžeme přijímat návrhy na digitalizaci od kteréhokoli přihlášeného uživatele.

**Comment by vojtisev** [comment]
Pro MKP platí také výše uvedené - digitalizaci na zakázku provádíme u volných děl:

http://www.mlp.cz/cz/sluzby/digitalizace-na-zakazku

Možná by mohl uživatel vybírat ze seznamu knihoven, které tuto služby poskytují a následně být přesměrován na objednávkový formulář dané knihovny?

Celkově nemyslím, že by to mělo za nás velkou prioritu, ale určitě se tomu nebráníme.

**Comment by PetraZabickova** [comment]
Díky za informaci. Digitalizaci na zakázku nabízejí i jiné knihovny (například službou EOD), součástí procesu zapojování bude. Návrh k digitalizaci je naopak služba, kterou poskytuje MZK zadarmo a zdigitalizovaný dokument je následně dostupný přes digitální knihovnu knihovny (v případě chráněných dokumentů pouze z budovy knihovny). 

V tuto chvíli mapujeme všechny alternativy těchto a podobných služeb.

**Comment by zabak** [comment]
Bude se řešit v návaznosti na zavedení služby Získej

**Comment by xmorave2** [comment]
V budoucnu bychom to rádi řešili. Ale bude to ještě na další diskusi.
