### ISSUE TITLE
Dostupnost článků

### ISSUE THREAD

**Issue by Stoklasovab** [moravianlibrary/CPK#60]
U článků, kde je dostupný plný text, je uvedena přístupnost neznámá. Ta je barevně výrazná. Otázka je, zda to uživatele neodradí a zda každého napadne kliknout vedle na méně výrazný odkaz na plný text. Neměl by být odkaz na plný text přímo u přístupnosti, třeba pod online nebo něco podobného?

**Comment by PetraZabickova** [comment]
Toto není problém pouze u článků, ale obecně u té části odkazů, které se tvoří s pole 856. 

Neznámá dostupnost znamená, že nejsme schopni zaručit (nemáme pod kontrolou) to, kam odkaz vede a zda bude fungovat. Protože narozdíl od linků získaných z linkserverů nebo informací ze sklizených záznamů digitálních knihoven, tady pouze odhadujeme. Tyto odkazy navíc mohou ale nemusí fungovat pro uživatele jiných knihoven než té, která záznam vytvořila.

Zápis tohoto pole a jeho obsah je v různých knihovnách tak různorodý, že se nemůžeme spolehnout na obsah podpolí, indikátory.

Samotný zobrazovaný text můžeme lehce upravit a budeme rádi za návrhy jak.  Spolehlivost odkazu ale není zdaleka 100% a myslíme si, že by bylo vhodné uživatele upozornit, že bohužel existuje velká pravděpodobnost, že kliknutím na odkaz, plný text nezíská.

**Comment by Stoklasovab** [comment]
Jasně. Ale možná by od přístupnosti mohla vést v případě dostupnosti plného textu alespoň nějaká šipka nebo jiné upozornění, aby si toho někdo všimnul, Asi typická reakce ne neznámoupřístupnost je jít pryč a nezkoumat okolí.

**Comment by black23** [comment]
Co tedy doplnit o nějakou motivační textaci typu "Pokusit se získat plný text" nebo něco podobného?

**Comment by jrmeixner** [comment]
Neznámá dostupnost pro odkazy s pole 856 je na místě, těžko se dá garantovat. Variabilita odkazů bude obrovská, knihovny mohou mít odkazy na dokumenty lokalizované na své institucionální profily v koncových databázích - takže se k dokumentu dostanou jen registrovaní čtenáři dané knihovny přes vzdálený přístup nebo přímo z IP adres knihovny. "Trvanlivost" odkazů v čase bývá také problém. Z tohoto pohledu jsou odkazy získané z linkserverů přesnější (kdo co má dostupné) a spolehlivější (odkazy v čase). Navíc při překryvech titulů v databázích často nabízejí více cest ke koncovému dokumentu - př. stejný článek dostupný v EBSCU, Proquestu nebo ScienceDirectu. Tato variabilita se při příp. technických problémech nativních rozhraní může hodit.

**Comment by Stoklasovab** [comment]
Vyuziti linkserveru jsem automaticky predpokladala vsude, kde je to mozne, tim se vysledek hodne zpresni.

**Comment by vojtisev** [comment]
Souhlasím s black23 - přidání motivační textaci s podmínkou. Když uživatelům webové odkazy nabízíme, nemůžeme zároveň dělat, že tam vlastně nejspíš nejsou. Musíme být připraveni ve uživatelům případně v rámci podpory odpovídat ve smyslu toho, co píše Lenka.

**Comment by Stoklasovab** [comment]
OK, pobídka ke získání s vyjádřením určité míry nejistoty typu Zkuste získat ... je dobrý nápad
