### ISSUE TITLE
Nalezeno v těchto institucích

### ISSUE THREAD

**Issue by Stoklasovab** [moravianlibrary/CPK#61]
Nalezeno v těchto institucích se objeví např. i u Výběru článků v českých novinách, časopisech a sbornících a to není instituce. Nebylo by lepší něco jako Nalezeno v: nebo Nalezeno zde: ?

**Comment by PetraZabickova** [comment]
Děkujeme za návrh. Zvážíme jej. Hlavní otázkou je, zda vůbec tuto informaci zobrazovat, vzhledem k tomu, že v uživatelské testování se ukázalo, že tuto informaci uživatelé nepotřebují.

**Comment by Stoklasovab** [comment]
Ona je otazka, jak a komu byl polozen dotaz.
