### ISSUE TITLE
Barvy

### ISSUE THREAD

**Issue by Stoklasovab** [moravianlibrary/CPK#62]
Nebylo by možné použít pro červené hlášky "portálovou" červenou? Takto se to dost tluče.
![barvy](https://cloud.githubusercontent.com/assets/11761577/10288395/e4e28c02-6b98-11e5-8d3a-82ba87d44364.jpg)

**Comment by zabak** [comment]
Otázka je, jestli je dobrý nápad mít ten portál celý v červené, protože pak nejsou vidět chybové hlášky :-)

**Comment by jrmeixner** [comment]
Když diskutujeme o červené barvě - nebylo by lepší kdyby označení statusu "Vypůjčené" změnilo barvu ze zelené právě na červenou. Logiku mi dává "semafor":
Vypůjčené - červená
Rezervace - žlutá/oranžová
Dostupné - zelená

**Comment by PetraZabickova** [comment]
"Semafor" opravujeme.

**Comment by vojtisev** [comment]
Portálovou červenou bych používal opravdu jenom v hlavičce a patičce, abychom uživatele nemátli.

Co takhle?

![barvy_alert](https://cloud.githubusercontent.com/assets/11600358/10551170/c559cc0e-744b-11e5-8e9b-1cfa71e937a2.jpg)

Použil jsem tohle rozvržení:
http://paletton.com/#uid=35o0u0kw0FGjOL6pxHzF2tOGln8

**Comment by Stoklasovab** [comment]
Semafor ano, změnu barvy na jednání 12.11. zřejmě neuzavřeme. Expertní tým může vyslovit názor na to, zda základní barvu podržet nebo změnit, ale záleží na výsledcích práce grafiků (projekt MKP v letošním roce) a změna barvy je více politickou než expertní věcí, takže spíš téma pro Řídicí výbor CPK s podklady MKP v ruce.

**Comment by PetraZabickova** [comment]
Již není relevantní.
