### ISSUE TITLE
Titul stánky není konzistentně textovaný a neodpovídá menu

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#65]
Stránka pojmenovaná Vaše rezervace, menu Rezervace a objednávky v sekci Můj účet.
![vase](https://cloud.githubusercontent.com/assets/5516936/10387089/87dd47fe-6e5e-11e5-8d74-4b16a0cf29cf.jpg)

**Comment by matussabik** [comment]
Opravené.
