### ISSUE TITLE
S ohledem na výsledky uživatelského testování zvážit přesun menu vlevo

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#66]
Co přehodit menu a fasety na levou stranu? Mnohé studiue ukazují, že nejviditelnější je levá horní  až střední část obrazovky a nejdůležitejší informace a prvky mají být umístěny do tohoto prostoru. Co o tom řeklo testování CPK?
![vysledky_vyhledavani_-_2015-10-09_09 03 48 png](https://cloud.githubusercontent.com/assets/5516936/10387812/be9dd9c4-6e64-11e5-9440-43c56de405de.jpg)

**Comment by PetraZabickova** [comment]
Z výsledků uživatelské testování vyplynulo, že fasety nejsou vůbec potřeba. Případně je možno je nahradit filtrovací funkcí, která bude umístěna v horní části obrazovky. 

Se úplným zrušením faset nebo s jejich přesunutím do horní části obrazovky, ale MZK nesouhlasí a budeme v tomto případě čekat na shodu v názorech ostatních zúčastněných stran.

**Comment by black23** [comment]
S rušením faset vyjadřuji také nesouhlas :-) Přesun na druhou stranu navrhuji prodiskutovat.

**Comment by Stoklasovab** [comment]
Take jsem proti zruseni faset a libil by se mi jejich presun vlevo.

**Comment by HankaHornychova** [comment]
Jsem proti zrušení faset.
Filtr v horní části obrazovky je možné přidat i při zachování faset. Třeba filtr pro dostupnost.
Fasety na levé straně by se mi líbily.

**Comment by vojtisev** [comment]
Fasety určitě nechat, při očekávání jejich využití bychom měli zůstat realističtí. Vnímám to jako nedílnou součást knihovního katalogu. Ještě k uživatelskému testování - probíhalo formou empatických rozhovorů, tj. neprobíhalo zatím testování přímo bety. Změny podobného charakteru bychom mohli během pilotního provozu předložit uživatelům metodou A/B testování, v tuto chvíli mi to nepřijde klíčové.

**Comment by Stoklasovab** [comment]
Probereme a uzavřeme na jednání 12.11.

**Comment by PavlinaDolezalova** [comment]
Fasety zachovat. Mohl by si po přihlášení uživatel umístění faset (levá/pravá strana) volit samostatně v rámci svého konta?

**Comment by Stoklasovab** [comment]
Autor, název, téma jsou hlavní požadavky uživatelů prověřené mnoha zahraničími průzkumy řádově většího rozsahu, než ten náš. Ještě tam občas figuruje rok, nakladatel ne. Při testování, kde jsme byla, se nakladatel neobjevoval a navíc je zde problém s jeho neautoritní podobou.

**Comment by paulusova** [comment]
Máme přichystány prostředky pro modifikaci fasety Nakladatel. Byli bychom schopni různé zápisy sjednotit, je na zvážení, jestli tyto modifikace budeme dělat, jedná se o velké množství manuální činnosti, kdy je potřeba nejednotným formám přiřadit jednotnou podobu, která bude při indexaci nahrazovat všechny ostatní. V případě nejednotného zápisu nebo zkratek se dá sice snadno najít jednotná forma, ne vždy je to ale tak jednoduché, zvláště pokud dochází ke změnám jména nakladatelů. Nebudeme schopni nahradit autoritní bázi, pouze sjednocení zápisu. Pro představu, v tuto chvíli máme si 800 000 různých zápisu nakladatelů.

**Comment by Stoklasovab** [comment]
Přesunout vlevo
