### ISSUE TITLE
Faseta Žánr

### ISSUE THREAD

**Issue by jrmeixner** [moravianlibrary/CPK#67]
Pokud zadám "beletristický" dotaz tak to žánru odpovídá (detektivní povídky, romány pro ženy...) ale pokud  zadám "akademický" dotaz tak to sedí spíš na druh dokumentu (monografie, sborníky, elektronické knihy). Co jí přejmenovat?

**Comment by Stoklasovab** [comment]
Zanr asi bude zajmavy spis pro beletristicke dotazy a tam stavajici pojeti vyhovuje

**Comment by vojtisev** [comment]
Popravdě se mi žánr ještě plete dohromady s fasetou "obor" (je to dokonce synonymum) a "téma".

**Comment by PetraZabickova** [comment]
Vycházeli jsme z podkladů (konkrétně Projektového záměru 4), ale nemáme problém s tím, modifikovat dle nějaké specifikace.

**Comment by Stoklasovab** [comment]
Probereme a uzavřeme na jednání 12.11.

**Comment by Stoklasovab** [comment]
Prosím členy expertního týmu - koukněte před jednáním 12.11, do Projektového záměru verze 4, příloha 6 na s. 125, zdá se mi vyhovující a použili i v MZK http://www.knihovny.cz/wp-content/uploads/2012/08/KNIHOVNY-CZ_Projektovy-zamer_verze-4.0_2014_10_03_rev.docx

**Comment by Stoklasovab** [comment]
V praxi je tam pěkný pall mall
![zanr](https://cloud.githubusercontent.com/assets/11761577/11040186/4bdffd8a-870b-11e5-81d0-30022a9d58a3.jpg)

**Comment by PavlinaDolezalova** [comment]
Pokud si dobře pamatuji, tak fasetu žánr požadovali osamostatnit zástupci zejména bývalých okresních knihoven, jejichž čtenáři jsou na tuto položku zvyklí. Žánr by měl být generován z 655 a 008 [22,23] u vybraných typů. Faseta obor je čistě konspekt (072) - také byl požadavek na osamostatnění. Faseta "téma" je zřejmě to samé co v proj. záměru "Předmět", tj. většina 6XX. Takže co s žánrem? Byla bych pro jej vsunout do jedné ze zbývajících faset, ovšem kam aby se vlk nažral a koza zůstala celá? Tak jsme to i nakousli s týmem CPK v květnu t.r.

**Comment by Stoklasovab** [comment]
Já si stále myslím, že žánr je něco jiného než téma (předmět) nebo obor (zastřešení předmětů-konspekt) a že vsunutím vznikne ještě větší guláš. Ale probereme zítra.

**Comment by paulusova** [comment]
V nějaké fázi nám se nám rozbil překlad, "téma" má opravdu být "předmět", opravíme.

**Comment by Stoklasovab** [comment]
Žánr ponechat samostatně, umístit dolů, analýza využití, směřovat k formalizaci
