### ISSUE TITLE
Testovací uživatel

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#68]
O možnostech testovacích účtů / uživatelů jsme mluvili na schůzce 7. října. Chystá se něco takového?

**Comment by PetraZabickova** [comment]
Můžeme Vám vytvořit testovacího uživatele v MZK. Bohužel většina zapojovaných knihoven si klade podmínky nevyužívat zbytečně testovací uživatele k objednávkám a rezervacím, protože je systém napojený na reálné živé systémy.

**Comment by PetraZabickova** [comment]
Ale ano pro MZK přichystáme.

**Comment by vojtisev** [comment]
Díky - zjistím, jaké jsou v tomto směru možnosti testovacího serveru pro uživatele MKP.
