### ISSUE TITLE
Hledání podle viz odkazů autoritních záznamů

### ISSUE THREAD

**Issue by lenkamaixnerova** [moravianlibrary/CPK#69]
Bylo by možné pro lepší vyhledávání hledat i podle viz odkazů autoritních záznamů, a to jak jmenných tak věcných? Např. při zadání hyperkinetický syndrom je nalezeno 7 záznamů, hyperkinetická porucha 28, adhd 299, přitom se jedná o synonyma, při zadání dotazu jiřina prekop je výsledek 95 a při zadání jiřina prekopová 57. Případně nabídnout rozšíření dotazu o záhlaví autoritního záznamu?

**Comment by mjtecka** [comment]
Synonyma by mělo být možné zpracovávat - dělalo se to třeba v NTK s PSH:
https://github.com/NationalTechnicalLibrary/VUFIND-1/blob/master/solr/biblio/conf/synonyms.txt

Pak by to fungovalo tak, že se při třeba při zadání dotazu "adhd" vyhledává také "hyperkinetická porucha" a "hyperkinetický syndrom".

S jedním slovníkem to funguje dobře, jestli jsou ovšem slovníky které by se měly takhle používat v CPK navzájem disjunktní (nenapadá mě teď český výraz, pardon;-) nevím. Pokud by došlo ke smíchání nesouvisejících slov dohromady, vzroste počet false positive výsledků, které budou navíc z uživatelského pohledu dost nepochopitelné. (Nicméně nevím jestli něco takového reálně hrozí...)

**Comment by PetraZabickova** [comment]
V tuto chvíli viz odkazy fungují pouze pro jmenné autority, v ostatních případech zatím ještě neobohacujeme.

**Comment by PetraZabickova** [comment]
Nyní již při indexaci záznamů dochází k obohacování záznamů o nepreferované termíny u všech autorů, korporací, témat a žánrů, které mají $7 s vazbou na národní autority.
