### ISSUE TITLE
Nápověda na titulní stránce

### ISSUE THREAD

**Issue by Stoklasovab** [moravianlibrary/CPK#71]
Nápověda na titulní stránce by měla fungovat opravdu jako nápověda a po kliknutí na určitý řádek by neměly probíhat změny přímo v ostré verzi dokumentu.

**Comment by PetraZabickova** [comment]
Ano, samozřejmě, že nápověda bude fungovat jako statický dokument. V tuto chvíli je vytvořena tímto způsobem, aby ji bylo snadné modifikovat a přidávat komentáře.

**Comment by PetraZabickova** [comment]
Bude přepracováno jakmile se zásadním způsobem přestane měnit rozhraní.
