### ISSUE TITLE
Dostupnost dokumentu - úpravy

### ISSUE THREAD

**Issue by Stoklasovab** [moravianlibrary/CPK#72]
U dostupnosti dokumentu je třeba odstranit anglické hlášky
![anglicke hlasky](https://cloud.githubusercontent.com/assets/11761577/11039736/687fb004-8709-11e5-878b-b2387e4781ed.jpg) 
a zmenšit písmo  v kolonce oddělení, aby se rozumně vešly i delší texty

**Comment by PetraZabickova** [comment]
Mírnou úpravu velikosti písma jsme udělali, ale nepomohlo to. Myslíme si, že pokud to písmo zmenšíme ještě více, tak bude natolik malé, že s ním někteří uživatelé budou mít problém. 

Uvědomujeme si, že některé knihovny tak mnoho informací o svých jednotkách nezobrazují, na druhou stranu některé toho zobrazují ještě mnohem více. Pokud bychom odstranili některý se zobrazovaných sloupců (údajů), mohli bychom zásadním způsobem narušit srozumitelnost objednávek u některých specifických typů dokumentů a knihoven.

Budeme rádi za názor, co s tím.

**Comment by vojtisev** [comment]
Nebyl by nějaký konkrétní titul, kde bychom pro lepší představu viděli vyplněné všechny údaje z tabulky? 

Tabulka si zároveň příliš nerozumí s responzivní variantou (screenshot z console pro iphone 5) a lámáním slov dokonce na desktopu.

![screenclip](https://cloud.githubusercontent.com/assets/11600358/15611001/8fb43700-2428-11e6-84af-ca1d295f1892.png)
![screenshot-beta knihovny cz 2016-05-27 16-28-20](https://cloud.githubusercontent.com/assets/11600358/15611000/8fb23072-2428-11e6-89a2-af841a4108fa.png)

**Comment by jankanka** [comment]
Neni to sice moc bezne, ale nedalo by se i na dekstopu jit spise tou cestou vice radku pro jeden exemplar, jak je to vyse na "telefonnim" zobrazeni? Sloupce budou vzdycky omezujici.
![exemplare](https://cloud.githubusercontent.com/assets/16186956/15859287/cb1f97c2-2cc4-11e6-8aeb-f504a44844a6.jpg)

**Comment by Stoklasovab** [comment]
Nechat stávající stav.
