### ISSUE TITLE
Přesunutí vypínání filtrů k vyhledávacímu poli

### ISSUE THREAD

**Issue by mjtecka** [moravianlibrary/CPK#73]
Doporučil bych zvážit přesun vypínání zapnutých filtrů k vyhledávacímu poli.

- když zadávám dotaz, dívám se na pole dotazu.. v současném layotu se ještě musím podívat doprava na nastavení filtrů; zapomínám na to a pak dostávám jiné výsledky než čekám
- v mobilní verzi je to celé uplně dole, musí se k tomu prorolovat přes seznam výsledků

- příklad reálného použítí tohohle způsobu v e-shopu je tu:
http://store.steampowered.com/search/?snr=1_4_4__12&term=star+trek

Mohlo by to vypadat třeba nějak takhle:
![modified-1024](https://cloud.githubusercontent.com/assets/11203453/11153087/d816e6d2-8a36-11e5-91e3-6025e0173e45.png)

Místo současného:
![current-1024](https://cloud.githubusercontent.com/assets/11203453/11153084/d033179c-8a36-11e5-8b51-26bc56e3b8e8.png)

**Comment by paulusova** [comment]
Fasety se budou přesouvat doleva, takže filtry budou blíž vyhledávacími poli, to by mohlo pomoct (mobilní verzi to ale neřeší).

**Comment by mjtecka** [comment]
Přesunutí faset doleva by mohlo pomoct, ale pořád tam zůstane takovej "zub". 

Jsem jediný komu tam vadí? ;-)

![current-1024-fields-left](https://cloud.githubusercontent.com/assets/11203453/11340604/e68a3438-91fe-11e5-8173-8ae0787ef421.png)

**Comment by zabak** [comment]
fasety začínají nadpisem upřesnit hledání, ne až fasetou instituce.

**Comment by mjtecka** [comment]
zabak: 
Jenze tohle je ovladaci prvek ktery zaroven urcuje co se bude hledat pokud je zapnute "zachovat soucasne nastaveni filtru". Jeho funkce je jina nez funkce faset.

Pokud chci vytvorit novy dotaz, musim se zkratka podivat na vsechno v tom modrem poli - to co navrhuju je dat to vic vizualne k sobe.
![modified-1024-fields-left](https://cloud.githubusercontent.com/assets/11203453/11342679/dc1fee7a-9208-11e5-9d49-cb198acfecda.png)

**Comment by zabak** [comment]
OK. Jenže proti tomu stojí návrh aby označení která faseta je zvolena bylo přímo vidět v dané fasetě. Leda že by se použilo obojí.

**Comment by mjtecka** [comment]
Obojí je tam i teď; jednou s křížkem, jednou s háčkem, ale jak na to tak klikám tak se mi zdá že obě varianty dělají to samé.

**Comment by vojtisev** [comment]
Přijde mi to jako dobrý nápad - zvlášť s ohledem na responzivitu. Mohlo by to fungovat i v momentě, kdybychom se rozhodli nemít faset tolik. 

Tomu, že se zobrazují oba stavy fasety také úplně nerozumím.

![screenshot-beta knihovny cz 2015-11-23 22-27-10](https://cloud.githubusercontent.com/assets/11600358/11350391/9f1a4588-9231-11e5-9bc6-6d7a9b091008.png)
