### ISSUE TITLE
Výsledky vyhledávání - "Žádné výsledky!"

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#75]
![screenshot-beta knihovny cz 2015-11-23 23-48-51](https://cloud.githubusercontent.com/assets/11600358/11352473/cbe9b886-923c-11e5-8801-ac6500dfc409.png)

Bylo by možné přidat zadaný dotaz do search query předáváného v URL, pokud kliknu na odkazy vedoucí na vyhledávání Google, nebo JIB (tj. v tomto konkrétním příkladě překlad na "https://www.google.cz/search?q=dfahfeofah+fdaf"? Takhle mě to jenom přesměruje na homepage daných vyhledávačů.

Zároveň bych navrhoval, abychom právě skrze tuto stránku odkazovali uživatele na pokročilé vyhledávání.

**Comment by paulusova** [comment]
Odkazy upravíme. 
Jak by mělo upozorňování na pokročilé vyhledávání vypadat?

**Comment by paulusova** [comment]
Odkazy upraveny.
