### ISSUE TITLE
Individualizované doporučování uživateli

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#77]
pokračování https://github.com/moravianlibrary/CPK/issues/53
Individualizované doporučování konkrétnímu uživateli na základě jeho výpůjční historie je jediná oblast, kde je historie jeho výpůjček nutná (a pak samotné zobrazení historie výpůjček danému uživateli). Ostatní požadavky lze realizovat na základě jiných údajů. Nejsem si ale jistý, že je možné doporučené knihy "vypočítat" v reálném čase na základě údajů stažených přes API, zvlášť pokud by těch výpůjček v historii bylo hodně. Možná by byla na toto lepší nějaká forma sklízení a indexace, ale to s sebou nese další problémy.

**Comment by PetraZabickova** [comment]
Prosím o zvážení potřeby této funkčnosti a rozhodnutí, zda ji skutečně máme implementovat.

Obáváme se, že tato funkčnost mohla být v rozporu s požadavky na maximální obezřetnost v práci s osobními údaji uživatelů. V tuto chvíli si totiž portál historii výpůjček uživatelů nedrží a pro tuto funkci by to bylo nezbytné.

**Comment by vojtisev** [comment]
Co kdybychom to nepočítali v reálném čase, ani z historie výpůjček, ale místo toho připravili vyhledávací dotazy / dávky titulů a uživatele bychom nechali naklikat si nabídku ("co mě zajímá") a na základě těchto preferencí mu tituly doporučovali? Součástí tohoto úvodního zaškatulkování by mohl být také souhlas se zpracováním pouze těchto údajů - další bychom uchovávat nemuseli.

**Comment by black23** [comment]
To, co navrhuje @vojtisev zní jako realizovatelné kompromisní řešení, které se nedotkne osobních údajů. Navíc by to technicky nemuselo představovat náričný problém.

**Comment by jankanka** [comment]
Nechci se drzet zbytecne pri zemi, ale povazoval bych za velky uspech, kdyby se podarilo opravdu dobre OBECNE doporucovani (na zaklade obsahove a zanrove podobnosti titulu). To individualizovane bych nechal az na pozdeji.

**Comment by Stoklasovab** [comment]
Realizovat a odladit obecné doporučování a individualizované odložit.

**Comment by PetraZabickova** [comment]
Úprava doporučování byla nasazena začátkem roku 2020 a průběžně testována. Doporučování není řešeno individualizováně na základě toho, co si uživatelé půjčují, ale díky hledání vazeb mezi různými bibliografikými záznamy. Při porovnávání výstupů různých aplikací pro doporučování výsledky našeho řešení vycházejí velmi slibně, stejně ale jako jiné systémy nedokáží doporučovat vše na 100%.

Další úpravy doporučovacího mechanismu se v nejbližší době neplánují.
