### ISSUE TITLE
Drobečková navigace

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#8]
Do všech stránek přidat cestu, pokud to VuFind umožňuje, aby se mohl uživatel vrátit např. o krok zpět nebo alespoň do stránky jednotlivých záznamů přidat návrat do seznamu výsledků.

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
Drobečková navigace (kterou vufind defaulně má) byla odstraněna na základě sílícíh požadavků o minimalistický a jednoduchý vzhled. Inspirací bylo také rozhraní, které vzniklo na základě uživatelské testování (projekt MKP).  Bude nutno projednat PS.
