### ISSUE TITLE
Vyhledávací dotaz z našeptávače

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#80]
Bylo by možné, aby po kliknutí na našeptané slovo proběhlo rovnou vyhledávání? V současnosti se mi pouze vyplní vyhledávací okno a musím znovu enterovat / klikat. 
![12 prosince 2015 212605 cet](https://cloud.githubusercontent.com/assets/11600358/11763772/70447f90-a117-11e5-80ce-4f078e0f0192.jpg)

**Comment by paulusova** [comment]
Děkujeme za postřeh, tohle nám uteklo. Opravíme.
