### ISSUE TITLE
Procházení výsledků dotazu v detailech a návrat na výsledky

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/CPK#81]
Chybí mi procházení výsledků dotazu z jednoho detailního záznamu na následující a předchozí - tak jak je to na VF MZK. A možná by mohl být v detailu i odkaz "Zpět na výsledky" - aby se nemuselo používat BACK v browseru.

**Comment by PetraZabickova** [comment]
Odkaz zpět na výsledky dotazů jsme přidali. 

Bohužel v tuto chvíli nejsme schopni přidat možnost přepínání na následující a předchozí záznamy. Řešení, které bychom v tuto chvíli mohli použít totiž nefunguje v případě, že má uživatel otevřeno více než jedno okno s výsledky hledání.

Vyřešení této situace by znamenalo zásadním způsobem přepsat celé chování Vufindu, což nyní nemůžeme udělat. 

Bylo nám doporučeno, že používat funkce, které nejsou spolehlivé a ne vždycky fungují, je pro uživatele matoucí a nežádoucí a je lepší je vůbec nepoužít.

**Comment by black23** [comment]
Zpět na výseldky již existuje, takže to uzavřeme?

**Comment by jankanka** [comment]
Uzaviram.
