### ISSUE TITLE
Posílání záznamu SMSkou

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/CPK#82]
Co by bylo třeba udělat, aby bylo možné odeslat si záznam SMSkou na mobil (jak bývá v "amerických" VuFindech)? Máme nějakou SMS bránu, kterou bychom mohli použít? Určitě by to řadu uživatelů potěšilo.

**Comment by black23** [comment]
My využíváme pro zasílání SMS z Kohy API SMSbrana.cz. Jedna zpráva stojí cca 80 haléřů. Muselo by se na to myslet ve financování. V objemu malé knihovny nejde měsičně o závratnou částku, ale v případě CPK by to mohlo být i v řádu tisiců Kč/měsíc. Ale dala by se domluvit jistě lepší cena.
Ekonomicky únosnější by bylo možná zvolit formu přeposlané notifikační SMS z e-mailu. To vyžaduje nastavení uživatelem a má to nějaká omezení.
https://www.t-mobile.cz/e-mail-do-sms
o2 stačí poslat e-mail na: 00420xxxyyyyyy@sms.cz.o2.com
Vodafone: jmeno@vodafonemail.cz
Vždy to zákazník musí mít povoleno.

**Comment by zabak** [comment]
My umíme i posílat SMS přímo ze serveru přes vlastní SIM kartu, když na to přijde (už to děláme cca 10 let, ale není to redundantní, při výpadku kritických kousků hardwaru by ta služba nemusela nějakou dobu jet). Samozřejmě při větší zátěži by se mohlo stát, že se SMS brána zahltí, to ale až tak nehrozí. Ale tohle je věc která nemá vysokou prioritu, vzhledem k tomu, že využití asi nebude vysoké.

**Comment by PetraZabickova** [comment]
Pokud bude funkčnost odsouhlasena ES, tak SMS bránu náplánujeme do rozpočtu na příští rok.

**Comment by black23** [comment]
IMHO SMS by bylo zajímavější poižívat spíše na nějaké notifikace. Posílat záznamy opravdu asi bude jen minimum lidí.

**Comment by vodomilka** [comment]
Možnost poslat záznam sms zahustí zobrazené rozhraní pro uživatele, přitom tuto možnost využije zřejmě jen zlomek uživatelů, takže bych ji raději nezahrnovala do nabídky. Souhlasím, že smysl má zasílat spíše notifikace k účtu.

**Comment by KarolinaKostalova** [comment]
Posílat nalezené záznamy smskou mi nepřijde uplně nutné. Nejsem si jistá, do jaké míry si uživatelé sdílí nebo navzájem posílají záznamy o nalezené "skvělé" knížce tímto způsobem.  Ale přijde mi, že tak malá skupina, že to v tuto chvíli není potřeba.

**Comment by Stoklasovab** [comment]
Zatím nerealizovat.
