### ISSUE TITLE
Sdílítka typu AddThis / ShareThis do detailu a do výsledku dotazu

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/CPK#84]
Bylo by dobré přidat do detailu sdílítko typu AddThis / ShareThis. A kdyby to šlo, tak i do výsledku vyhledávání - odeslání emailem je výborné, ale je to jen jedna cesta komunikace. (Kromě jiného mají tyhle služby pěkně udělané statistiky o tom, co a jak se sdílí.)

**Comment by vojtisev** [comment]
Osobně jsem spíš proti - statistiky jsou dobré, ale za sebe bych nejraději viděl CPK co nejčistší, nejrychlejší. Sociální tlačítka vždy web zpomalí, sbírají data uživatelů a životnost (oblíbenost) se může také dost měnit (viz např. http://www.mightybytes.com/blog/social-buttons-pros-and-cons/). Pochopil bych to spíš u blogu, nebo aktualit o CPK, kde je cílem získat větší publikum, ale u vyhledavače nám to IMHO nic nepřinese.

**Comment by PetraZabickova** [comment]
Vzhledem k protichůdným reakcím, prosíme o jednotné stanovisko.

**Comment by zabak** [comment]
Mohli bychom tam mít jedno tlačítko, které by nic nesbíralo, protože by potřilo nám - po jeho zmáčknutí by se teprve objevila nabídka různých tlačítek/sdílítek, podobně jako na mobilu.

**Comment by jankanka** [comment]
Pokud by to takhle slo, bylo by to z meho pohledu idealni.

**Comment by black23** [comment]
Přikláním se k názoru @zabak

**Comment by lenkamaixnerova** [comment]
Taky souhlasím s @zabak

**Comment by Stoklasovab** [comment]
Realizovat návrh  @zabak

**Comment by PetraZabickova** [comment]
Hotovo.
