### ISSUE TITLE
Fasety - rozklik dalších úrovní

### ISSUE THREAD

**Issue by jankanka** [moravianlibrary/CPK#86]
Navrhuju změnit a zvětšit prvek rozbalující další úroveň faset. Ten trojůhelník / šipka nemluví tak jasnou řečí, jako např zaužívané znaménko plus ve čtverečku (může působit např. jen jako zvýraznění apod.). Na dotykových zařízeních je ten prvek pro některé prsty ;) hodně malý a při tapnutí se nechtěně vybere něco jiného. Tohle je nepříjemné zvlášť ve fasetě Zdroje (dojde k zatržení checkboxu).

**Comment by PetraZabickova** [comment]
Ano, pracujeme na tom.

**Comment by paulusova** [comment]
V v2.7.0 je zvýraznění fasety Instituce, do dalších verzí spravíme i pro další hierarchické fasety.
