### ISSUE TITLE
Druh dokumentu - e-kniha?

### ISSUE THREAD

**Issue by vojtisev** [moravianlibrary/CPK#88]
Zkoušel jsem si vyfiltrovat všechny e-knihy z CPK a nenašel jsem způsob, jak to udělat. Počítáme s tím?

Druhy dokumentů tam máme - audioknihy, dvd, cd, el. zdroje, ... Také způsob získání (několik typů online).

Mělo by se výhledově jednat minimálně o stovky titulů (MKP), až tisícovky (eReading), které lze získat online. Považoval bych proto jako uživatel za výhodné, abych se k tomu snadno dostal.

Ještě příklad e-knihy indexované ze souborného katalogu:
https://beta.knihovny.cz/Record/caslin.SKC01-006692032/EVersion#tabnav
- má druh dokumentu "kniha", přestože se jedná o e-knihu. Možná to můžeme také nějak ošetřit v našich datech?

![fasety_e-knihy_screenshot-beta knihovny cz 2016-01-17 22-25-24](https://cloud.githubusercontent.com/assets/11600358/12380233/1c14a9cc-bd6e-11e5-8737-85b695f5f83e.png)

**Comment by PetraZabickova** [comment]
Dobrý den,

děkujeme za připomínku. 

Ve většině případů je možné použít kombinaci filteru elektronický zdroj + kniha. V daném případě to možné není, protože kódované údaje tohoto záznamu  https://beta.knihovny.cz/Record/caslin.SKC01-006692032/EVersion#tabnav neobsahují informaci o tom, že se o elektronickou publikaci jedná.

K správnému  výsledku by se měl dostat také v případě použití kombinace filteru kniha + způsob získání online, kde jsou navíc zahrnuty přístupy k online  dokumentu přes pole 856. Bohužel ve velkém množství polí 856 se nachází smetí, která nás vedlo k tomu, abychom všechny záznamy s obsahem pole 856 označili jako elektronické dokumenty.

Původně jsme zvažovali zavést typ dokumentu elektronická kniha. V takovém případě bychom ale museli zavést také typ elektronický časopis, elektronická mapa, elektronická norma, elektronický zvuk, elektronický článek, ... A forma elektronická není jediná možná, která může nastat, co takový mikrodokument nebo braille? Proto nám přišlo jednodušší umožnit publikacím získat více typu dokumentů v kombinaci.

Naše možnosti jsou následující:
- typy dokumentů přepracujeme, otázka je jestli se nám jednotlivé typy ale neznásobí na neúnosné množství
- můžeme přiřadit typ elektronický dokument všem záznamům, které mají  pole 856, což ale bohužel nemůžeme nikdy zaručit že bude správně
- můžeme vygenerovat nějaké seznamy záznamů k opravám, opravy bude ale nutno udělat i v souborném katalogu

Budeme rádi za další návrhy a možnosti řešení.

**Comment by PetraZabickova** [comment]
Jen pro vysvětlenou proč ne všechny údaje v poli 856 jsou spolehlivé:

- odkazy zastarávají a přestávají platit
- ne vždy je v poli správně použit druhý indikátor, který by umožnil rozeznat typ odkazu
- mnohé knihovny používají pole pro specifické odkazy, které nefungují mimo danou knihovnu a syntaxe takových odkazů je velmi proměnlivá. Tento třetí problém bychom sice mohli řešit tím, že odkazy z pole 856 budou fungovat jen pouze pro tu knihovnu, která záznam do portálu poslala, tím bychom ale zase znemožnili tyto informace sdílet navzájem napříč všemi zdeduplikovanými záznamy.

**Comment by PetraZabickova** [comment]
V případě požadavku na předělání fasety Typu dokument jiným způsobem než nyní je, žádáme expertní skupinu o přesnou specifikaci jak. 

Stávající specifikace je pro představu k nahlédnutí zde:
https://docs.google.com/spreadsheets/d/1VA0MgzImAAdd0la0zjPxLLWlrAiPD1PKsBXvRgmpHGM/edit?usp=sharing

**Comment by black23** [comment]
Co s tím?

**Comment by jrmeixner** [comment]
V případě centrálního indexu musíme s typem dokumentu "elektronická kniha" nebo "e-kniha" počítat. CI pokrývá záznamy titulů e-knih z multioborových kolekcí vydavatelů/agregátorů v řádu statisíců titulů e-knih. Při slučování výsledků se záznamy z lokálního (národního) indexu a následném odfiltrování výsledků pouze na e-knihy by absence typu dokumentu pro e-knihy na straně LI mohla být problémem. U knihoven s vlastními linkservery by pro identifikaci kniha X e-kniha možná pomohly indexace exportu holdingů, ve kterých budou e-knihy zahrnuty a tištěné knihy ne.

**Comment by lenkamaixnerova** [comment]
já bych navrhovala nechat typ dokumentu kniha s možností podkategorie tištěná kniha, ekniha , pokud nechceme mít podkategorie tak klidně přejmenovat na kniha/e-kniha (takto to má např. Summon)

**Comment by Stoklasovab** [comment]
Ponechat stávající řešení a doladit v souvislosti s testováním/implementací CI, kdy začne věc být naléhavá.
