### ISSUE TITLE
Další pole v seznamu výsledků hledání - 773tg

### ISSUE THREAD

**Issue by PavlinaDolezalova** [moravianlibrary/CPK#89]
Ještě bych navázala na https://github.com/moravianlibrary/CPK/issues/9. Bylo by možné zobrazování 773tg přidat i do seznamu výsledku hledání? To, že je už 773tg v úplném zobrazení, je super. A nebo pro typ dokumentu článek automaticky rozbalovat fasetu "Zdrojový dokument". Ideálně obé.

**Comment by paulusova** [comment]
Přidali jsme do výsledků vyhledávání zobrazování 773tg.

**Comment by PavlinaDolezalova** [comment]
OK.
