### ISSUE TITLE
Další pole v úplném zobrazení

### ISSUE THREAD

**Issue by paulusova** [moravianlibrary/CPK#9]
Zobrazit v záznamu – 773tgx, 856, 902a, byl by možný i permalink záznamu?

navrhuje Mgr. Pavlína Doležalová

**Comment by PetraZabickova** [comment]
Odkaz z pole 856 se zobrazuje v záložce E-zdroje. 

773txg i 902a můžeme přidat, pokud to nebude v rozporu s názory ostatních.

Permalink přidáme, ale je potřeba počítat s tím, že bude funkční pouze tak dlouho, dokud bude existovat daný záznam ve zdrojové knihovně/databázi.

**Comment by PavlinaDolezalova** [comment]
Doufám, že nebude, 773txg jsou pole pro analytiku a 902s chtějí (naši) čtenáři.

**Comment by PavlinaDolezalova** [comment]
Bylo by možné zobrazování 773tg přidat i do seznamu výsledku hledání? To, že je už 773tg v úplném zobrazení, je super. A nebo pro typ dokumentu článek automaticky rozbalovat fasetu "Zdrojový dokument". Ideálně obé.

**Comment by PetraZabickova** [comment]
viz 89
