### ISSUE TITLE
Obálky ve čtenářském kontě

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#93]
Je v plánu zobrazovat obálky i v seznamech aktuálníhc výpůjček, oblíbených atp.?

**Comment by paulusova** [comment]
Ano, u některých knihoven už se zobrazují všude, pro Kohu je potřeba doladit, viz https://github.com/moravianlibrary/CPK/issues/51

**Comment by black23** [comment]
Doladit na naší straně?

**Comment by paulusova** [comment]
To už bohužel nevím, zjistím a dáme vědět.

**Comment by PetraZabickova** [comment]
Opravili jsme.
