### ISSUE TITLE
Název UNIMARC/MARC

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#95]
Nepřejmenujeme na "Zobrazit metadata záznamu" nebo něco popisnějšího?

**Comment by vodomilka** [comment]
To je poměrně dlouhé, zvlášť, když si to představím jako popis záložky v mobilní verzi. Nestačila by jen "Metadata" nebo jen "MARC"?

**Comment by black23** [comment]
Zobrazit MARC?

**Comment by black23** [comment]
Pokud jednou bude součástí CPK systém na řešení MVS, mohlo by se celá sekce jmenova "Pro knihovny" a obsahovat i tlačítko na objednávku MVS. Jak to mají kolegové v Ústí nad Orlicí.

**Comment by zabak** [comment]
nejde jen o MARC, jindy může jít o Dublin Core. Takže Metadata je lepší. Ale otázka je spíš jestli tam ta záložka má vůbec být.

**Comment by vodomilka** [comment]
Za uživatele to vidím jako zcela minimálně využívanou položku, ale bavili
jsme se o tom, že pro knihovníky je nezbytná. Byla by varianta, že by
záložka metadata mohla být skrytá a objevila se, pokud by se do URL adresy
záznamu přidalo třeba /metadata ?


2016-03-01 23:59 GMT+01:00 zabak <notifications@github.com>:

> nejde jen o MARC, jindy může jít o Dublin Core. Takže Metadata je lepší.
> Ale otázka je spíš jestli tam ta záložka má vůbec být.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moravianlibrary/CPK/issues/95#issuecomment-190951171>.
>



-- 
Veronika Hyblerová Trachtová
+420 602 863 861
LinkedIn <http://cz.linkedin.com/in/veronikatrachtova> / Twitter
<https://twitter.com/vodomilka>
V každém mailu pozitivní zprávu.

**Comment by paulusova** [comment]
Něco podobného momentálně máme pro seznam zdeduplikovaných záznamů (v podstatě záložka s  roletkou) vedle záložky UNIMARC/MARC. Dá se ní kliknout, ale nemá popis, takže není vidět. Nechceme ji zobrazovat, ale hodí se nám pro kontrolu deduplikací.

**Comment by black23** [comment]
Pak by bylo systémovější zobrazovat ten tab jen přihlášeným uživatelům, kteří jsou knihovníci. Pokud tedy máme možnost rozlišovat běžné uživatele a knihovníky. Přes NCIP informace o kategorii čtenáře snad prochází, ale opět bychom řešili různé označení v různých knihovnách/systémech. Nicméně, přidávat ručně něco do URL není správně.

**Comment by Stoklasovab** [comment]
Určitě metadata obecně, protože to nemusí být jen MARC, jak píše Petr. A běžným uživatelům skrýt, ale tak, aby se k tomu mohli nějakým rozumným způsobem dostat. K mému překvapení občas používali MARCový záznam i běžní uživatelé, třeba proto, že si nebyli jisti anglickou terminologií a zajímaly je anglické ekvivalenty předmětových hesel, které pak používali i pro hledání jinde atd.

**Comment by vodomilka** [comment]
Než to budeme složitě vymýšlet, jak to skrýt a přitom běžným
(neknihovníkům) uživatelům zpřístupnit, máte prosím někdo k dispozici
statistiku, kolik % ze zobrzaneých záznamů si uživatelé překliknou na
zobrazení metadat? Třeba z KNAVu nebona JIB?


2016-03-02 10:23 GMT+01:00 Bohdana Stoklasová <notifications@github.com>:

> Určitě metadata obecně, protože to nemusí být jen MARC, jak píše Petr. A
> běžným uživatelům skrýt, ale tak, aby se k tomu mohli nějakým rozumným
> způsobem dostat. K mému překvapení občas používali MARCový záznam i běžní
> uživatelé, třeba proto, že si nebyli jisti anglickou terminologií a
> zajímaly je anglické ekvivalenty předmětových hesel, které pak používali i
> pro hledání jinde atd.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moravianlibrary/CPK/issues/95#issuecomment-191149614>.
>



-- 
Veronika Hyblerová Trachtová
+420 602 863 861
LinkedIn <http://cz.linkedin.com/in/veronikatrachtova> / Twitter
<https://twitter.com/vodomilka>
V každém mailu pozitivní zprávu.

**Comment by paulusova** [comment]
Přihlášený uživatel má v účtu nastavení, kde si může nastavit formát citace, počet výsledků na stránku, podle čeho se mu řadí výsledky, ... Šlo by tam dát i možnost ne/zobrazování tabu s metadaty.

**Comment by vojtisev** [comment]
@paulusova to mi přijde jako dobrý nápad.

**Comment by Stoklasovab** [comment]
Metadata jsou nyní pro nezasvěcené dost nesrozumitelná. Možná lepší než Metadata by bylo Úplná nebo Podrobná metadata a pak formát s návěštími místo MARCu. Někdo může mít zájem o podrobná metadata, ale v "lidské" podobě. Volbu formátu nechat pro přihlášené a nutnost přihlášení pro volbu formátu avizovat dole pod metadaty?

**Comment by PetraZabickova** [comment]
Obávám se, že podrobná metadata v lidské podobě nedodáme. Mimo jiné proto, že existuje řada polí převážně 9XX a písmenných, která v různých knihovnách znamenají různé věci, respektive se o jejich existenci vůbec nedozvíme. 

Prosíme expertní skupinu o konečné označení pojmenování tabu. V případě, že ES bude trvat na jeho odstranění, tak z něj uděláme konfigurovatelnou položku pro přihlášeného uživatele. Myslíme si, že by to ale šlo proti rozhodnutí nechat nepřihlášeného uživatele využívat portál maximálně.

**Comment by Stoklasovab** [comment]
Probereme to, ale odstranit určitě ne.

**Comment by PavlinaDolezalova** [comment]
MARC/UNIMARC nechat tak jak je, tj. v "lidské" řádkové verzi (verze s návěštími - slovními popisky tagů nejsou třeba), a jeho název "metadata" je dost vypovídající. Zobrazovat pro všechny, i pro nepřihlášené již s ohledem na to, že v podrobném záznamu se nezobrazují všechny údaje, např. 902 (u tohoto pole jen první výskyt).

**Comment by vojtisev** [comment]
Souhlasím s @PavlinaDolezalova

**Comment by jrmeixner** [comment]
Také jsem pro název záložky "Metadata" a řádkovou verzi MARCu/UNIMARCu.

**Comment by lenkamaixnerova** [comment]
Souhlasím s názvem "Metadata" a řádkovou verzi MARCu/UNIMARCu

**Comment by jankanka** [comment]
Vida, tohle tema (pro "normalni" uzivatele naprosto marginalni) nas bavi skoro nejvic ;) Myslim, ze zalozka musi (pro nas) zustat a Metadata jsou co mozna nejsrozumitelnejsi.

**Comment by KarolinaKostalova** [comment]
Souhlasím s pojmenováním Metadata a řádkové verzi marcu.

**Comment by black23** [comment]
Máme Metadata, takže zavírám.
