### ISSUE TITLE
Řešení stránkování

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#96]
Nedávno proběhla diskuze ohledně řešení stránkování, objevil jsem článek, který se tématem zabývá podrobně a ukazuje výhody a nevýhody některých řešení (zobrazit další, automatické zobrazování dalších). Posílám pro inspiraci:
https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/

**Comment by PetraZabickova** [comment]
Děkujeme za inspiraci.
