### ISSUE TITLE
E-mail správci knihovního systému, pokud CPK zjistí nefunkčnost spojení

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#97]
Bylo by velmi užitečné, aby CPK při prvním neúspěšném pokusu o připojení do systému knihovny, byl odeslán e-mail správci s popisem problému. Měla by se testovat dostupnost NCIP, Aleph API, ale i OAI provideru, případně i zdroje kalendáře akcí. Bez toho se správce často nedozví, že něco nefunguje například po upgrade systému. Ušetří to čas lidem z CPK a pomůže zkrátit čas nedostupnosti na minimum.

**Comment by PetraZabickova** [comment]
Děkujeme, ano víme, chystáme a dáme Vám vědět, jakmile zrealizujeme.

**Comment by xmorave2** [comment]
Bylo v provozu, neosvědčilo se. Nenašli jsme zatím ideální způsob jak to řešit, ale je to i pro nás jedna z priorit.
