### ISSUE TITLE
Jak máme řešit odepsané tituly v OAI?

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#98]
Jak máme označit tituly, v OAI setu, které jsme odepsali?

**Comment by PetraZabickova** [comment]
Smazané záznamy by měly být dle specifikace OAI označeny v hlavičce jako deleted.

Příklad:
<record>
<header status="deleted">
<identifier>KN3171000000000945</identifier>
<datestamp>2016-09-18T08:31:54Z</datestamp>
<setSpec>KN</setSpec>
</header>
</record>

Pokud knihovní systém takovýto způsob označování smazaných záznamů neumožňuje, tak je nutné se na způsobu předávání této informace individuálně domluvit.
